### DISCUSSION TITLE
Permission Denied for Data Prepper Config File

### DISCUSSION THREAD

**Discussion by rajavajra** [opensearch-project/data-prepper#2463] [Q&A]
When I try to use docker-compose I am receiving a permission denied error

```
Caused by: java.io.FileNotFoundException: /usr/share/data-prepper/config/data-prepper-config.yaml (Permission denied)
```
This is a test setup so I have 777 permissions set on the file, and the owner is opensearch
![Screenshot from 2023-04-07 10-31-39](https://user-images.githubusercontent.com/130164517/230651949-d95322a5-7899-480e-8a8e-3acea628c001.png)

my docker compose for data-prepper is below

```
  data-prepper:
    container_name: data-prepper
    image: docker.io/opensearchproject/data-prepper:latest
    volumes:
      - ./log-pipeline.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml:rw
      - ./data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml:rw
    networks:
      - opensearch-net
```
I also receive the following error in the same log 

```
Error creating bean with name 'dataPrepper' defined in URL [jar:file:/usr/share/data-prepper/lib/data-prepper-core-2.1.1.jar!/org/opensearch/dataprepper/DataPrepper.class]: Unsatisfied dependency expressed through constructor parameter 0
```
Below is the data prepper config file
```
ssl: false
```

here is the full log file I get 

[dataprepper.log](https://github.com/opensearch-project/data-prepper/files/11180489/dataprepper.log)

if there is any other information needed please let me know
