### DISCUSSION TITLE
Kafka Bitnami Helm Integration

### DISCUSSION THREAD

**Discussion by jmtt89** [opensearch-project/data-prepper#3503] [Q&A]
Hi, please someone can guide me on the steps to add source of Kafka generated with the Bitnami helm chart?

when install Bitnami Kafka helm chart them include a note:
```
The CLIENT listener for Kafka client connections from within your cluster have been configured with the following security settings:
- SASL authentication

To connect a client to your Kafka, you need to create the 'client.properties' configuration files with the content below:

security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-256
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
username="user1" \
password="$(kubectl get secret kafka-0000000-user-passwords --namespace default -o jsonpath='{.data.client-passwords}' | base64 -d | cut -d , -f 1)";
```

after reading comments and source i think that is a valid configuration:

```
      source:
        kafka:
          bootstrap_servers:
            - kafka-0000000.default.svc.cluster.local:9092
          topics:
            - name: test
              group_id: groupID1
          authentication:
            sasl:
              oauth:
                oauth_security_protocol: SASL_PLAINTEXT
                oauth_sasl_mechanism: SCRAM-SHA-256                
                username: user1
                password: pass1
```

but i dont find how include `sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="user1" password="pass1";`

in the source code i found references to `org.apache.kafka.common.security.plain.PlainLoginModule` but no for `org.apache.kafka.common.security.scram.ScramLoginModule` 

someone knows a workaround to include custom `sasl.jaas.config` ?
