### DISCUSSION TITLE
Can't you automatically turn off the bin/data-prepper?

### DISCUSSION THREAD

**Discussion by sc303030** [opensearch-project/data-prepper#4273] [Q&A]
I'm installing it directly on Linux and using the version below.
Version: **opensearch-data-prepper-2.7.0-SNAPSHOT-linux-x64**

Once a month, csv files are created in a specific folder (ex.test). I want to insert data into Opensearch through data prepper, so I want to change the layout to crontab. I want to read the first file using the for statement, and when data is registered in opensearch, I want to exit the data prepper and register the second file. However, after the first file is registered, the data prepper is not finished, so I cannot read the second file. Can you finish it automatically?? Is there any good way?

```yaml
version: 2
sample-pipeline:
  workers: 8
  delay: 100
  source:
    file:
      path: "/mnt/storage1/test/202403_2/df_1000000.csv"
      codec:
        csv:
  buffer:
    bounded_blocking:
      buffer_size: 10000000
      batch_size: 1000000
  sink:
    - opensearch:
        hosts: ["localhost:9200"]
        username: "admin"
        password: "admin"
        index: "df_1000000_20240313_112146"
        insecure: true
```

```sh
folder=202403_2

prepper_file=/mnt/storage1/opensearch/data-prepper/release/archives/linux/build/install/opensearch-data-prepper-2.7.0-SNAPSHOT-linux-x64

today=$(date "+%Y%m%d_%H%M%S")

for file in /mnt/storage1/test/$folder/*
do
        echo "file: $file"

        name_split=($(echo $file | tr "/" "\n")) 
        name=($(echo ${name_split[4]} | tr "." "\n")) 
        echo "name: $name"
        
        yq e --inplace '.sample-pipeline.source.file.path="'$file'"' $prepper_file/pipelines/pipelines.yaml   
        cat $prepper_file/pipelines/pipelines.yaml    | grep path
        yq e --inplace '.sample-pipeline.sink[0].opensearch.index="'$name'_'$today'"' $prepper_file/pipelines/pipelines.yaml   
        cat $prepper_file/pipelines/pipelines.yaml    | grep index
        echo ""

        $prepper_file/bin/data-prepper
done
```

![image](https://github.com/opensearch-project/data-prepper/assets/52574837/f7400d9c-f62c-4ca7-9e53-0f9a531b9557)
