### DISCUSSION TITLE
OTLP/gRPC or OTLP/HTTP sink

### DISCUSSION THREAD

**Discussion by rhys-evans** [opensearch-project/data-prepper#4356] [Ideas]
Hi

I would like to send OTLP data (in particular trace data, for my use case) to any OTLP compatible backend. 

Would this be supported by an HTTP sink "extension" ?

Ideally for me this would take batched trace data from S3 eg

OTEL Collector example: (not complete)
```
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
            cors:
              allowed_origins:
                - "http://*"
                - "https://*"

    exporters:
      awss3:
        s3uploader:
            region: us-west-2
            s3_bucket: "tempo-traces-bucket"
            s3_prefix: 'metric'
            s3_partition: 'minute'

    processors:
      batch:
        send_batch_size: 10000
        timeout: 30s
      resource:
        attributes:
        - key: service.instance.id
          from_attribute: k8s.pod.uid
          action: insert
      memory_limiter:
        check_interval: 5s
        limit_mib: 200

    service:
      pipelines:
        traces:
          processors: [memory_limiter, resource, batch]
          exporters: [awss3, spanmetrics]
```

Dataprepper pipeline config example idea:
```
traces-pipeline:
  workers: 2
  delay: "100"
  source:
    s3:
        notification_type: sqs
        compression: automatic
        sqs:
            queue_url: "https://sqs.eu-west-1.amazonaws.com/<account_id>/queue"
        aws:
            region: "us-west-2"
  buffer:
    bounded_blocking:
      buffer_size: 4096
      batch_size: 512
  processor:
    - parse_json:
  sink:
    - otlp:
        endpoint: http://otlp-backend
```

Thoughts ? 

There seems to have been a attempt (I have not tested it) to do this in logstash here https://github.com/paulgrav/logstash-output-opentelemetry/blob/main/README.md

**Comment by KarstenSchnitter** [comment]
The main challenge will be to map events to the proper format. OpenTelemetry uses a complex data models for each of the supported signals: [logs](https://opentelemetry.io/docs/specs/otel/logs/data-model/), [metrics](https://opentelemetry.io/docs/specs/otel/metrics/data-model/) and traces. The resource linked by @rhys-evans only covers logs, which are currently the easiest format to generate. It is missing the instrumentation scope entirely, too. 

An OpenTelemetry sink most likely requires complex configuration on field mappings and aggregations. Specification of the intended signal type is required too, since OpenTelemetry uses different endpoints for each one of those. Switching between gRPC and http/protobuf transport is another feature and requires implementation of two (not so) different clients. The configuration might look similar to the OpenTelemetry Collector:

```yaml
sink:
  - otlp/logs:
    network:
      endpoint: otlp-backend
      tls:
        cert: cert.pem
        key: key.pem
    resource:
      service.name: field_key
    instrumentation:
      scope: field_key
    attribute:
      name: field_key
    body: field_key
```

However, there will be a lot more details. E.g. all (resource) attributes and the body can be of several types: string, integer, hash,...
This is a challenge for parsing arbitrary data.

I wonder, whether this feature is not already provided in a more mature form by the OpenTelemetry Collector.
