### ISSUE TITLE
Processor Ids

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1025]
# Introduction

A Data Prepper pipeline can contain multiple sources, processors, and sinks with the same type. Presently, these cannot be distinguished.

# Proposed Solution

Data Prepper should assign a unique identifier for each pipeline component.

Additionally, pipeline authors may wish to configure some component Ids. This can help them debug their pipelines and make them more readable.

The following example shows how a pipeline author can configure the Id using an `id` property:

```
log-pipeline:
  source:
    http:
  prepper:
    - grok:
        id: extract-apache-logs
        match:
          log: [ "%{COMMONAPACHELOG}" ]
  sink:
    - opensearch:
        id: opensearch-a
        hosts: [ "https://opensearch-host-a" ]
    - opensearch:
        id: opensearch-a
        hosts: [ "https://opensearch-host-b" ]
```

Pipeline authors do not need to configure the `id`. Data Prepper will produce a default value.

## Id Generation

The default Id generation should be deterministic. This will allow the peer-forwarder to use the `id` of a component and consistently supply Events to the correct component in a peer node.

The default Id generation can be:

```
${pluginType}${incrementedCount > 1 ? incrementedCount : ''}
```

The `incrementedCount` will be a number which is incremented for each component type individually. It can thus be stored in a map: `Map<String, Integer> typeToIncrementedCount`. The count will be incremented before applying the function above. So the first of any given type has `incrementedCount == 1`. This approach allows the pipelines without duplicates to continue to use the `pluginType` without having a trailing `1`.

### No Configured Ids

```
log-pipeline:
  source:
    http:
  prepper:
    - grok:
        match:
          log: [ "%{COMMONAPACHELOG}" ]
  sink:
    - opensearch:
        hosts: [ "https://opensearch-host-a" ]
    - opensearch:
        hosts: [ "https://opensearch-host-b" ]
```

The Ids are:

* `http`
* `grok`
* `opensearch`
* `opensearch2`

### Some Configured Ids

```
log-pipeline:
  source:
    http:
  prepper:
    - grok:
        match:
          log: [ "%{COMMONAPACHELOG}" ]
  sink:
    - opensearch:
        hosts: [ "https://opensearch-host-a" ]
    - opensearch:
        hosts: [ "https://opensearch-host-b" ]
```

The Ids are:

* `http`
* `extract-apache-logs`
* `opensearch-a`
* `opensearch2`

# Alternatives

## Duplicates Always Have Count Suffix

Another approach is to identify any plugin type that has more than one plugin in the pipeline. Only those that have more than one will have a suffix. This can be nice because each plugin of the same type has a more consistent name.

The disadvantage is that it may be more complicated to support. Is the improvement to the name really worthwhile here? Pipeline authors who want better names can control the `id` already.

```
log-pipeline:
  source:
    http:
  prepper:
    - grok:
        match:
          log: [ "%{COMMONAPACHELOG}" ]
  sink:
    - opensearch:
        hosts: [ "https://opensearch-host-a" ]
    - opensearch:
        hosts: [ "https://opensearch-host-b" ]
```

The Ids are:

* `http`
* `grok`
* `opensearch1`
* `opensearch2`

## Count Across Components

Data Prepper could increment a universal count. The disadvantage is that when there is only one processor of a type it gets some number behind it.

```
log-pipeline:
  source:
    http:
  prepper:
    - grok:
        match:
          log: [ "%{COMMONAPACHELOG}" ]
  sink:
    - opensearch:
        hosts: [ "https://opensearch-host-a" ]
    - opensearch:
        hosts: [ "https://opensearch-host-b" ]
```

The Ids are:

* `http1`
* `grok2`
* `opensearch3`
* `opensearch4`
