### ISSUE TITLE
Support SQS as a Source

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1049]
```
log-pipeline:
  source:
    sqs:
        queues: 
           - url: "https://sqs.us-east-1.amazonaws.com/myQueue1"
             polling_frequency: 5m
             batch_size: 10
             number_of_threads: 2
           - urls: "https://sqs.us-east-1.amazonaws.com/myQueue2"
             polling_frequency: 1m
             batch_size: 10
             number_of_threads: 3
```

The data from the queue will be sent to the buffer as:

```
{
  "message" : "{messageBody}"
}
```

It should also include queue metadata:

```
{
  "queueUrl" : "https://sqs.us-east-1.amazonaws.com/myQueue1",
  "sentTimestamp" : 1720679777
```

**Comment by dlvenable** [comment]
As a follow-on we should also support an optional codec. The default behavior will be to put the message on the SQS queue, but we can support codecs for when an SQS message contains multiple events.

For example, a user could create a JSON array with multiple events:

```
{ "someArbitraryKey" : [
  { ... event1 ... },
  { ... event2 ... },
  ...
] }
```

The JSON codec already supports this:

```
source:
  sqs:
    codec:
      json:
```
