### ISSUE TITLE
[BUG] Can't dump OTEL traces to stdout or file

### ISSUE THREAD

**Issue by enp** [opensearch-project/data-prepper#1075]
It looks like no way to transmit OTEL traces to some simple output like stdout or file

With configuration like so:

```
entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
  sink:
    - file:
        path: /data/data-prepper/prepper.json
```

I see error:

```
data-prepper      | 2022-02-19T08:39:16,313 [entry-pipeline-prepper-worker-1-thread-1] INFO  com.amazon.dataprepper.pipeline.ProcessWorker -  entry-pipeline Worker: Processing 1 records from buffer
data-prepper      | 2022-02-19T08:39:16,336 [entry-pipeline-sink-worker-2-thread-1] ERROR com.amazon.dataprepper.pipeline.common.PipelineThreadPoolExecutor - Pipeline [entry-pipeline] process worker encountered a fatal exception, cannot proceed further
data-prepper      | java.util.concurrent.ExecutionException: java.lang.ClassCastException: class io.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest cannot be cast to class java.lang.String (io.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
```

With:

```
entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
  sink:
    - stdout:
```

error is even more helpful:

```
data-prepper      | 2022-02-19T08:46:06,315 [entry-pipeline-prepper-worker-1-thread-1] INFO  com.amazon.dataprepper.pipeline.ProcessWorker -  entry-pipeline Worker: Processing 1 records from buffer
data-prepper      | 2022-02-19T08:46:06,323 [entry-pipeline-sink-worker-2-thread-1] ERROR com.amazon.dataprepper.pipeline.common.PipelineThreadPoolExecutor - Pipeline [entry-pipeline] process worker encountered a fatal exception, cannot proceed further
data-prepper      | java.util.concurrent.ExecutionException: java.lang.RuntimeException: Invalid record type. StdOutSink only supports String and Events
```

So, maybe it is possible to dump traces as json?
