### ISSUE TITLE
Provide a migration path to using Events for Trace data

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1158]
**Is your feature request related to a problem? Please describe.**

Data Prepper's existing Trace Analytics source and processors operate on `ExportTraceServiceRequest` records. Each of these `ExportTraceServiceRequest` objects contains multiple spans. With the new Event model, the Trace Analytics source and processors should operate on spans instead.

The current work to migrate to spans changes the way that the buffer behaves. With this change, the buffer will need to have many more records in it. Each record is smaller and thus the overall buffer size in MB should be the same. But, the buffer count does need to change.

If Data Prepper releases with the new Event model, then existing pipelines will experience a performance degradation which we have measured to be about half the throughput. Pipeline authors must reconfigure their pipeline to get back the original throughput.

Because this is somewhat of a breaking change, Data Prepper should have a migration path toward using the new model.

**Describe the solution you'd like**

Provide a migration path for existing Data Prepper pipelines to move to the new model.

* Add a new `otel_trace_raw` processor which operates on the new Event model.
* Keep `otel_trace_raw_prepper` on the old model.
* Add a `record_type` field to `otel_trace_source` to allow it to send out Events instead of the old model.

Here is a conceptual pipeline (shortened for brevity):

```
otel-trace-pipeline:
  source:
    otel_trace_source:
      record_type: event
  buffer:
    bounded_blocking:
       # Original recommendation of 512, multiplied by 20
       buffer_size: 10240
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"
raw-pipeline:
  source:
    pipeline:
      name: "otel-trace-pipeline"
  buffer:
      bounded_blocking:
         # Configure the same value as in otel-trace-pipeline
         buffer_size: 10_240
  processor:
      # This used to be the otel_trace_raw_prepper.
    - otel_trace_raw:
  sink:
    ...
```

**Describe alternatives you've considered (Optional)**

1) Require pipeline authors update their pipeline. This would not be a good experience and I don't think we should take this approach.
2) Force the migration in Data Prepper 2.0. Pipeline authors would need to make changes to support Data Prepper 2.0. I think having a migration path is more ideal.

**Additional context**

Related issue: #546 

Existing work: https://github.com/opensearch-project/data-prepper/tree/maint/546-migrate-trace-analytics-to-event-model
