### ISSUE TITLE
[BUG] Data Prepper Expression string starting in / is considered escaped Json Pointer

### ISSUE THREAD

**Issue by sbayer55** [opensearch-project/data-prepper#1188]
**Describe the bug**
Data Prepper Expression string where the first character is `/` are evaluated as escaped Json Pointer.

**To Reproduce**

Using the following configuration:
```yaml
simple-pipeline:
  workers: 1
  source:
      http:
        thread_count: 1
  prepper:
    - drop_events:
        drop_when: '/message == "/Hello"'
  sink:
    - file:
        path: /tmp/sink.log
```
1. Start Data Prepper
2. `curl -k -H "Content-Type: application/json" -d '{"message": "/Hello"}' 'http://localhost:2021/log/ingest`
3. Verify in `/tmp/sink.log` event was not dropped.

**Expected behavior**
Support for Strings starting in a forward slash '/'

**Screenshots**
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/8837988/158248313-7e92c69e-43ee-49d2-b549-8b26f113401c.png">

**Environment (please complete the following information):**
 - OS: MacOS 12.2.1
 - Version: Data Prepper 1.3.0

**Additional context**
n/a
