### ISSUE TITLE
[BUG] NoService document

### ISSUE THREAD

**Issue by elvince** [opensearch-project/data-prepper#1308]
**Describe the bug**
I created a test application with OTLP data and I can get any document in the ServiceMap Indice.

In a c# .net core console, add OpenTelemetry package and opentelemetry.exporter.opentelemetryprotocol

Add :
```
                var MyActivitySource = new ActivitySource(serviceName);

                using var activity = MyActivitySource.StartActivity("SayHello");
                activity?.SetTag("baz", new int[] { 1, 2, 3 });
```

Setup the OtelCollector to send data to the Data-prepper:
Config:
```
receivers:
  otlp:
    protocols:
      grpc:
        #endpoint: 0.0.0.0:55680

exporters:
  otlp/2:
    endpoint: localhost:21890
    tls:
      insecure: true
      insecure_skip_verify: true
  logging:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/2]
```

when the trace reach the server, it is consumed and sent to OpenSearch but only the raw-pipeline seems to send data.

**Expected behavior**
service-map-pipeline should send document to open search

**Environment (please complete the following information):**
 - OS: Windows - Data-preper is running on latest docker image
 - Version Latest as of 11 april 22

No sure it is a bug or something wrong in my configuration.
Is there any configuration to set to have verbose log that can help in tracking why the servicemap pipeline is not sending data?
