### ISSUE TITLE
Complex documentId fields in OpenSearch sink

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1456]
**Is your feature request related to a problem? Please describe.**

Some events going to OpenSearch should have a document id (`_id`) set to a field within a sub-object. For example, `info/id` rather than `id`. Currently Data Prepper's `document_id_field` property only supports a field which is directly in the root of the event.

**Describe the solution you'd like**

Support the JSON Pointer syntax that Data Prepper is using throughout in the `document_id_field` property for Data Prepper.

Example configuration:

```
sink:
  - opensearch:
       hosts: ["https://my-opensearch"]
       document_id_field: info/id
```

Given the following event, Data Prepper will produce a document with `_id` set to `json001`:

```
"fieldA" : "arbitrary value",
"info" : {
  "id" : "json001",
  "fieldA" : "xyz",
  "fieldB" : "def"
}
```
