### ISSUE TITLE
Dynamic Index Name in OpenSearch sink

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1459]
**Is your feature request related to a problem? Please describe.**

Some use-cases require placing different documents in different dynamic indices. Pipeline authors want to configure a dynamic index name that is derived from a property (or multiple properties) in a Data Prepper event.

**Describe the solution you'd like**

Support dynamic index names using a format string. This format string can use `${}` to signal string interpolation and use JSON Pointer for getting fields from events. For example: `metadata-${metadataType}`.

```
pipeline:
  ...
  sink:
    opensearch:
      hosts: ["https://opensearch-host"]
      index_type: custom
      index: "metadata-${metadataType}"
```

**Describe alternatives you've considered (Optional)**

Using conditional routing could allow for supporting a predefined number of indices. However, this approach has a very practical bound. Using this format string allows for unlimited (from Data Prepper's perspective) indices.

**Additional context**

N/A
