### ISSUE TITLE
[BUG] Certificate issue on otel_trace_source

### ISSUE THREAD

**Issue by elvince** [opensearch-project/data-prepper#1599]
**Describe the bug**
I'm using the same certificate on Http source as in otel_trace_source .
On otel_trace_source, I received a ". HttpRequestException: The SSL connection could not be established, see inner exception. AuthenticationException: Authentication failed" error when trying to push events.

**To Reproduce**
Here are the way I setup the sources:
```
  otel_trace_source:
      ssl: true
      sslKeyCertChainFile: "certificat.crt"
      sslKeyFile: "certificat.key"
       # Explicitly disable authentication
      authentication:
        unauthenticated:
      port: 2022
```
```
http:
      ssl: true
      ssl_certificate_file: "certificat.crt"
      ssl_key_file: "certificat.key"
      # Explicitly disable authentication
      authentication:
        unauthenticated:
     port: 2021
```
**Expected behavior**
No error on connection

**Environment (please complete the following information):**
 - Public Docker image

Is there anything specific to otel_trace_source in term of certificate?
Thanks,
