### ISSUE TITLE
[BUG] Health Check returns 401 when Auth is enabled

### ISSUE THREAD

**Issue by dinujoh** [opensearch-project/data-prepper#1600]
**Describe the bug**
Health Check to Log Source or Otel Source returns 401 when Auth is enabled. If we have data prepper fronted by load balancer and load balancer is doing health check, the health check path should be excluded from Auth.

**To Reproduce**
1. Configure the Data Pepper Pipeline config with Auth
```
source:
  http:
    authentication:
      http_basic:
        username: my-user
        password: my_s3cr3t
```
2. Start Data Prepper
3. curl http://localhost:2021/health

**Expected behavior**
return Http status 200 with response {}.

**Screenshots**
```
curl http://localhost:2021/health
401 Unauthorized%
```

**Environment (please complete the following information):**
 - OS: Linux
