### ISSUE TITLE
raw-span-policy  delete action

### ISSUE THREAD

**Issue by arulselvan** [opensearch-project/data-prepper#1751]
how to replace/override raw-span-policy?  I need to include the delete action for otel-v1-apm-span-* during data-prepper setup time

thanks!

**Comment by sshivanii** [comment]
Hi @arulselvan,
The `index` reserved will always be `otel-v1-apm-span` when using `trace_analytics_raw` `index_type`, and it cannot be replaced. For reference, here's the configuration for [Raw Span Trace Analytics](https://github.com/opensearch-project/data-prepper/blob/caebb1964233c0d400ef40c8c7c24353ee3091ff/data-prepper-plugins/opensearch/README.md#raw-span-trace-analytics).
However, an alternative suggestion would be to switch to **custom** `index_type` and then specify the `index` you want to create. The default `index_type` is custom so specifying the `index` should be sufficient, in the following way:
```
pipeline:
  ...
  sink:
    opensearch:
      hosts: ["https://localhost:9200"]
      cert: path/to/cert
      username: YOUR_USERNAME_HERE
      password: YOUR_PASSWORD_HERE
      index: my-index-name
```
