### ISSUE TITLE
Provide a trace_peer_forwarder plugin

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1759]
**Is your feature request related to a problem? Please describe.**

The Core Peer Forwarding (#700) feature will replace the existing `peer-forwarder`. However, an ideal trace pipeline should forward events prior to the `raw_trace` and `service_map_stateful` processors.

**Describe the solution you'd like**

Create a `trace_peer_forwarder` plugin. Thus, we can create a pipeline like the following.

```
entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
  processor:
    - trace_peer_forwarder:
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"
raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
```

It can forward based on the `traceId`.

**Describe alternatives you've considered (Optional)**

Rely exclusively on `service_map_stateful` and `otel_trace_raw`. But, then the events will need to be forwarded twice.
