### ISSUE TITLE
Support custom headers when assuming AWS IAM roles

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1888]
**Is your feature request related to a problem? Please describe.**

Some use-cases require adding new headers to IAM requests made to STS when performing an `iam:AssumeRole` action. Data Prepper can provide support for pipeline authors to configure these headers.

**Describe the solution you'd like**

Provide configurations to modify these headers when assuming roles in the `s3` source and the `opensearch` sink.

```
source:
  s3:
    aws:
      sts_role_arn: arn:aws:iam::123456789012:role/MyS3Role
      sts_header_overrides:
        my-header-name1: my-header-value1
        my-header-name2: my-header-value2
sink:
  - opensearch:
      aws_sts_role_arn: arn:aws:iam::123456789012:role/MyOpenSeachRole
      aws_sts_header_overrides:
        my-header-name3: my-header-value3
        my-header-name4: my-header-value4
```

**Describe alternatives you've considered (Optional)**

Data Prepper could support a global configuration for this. But that is a fairly large change that requires some design.
