### ISSUE TITLE
Kubernetes deployment template needs an update

### ISSUE THREAD

**Issue by oeyh** [opensearch-project/data-prepper#1922]
[Kubernetes deployment template](https://github.com/opensearch-project/data-prepper/blob/main/deployment-template/k8s/data-prepper-k8s.yaml) needs an update to reflect the new directory structure in 2.0:

```
      containers:
        - args:
            - java
            - -jar
            - /usr/share/data-prepper/data-prepper.jar
            - /etc/data-prepper/pipelines.yaml
            - /etc/data-prepper/data-prepper-config.yaml
          image: opensearchproject/data-prepper:latest
          name: data-prepper
```

**Comment by rafael-gumiero** [comment]
Hello, I had the same problem to use version 2.0 and I changed it as follows:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data-prepper
  name: data-prepper
  namespace: data-prepper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-prepper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: data-prepper
    spec:
      containers:
        - args:
            - /usr/share/data-prepper/bin/data-prepper
            - /etc/data-prepper/pipelines.yaml
            - /etc/data-prepper/data-prepper-config.yaml
          image: opensearchproject/data-prepper:latest
          name: data-prepper
          ports:
            - containerPort: 21890
              protocol: TCP
            - containerPort: 2021 # Port for http source communication
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/data-prepper
              name: prepper-configmap-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: prepper-configmap-claim0
          configMap:
            name: data-prepper-config
status: {}
---
```

**Comment by rafael-gumiero** [comment]
But I believe my configuration was not the best choice because the log says that the ability to specify these paths will be removed in the next release.

```
Data Prepper now supports reading pipeline and data-prepper configuration files
from Data Prepper home directory automatically.
You can continue to specify paths to configuration files as command line arguments,
but that support will be dropped in a future release.
```

**Comment by rafael-gumiero** [comment]
Now I believe it got better.

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data-prepper
  name: data-prepper
  namespace: data-prepper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-prepper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: data-prepper
    spec:
      containers:
        - image: opensearchproject/data-prepper:latest
          name: data-prepper
          ports:
            - containerPort: 21890
              protocol: TCP
            - containerPort: 2021 # Port for http source communication
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: prepper-configmap-config
              mountPath: /usr/share/data-prepper/config/data-prepper-config.yaml
              subPath: data-prepper-config.yaml

            - name: prepper-configmap-pipelines
              mountPath: /usr/share/data-prepper/pipelines/pipelines.yaml
              subPath: pipelines.yaml             
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: prepper-configmap-config
          configMap:
            name: data-prepper-config
            items:
            - key: data-prepper-config.yaml
              path: data-prepper-config.yaml

        - name: prepper-configmap-pipelines
          configMap:
            name: data-prepper-config
            items:
            - key: pipelines.yaml 
              path: pipelines.yaml             
status: {}
---
```
