### ISSUE TITLE
[BUG] Unable to read from S3 key with spaces

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1923]
**Describe the bug**

The Data Prepper S3 source is unable to read from keys with spaces in them.

**To Reproduce**

Simple pipeline:

```
log-pipeline:
  source:
    s3:
      notification_type: "sqs"
      codec:
        newline:
      sqs:
        queue_url: "https://sqs.us-east-1.amazonaws.com/123456789012/MyPipeline"
      aws:
        region: "us-east-1"

  processor:
  sink:
    - stdout:
```

Here is a sample file:

```
cat "has some spaces.log"
This file has spaces.
Two to be precise.
```

Upload that file:

```
aws s3 cp "has some spaces.log" s3://s3-source-manual-test/
```

**Expected behavior**

The S3 object should be read just like the one without spaces.

**Actual Outputs**

```
2022-10-15T16:56:08,659 [Thread-1] WARN  org.opensearch.dataprepper.plugins.source.SqsWorker - Unable to process S3Object: s3ObjectReference=[bucketName=***, key=has+some+spaces.log].
software.amazon.awssdk.services.s3.model.NoSuchKeyException: The specified key does not exist. (Service: S3, Status Code: 404, Request ID: ***, Extended Request ID: ***)
```

**Environment (please complete the following information):**

Data Prepper Docker build from `main`.

Files uploaded via macOS.

**Additional context**

The following values come from the S3 Console:
The S3 URI looks like:

S3 URI: `s3://***/has some spaces.log`

Object URL: `https://***.s3.amazonaws.com/has+some+spaces.log`

ARN: `arn:aws:s3:::***/has some spaces.log`
