### ISSUE TITLE
Poll CloudWatch for metrics as a source

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#1987]
**Is your feature request related to a problem? Please describe.**

Pipeline authors want to get metrics out of Amazon CloudWatch to send to either OpenSearch or Prometheus.

**Describe the solution you'd like**

Create a CloudWatch source plugin which retrieves metrics from CloudWatch. It should put those metrics into the Data Prepper in the current Metrics model, which is based on the OpenTelemetry specification.

```
source:
  cloudwatch:
    namespace: ES/OpenSearchService
    metric_name: ShardCount
    dimensions:
      - name: DomainName
        value: my-domain
```

As this is a polling source, it should also allow pipeline authors to define a poll interval similar to the S3 source.

It also needs to have AWS configurations. These can follow similar conventions to other AWS-based plugins.

**Describe alternatives you've considered (Optional)**

An alternative design would be to put the metrics into the buffer in the CloudWatch format. Then pipeline authors could configure a processor which performs the translation. This approach could be valuable if the translation is non-trivial and requires some additional configurations from pipeline authors. It could also be valuable if the translation is costly and we want to have it happen on data in the buffer.

**Additional context**

https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricStatistics.html
