### ISSUE TITLE
CloudWatch Logs as Source

### ISSUE THREAD

**Issue by ashoktelukuntla** [opensearch-project/data-prepper#1994]
**Is your feature request related to a problem? Please describe.**

Pipeline authors wanted to get Logs out of Amazon Cloud Watch to send to either OpenSearch or Prometheus

**Describe the solution you'd like**

Create a CloudWatch source plugin which retrieves logs from CloudWatch.I t should put logs into the Data Prepper in the current Metrics model, which is based on the OpenTelemetry specification.

```
source:
    cloudwatch:
    namespace: ES/OpenSearchService
    log_source: ShardCount
    dimensions:
      - name: DomainName
        value: my-domain
```
As this is a polling source, it should also allow pipeline authors to define a poll interval similar to the S3 source.

It also needs to have AWS configurations. These can follow similar conventions to other AWS-based plugins.

**Describe alternatives you've considered (Optional)**

**Additional context**

https://aws.amazon.com/premiumsupport/knowledge-center/cloudwatch-logs-retrieve-data/
https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/Welcome.html
