### ISSUE TITLE
Provide a type conversion / cast processor

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#2010]
**Is your feature request related to a problem? Please describe.**

Some pipelines have Event values in one type (e.g. string), but want to convert them to another type (e.g. integer).

**Describe the solution you'd like**

Provide a new convert processor along with the other Mutate Event Processors.

```
processor
    - convert_entries:
        entries:
        - from_key: "mySource"
           to_key: "myTarget"
           type: integer
```

The default value for `to_key` can be the `from_key`. So this could be simplified in some cases:

```
processor
    - convert_entries:
        entries:
        - from_key: "http_status"
           type: integer
```

**Additional context**

With conditional routing and expressions this can help pipeline authors perform better comparisons. It also allows for sending data to OpenSearch in a more desirable format.

See #2009 for a grok-based solution for a similar problem.
