### ISSUE TITLE
New Aggregate processor actions 

### ISSUE THREAD

**Issue by kkondaka** [opensearch-project/data-prepper#2015]
**Is your feature request related to a problem? Please describe.**
It would be nice to have aggregate action `count ` in the aggregate processor to count the number of events matching the specified identification_keys. The aggregation action should optionally support a condition under which the count action is done

**Describe the solution you'd like**
Provide a new action for "count" with optional condition as shown below 
```
processor:
  aggregate:
    identification_keys:
      - # ... Identification keys for the metric ...
      action:
        count: 
          [when: <condition>]
```
Examples

1. `Count `Aggregate Action - to count the messages with unique identification_keys with optional condition
Example 1 - Count the number of messages with clientip 127.0.0.1
```
processor:
  aggregate:
    identification_keys:
      - # ... Identification keys for the metric ...
      action:
        count: 
          when: '/clientip == "127.0.0.1"'
```
Example 2 - Count the number of messages with response code 503 or 404        
```
processor:
  aggregate:
    identification_keys:
      - # ... Identification keys for the metric ...
      action:
        count: 
          when: '/response == 503 or /response == 404'     
```
Example 3 - Count the number of messages with matching identification keys (No condition specified)
```
processor:
  aggregate:
    identification_keys:
      - # ... Identification keys for the metric ...
      action:
        count: 
```

**Additional context**
The following options can be added to this action in the future
- Make the action to delete all other fields (other than identification_keys)  from the event by default
- New fields like `start_time` and `end_time` may be added to the event when specified as config option as follows
```
processor:
  aggregate:
    identification_keys:
      - # ... Identification keys for the metric ...
      action:
        count: 
          [when: <condition>]
          [add_keys: ["start_time", "end_time"]]
```
