### ISSUE TITLE
Core Peer Forwarding documentation is not up to date for TLS configurations

### ISSUE THREAD

**Issue by pankdhnd** [opensearch-project/data-prepper#2036]
Description:
Peer Forwarding processor documentation from [this](https://github.com/opensearch-project/data-prepper/issues/700) page suggests use of below parameters to enableSSL/TLS

```yaml
peer_forwarder:
  ssl: true
  certificate:
    file:
      certificate_path: /usr/share/my/path/public.cert
      private_key_path: /usr/share/my/path/private.key
  authentication:
    unauthenticated:
  discovery_mode: "dns"
  domain_name: "data-prepper-cluster.my-domain.net"
```

The configuration listed on [docs page](https://github.com/opensearch-project/data-prepper/blob/main/docs/peer_forwarder.md) is different as given below:

```
peer_forwarder:
  ssl: true
  ssl_certificate_file: "<cert-file-path>"
  ssl_key_file: "<private-key-file-path>"yaml
```

But unfortunately both of the above configuration doesn't work. With above configs, data  prepper keep crashing with below exception:

`java.lang.IllegalArgumentException: ssl is enabled, sslKeyCertChainFile can not be empty or null`

Note: The full exception is huge, so I will put in the in the comment.

So just to t to try out, I provided the crt file in the `sslKeyCertChainFile` parameter from the exception message and after the configuration. and data prepper came up and running. Below is configuration I am using right now, which works without an issue:

```yaml
processor:
 - peer_forwarder:
     discovery_mode: "dns"
     domain_name: "data-prepper-headless"
     ssl: true
     sslKeyCertChainFile: "/certs/tls.crt"
```

I believe the implementation was changed at some place but the documentation is not yet updated

I request someone to please confirm if what I am saying is correct, so that I can create a PR for documentation
