### ISSUE TITLE
[BUG] Data Prepper can not write to Opensearch Datastream 

### ISSUE THREAD

**Issue by rospeelman** [opensearch-project/data-prepper#2037]
**Describe the bug**
Can not send logs to Opensearch Data stream

**To Reproduce**
1. create an index template for a data stream in Opensearch
2. use data-prepper to send logs with an index matching the index patern of the datastream
3. get the error "WARN  com.amazon.dataprepper.plugins.sink.opensearch.OpenSearchSink - Document [org.opensearch.client.opensearch.core.bulk.BulkOperation@c4aecd] has failure: java.lang.RuntimeException: only write ops with an op_type of create are allowed in data streams"

**Expected behavior**
write logs to Data stream

**Environment (please complete the following information):**
 - Running in docker (Docker Desktop 4.10.1)
 - using latest version of Opensearch
 - using latest version of Data prepper

**Comment**
I didn't find an option to set the op_typ.

**Comment by sshivanii** [comment]
Hi @rospeelman 

The reason you've encountered that error is because the OpenSearch Sink currently does not have [configuration](https://github.com/opensearch-project/data-prepper/tree/main/data-prepper-plugins/opensearch#configuration) options to specifically support data streams. I would encourage you to update this issue as a feature request or enhancement.

**Comment by cmanning09** [comment]
@rospeelman , have you tried manually creating the data stream prior to running data prepper? The error you provided appears to be on creation of the data stream. And as @sshivanii has pointed out, the current plugin does not support data stream configuration option. Ingesting of documents should be standard across indices and creating a stream prior may be a work-around until we have support for creating streams through the plugin.

**Comment by rospeelman** [comment]
I tested it again, creating the datastream bevor starting data prepper gets me the same result, as soon as i try to ingest data I get the same error.

**Comment by dlvenable** [comment]
@rospeelman , Have you tried disabling the `index_type` in Data Prepper's `opensearch` plugin?

As @cmanning09 pointed out, we do not currently support Data Streams. However, Data Prepper can ingest data into OpenSearch without attempting to manage the indices.

I believe the following two steps may work:
* Create the Data Stream outside Data Prepper
* Configure the `opensearch` plugin in Data Prepper to use `index_type: management_disabled `.

```
pipeline:
  ...
  sink:
    opensearch:
      hosts: ["https://localhost:9200"]
      index_type: management_disabled
```

There are additional details in this issue: 1051

Configuration reference: https://github.com/opensearch-project/data-prepper/tree/main/data-prepper-plugins/opensearch#configuration

**Comment by cameronattard** [comment]
The issue here is not related to creating a data stream - it is the action performed when sending requests to OpenSearch (it is set to index and cannot be changed to create). To solve this, Data Prepper should implement an action attribute on the OpenSearch sink, similar to what LogStash has done here - https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-action

**Comment by a13xie** [comment]
@cameronattard Exactly this. As soon as I saw this error message, I immediately went looking at the options for the OpenSearch sink expecting to find an option to configure the `op_type` that data-prepper sends. To my surprise, no such option is available at this time.

**Comment by StefanSa** [comment]
Hi there,
For us it would also be important that otel as source and datastream would work.

If i understand correctly, the "opensearch exporter" from otel currently only supports traces, but not logs and metrics.
However, Data Prepper traces, logs and metrics from otel, but no datastream to opensearch.

@dlvenable 
The current situation is not really helpful.

**Comment by StefanSa** [comment]
Hi @dlvenable @cmanning09 
Any progress or time frame here ?
The ticket has been open for almost a year and so far nothing has moved, whereas this feature would be very necessary.

**Comment by mmehrten** [comment]
Would also like to see DataPrepper support for data streams. With many tools (such as AWS OpenSearch Ingestion) moving to DataPrepper based ingestion stacks, and Data Stream based analytics stacks (e.g. OpenSearch Integrations), it would be great to see support for data streams in DataPrepper.

**Comment by Alankarsharma** [comment]
I was able to write data to DataStream by setting action to create and index_type to custom. DataStream I created manually.
Sample config:
```
log-pipeline:
  source:
    otel_logs_source:
      port: 2021
      ssl: false
      authentication:
        unauthenticated:
  processor:
  sink:
    - opensearch:
        hosts: [ "https://logs.sandbox.system.com" ]
        username: "test"
        password: "123!"
        index_type: custom
        index: system-dev-ecs
        action: create
```

**Comment by FishyFishPat** [comment]
Is there any update or working solution on this issue?

**Comment by PW999** [comment]
For our use case (pushing logs), we ended up with ISM and letting OpenSearch do the roll-over.

Everything is created using Terraform, so mind you that anything below that is in `${...}` will be resolved by Terraform only, not by data-prepper or otel.

ISM policy for automatic roll-over and deletion of old data:
```json
{
    "policy": {
        "policy_id": "${local.env}-ecs-ism",
        "description": "Changes replica count and deletes.",
        "error_notification": null,
        "default_state": "current",
        "states": [
            {
                "name": "current",
                "actions": [],
                "transitions": [
                    {
                        "state_name": "old",
                        "conditions": {
                            "min_index_age": "1d"
                        }
                    }
                ]
            },
            {
                "name": "old",
                "actions": [
                    {
                        "rollover": {
                            "min_index_age": "1d"
                        }
                    },
                    {
                        "replica_count": {
                            "number_of_replicas": 0
                        }
                    },
                    { 
                        "read_only": {} 
                    }
                ],
                "transitions": [
                    {
                        "state_name": "delete",
                        "conditions": {
                            "min_index_age": "14d"
                        }
                    }
                ]
            },
            {
                "name": "delete",
                "actions": [
                    {
                        "retry": {
                            "count": 3,
                            "backoff": "exponential",
                            "delay": "30m"
                        },
                        "delete": {}
                    }
                ],
                "transitions": []
            }
        ],
        "ism_template": [
            {
                "index_patterns": [
                    "${local.env}-ecs*"
                ],
                "priority": 1
            }
        ]
    }
}
```

We have the following rollover template which gives us an alias index without the sequence numbers in it.

```json
{
  "index_patterns": ["${var.env}-${each.value}*"],
  "template": {
   "settings": {
    "plugins.index_state_management.rollover_alias": "${var.env}-${each.value}"
   }
 }
}
```

Our otel collector has the following exporter:

 ```yaml
 otlp/ecs-logs:
    endpoint: http://${local.env}-data-prepper.${local.env}-monitoring:9060
    tls:
      insecure: true
      insecure_skip_verify: true
    retry_on_failure: 
      enabled: true
      initial_interval: 15s
      max_interval: 120s
      max_elapsed_time: 300s
```

and our data-prepper pipeline is as follow

```yaml
log-ecs-pipeline:
  workers: ${local.dataprepper_workers}
  delay: 2000
  buffer:
    bounded_blocking:
      buffer_size: ${local.dataprepper_buffer_size}
      batch_size: ${local.dataprepper_batch_size}
  source:
    otel_logs_source:
      port: 9060
      ssl: false
      health_check_service: false
      authentication:
        unauthenticated:
  processor:
  sink:
    - opensearch:
        hosts: [ "${local.opensearch_endpoint}" ]
        username: "${nonsensitive(data.vault_generic_secret.es.data.dataprepper_username)}"
        password: "${sensitive(data.vault_generic_secret.es.data.dataprepper_password)}"
        max_retries: 5
        index_type: custom
        ism_policy_file: /usr/share/data-prepper/pipelines/ecs-ism.json
        index: ${local.env}-ecs
        bulk_size: 5
```

It's a bit of a cobbled together solution, but it works good enough for us at this point and it mimic how we used to have logs when we were directly writing to ElasticSearch from fluentD

**Comment by dlvenable** [comment]
We are planning to add this feature to Data Prepper.

I'd like to propose the following configuration as part of this support.

```
sink:
    - opensearch:
        hosts: [ "https://localhost:9200" ]
        index: my-data-stream
```

When the `index_type` is not defined Data Prepper's `opensearch` sink would then:

1. Get the index to determine if this is a data stream or a normal index.
2. If it is a normal index, then proceed as usual
3. If it is a data stream, then:
  a. Check the configurations for any unsupported configurations on data streams (e.g. `action`, `index_template`)
  b. Setup ingestion for data streams

As data is being ingest, the `opensearch` sink:
* Always use the `create` action.
* If the `@timestamp` is not present, then automatically add it using the Event received time.
