### ISSUE TITLE
New data-prepper processor to detect Anomalies

### ISSUE THREAD

**Issue by kkondaka** [opensearch-project/data-prepper#2040]
**Is your feature request related to a problem? Please describe.**

It would be nice to have an anomaly detector processor that uses ML anomaly detector algorithms like "random-cut forest". Events (or aggregated events) may be passed through this processor to identify any anomalies and generate anomaly events.

**Describe the solution you'd like**
Provide a new processor that can detect anomalies using the user-configurable method/algorithm
```
processor:
    anomaly_detector:
        mode: "random-cut-forest.metrics.v1"
        keys: ["key1", "key2"]
```
The above configuration will create an anomaly detector processor that uses `random-cut-forest.metrics.v1` algorithm to detect anomalies in the event's key1 and key2 events.

For example, if the events are HTTP log message events with `client-ip`, `latency` as fields (along with others), values for `client-ip` and `latency` can be passed to the anomaly detector to identify any anomalies in the latencies of HTTP request/responses from the same source IP.

```
sample-pipeline:

  source:
    http:
      ssl: false
      port: 2021
  processor:
    - grok:
        match:
          message: ['%{IPORHOST:clientip} (?:%{WORD:ident}|-) (%{USER:auth}|-) \[%{HTTPDATE:timestamp}\] "(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})" %{NUMBER:response} (?:%{NUMBER:bytes}|-) %{BASE10NUM:latency} "(?:%{WORD:ref}|-)" %{GREEDYDATA:useragent}']
 processor:
    anomaly_detector:
        mode: "random-cut-forest.metrics.v1"
        keys: ["clientip", "latency"]
```

This is a new feature request that will accommodate using any supported ML algorithm to detect anomalies. Initially, we will have support for random cut forest algorithm only.

**Additional context**
The output event record when an anomaly is detected may have the following fields for the example above
```
{"latency":10.425959275971174,"clientip":"10.10.10.10","deviation_from_
expected":9.88751976547253,"grade":1.0,"confidence":0.9744249290428905}
```
