### ISSUE TITLE
[BUG] The json processor is not available

### ISSUE THREAD

**Issue by kaninaba94** [opensearch-project/data-prepper#2066]
**Describe the bug**
`json` processor is not available as documented in the [docs](https://opensearch.org/docs/2.0/clients/data-prepper/data-prepper-reference/#json).

**To Reproduce**
pipelines.yaml:
```
log-pipeline:
        source:
                http:
                        ssl: false
        processor:       
                 - json:
                         source: "log" 
        sink:
                - opensearch: ......
```

**Expected behavior**
The error should not occur, and ideally, my json-formatted logs should be parsed.

**Error message**
```

2022-12-08T18:19:24,398 [main] ERROR org.opensearch.dataprepper.parser.PipelineParser - Construction of pipeline components failed, skipping building of pipeline [log-pipeline] and its connected pipelines
org.opensearch.dataprepper.model.plugin.NoPluginFoundException: Unable to find a plugin named 'json'. Please ensure that plugin is annotated with appropriate values.

```

**Environment:**
 - docker host OS: Ubuntu 20.04 LTS 
 - docker image: opensearchproject/data-prepper:latest
