### ISSUE TITLE
[BUG] Opensearch sink, dynamic index not working

### ISSUE THREAD

**Issue by skylagallm** [opensearch-project/data-prepper#2070]
**Describe the bug**
It seems that using version 2.0.1 the dynamic index name (with index type custom) is not working when trying to create the index name starting from the value of a field inside a trace event.

**To Reproduce**
1. Data prepper config

```
entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
  sink:
    - pipeline:
        name: "raw-pipeline"
raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: ["https://<ENDPOINT>:443"]
        aws_sigv4: true
        aws_region: "eu-west-1"
        index: "otel-v1-apm-span-${resource.attributes.obs-tenant}-%{yyyy.MM.dd}"
        index_type: trace-analytics-raw
        trace_analytics_raw: true
```

2. My trace data inside Opensearch looks like:

```
[
  {
    "_index": "otel-v1-apm-span-${resource.attributes.obs-tenant}-2022.12.12",
    "_type": "_doc",
    "_id": "jTtrCIUB2abFRUifipmm",
    "_score": 0.6931471,
    "_source": {
      "traceId": "00000000000000000000e7a86b9eaece",
      "droppedLinksCount": 0,
      "kind": "SPAN_KIND_SERVER",
      "droppedEventsCount": 0,
      "traceGroupFields": {
        "endTime": "2022-12-12T22:09:28.160267Z",
        "durationInNanos": 108000,
        "statusCode": 0
      },
      "traceGroup": "HTTP GET /",
      "serviceName": "frontend",
      "parentSpanId": "",
      "spanId": "0000e7a86b9eaece",
      "traceState": "",
      "name": "HTTP GET /",
      "startTime": "2022-12-12T22:09:28.160159Z",
      "links": [],
      "endTime": "2022-12-12T22:09:28.160267Z",
      "droppedAttributesCount": 0,
      "durationInNanos": 108000,
      "events": [],
      "span.attributes.http@url": "/",
      "resource.attributes.client-uuid": "63d9e116e98c3b2",
      "resource.attributes.service@name": "frontend",
      "span.attributes.component": "net/http",
      "status.code": 0,
      "span.attributes.sampler@param": true,
      "span.attributes.http@method": "GET",
      "resource.attributes.ip": "10.10.10.10",
      "resource.attributes.opencensus@exporterversion": "Jaeger-Go-2.30.0",
      "resource.attributes.obs-tenant": "devsecops",
      "span.attributes.http@status_code": 200,
      "span.attributes.sampler@type": "const"
    }
  }
]
```

3. The trace is then added inside an index without parsing dynamically the value of **resource.attributes.obs-tenant** from the input data.
