### ISSUE TITLE
New aggregate processor action - percent sampler - to limit the number of events passed through aggregator to the specified percent

### ISSUE THREAD

**Issue by kkondaka** [opensearch-project/data-prepper#2094]
**Is your feature request related to a problem? Please describe.**
It would be nice to have sampling capability in aggregator actions to be able to allow certain (user configured) percent of events

This is a sub-issue of issue of #2015  

**Describe the solution you'd like**
Provide a new action`percent_sampler` that would limit the number of events to the specified percent in the configuration. Only `percent` number of events are allowed out of every 100 events.
```
processor:
  aggregate:
    identification_keys:
      - # ... Identification keys for the metric ...
      action:
        percent_sampler: 
           percent: 60
```
The above config would allow only 6 out of every 10 events received during the aggregation window.

**Additional context**
This action when combined with when condition of aggregation can be used to sample events matching a specific condition.
Percent Sampling is one of the policies of tail sampling provided by OTEL - https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/tailsamplingprocessor/README.md
