### ISSUE TITLE
[BUG] STDOUT not respecting Log4J configuration

### ISSUE THREAD

**Issue by iquirino** [opensearch-project/data-prepper#2116]
**Describe the bug**
I've updated my log4j configuration and it stopped to save logs o file system, so, it worked well.
I've fixed all log levels to errors but data-prepper continues printing the content of the logs received.

**To Reproduce**
1: Updated log4j configutation at '' with:

```
status = error
dest = err
name = PropertiesConfig

property.filename = log/data-prepper/data-prepper.log

appender.console.type = Console
appender.console.level = error
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{ISO8601} [%t] %-5p %40C - %m%n

rootLogger.level = error
rootLogger.appenderRef.stdout.ref = STDOUT

logger.pipeline.name = org.opensearch.dataprepper.pipeline
logger.pipeline.level = error

logger.parser.name = org.opensearch.dataprepper.parser
logger.parser.level = error

logger.plugins.name = org.opensearch.dataprepper.plugins
logger.plugins.level = error
```

2. I am currently using the default pipeline for open telemetry use case:

```
entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"
raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: [ "https://opensearch.stag.bolttechbroker.net" ]
        username: "edirect"
        password: "123@PenguinsCanFly;)"
        index_type: "trace-analytics-raw"
service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: [ "https://opensearch.stag.bolttechbroker.net" ]
        username: "edirect"
        password: "123@PenguinsCanFly;)"
        index_type: "trace-analytics-service-map"
```

**Expected behavior**
I dont want to have all requests logged to my console, I just want to have errors logged to it.

**Screenshots**
![image](https://user-images.githubusercontent.com/881117/210804388-6cf066d7-9665-4af4-af51-476183604918.png)

**Environment (please complete the following information):**
 - OS: Debian
 - Version: latest

**Additional context**
I am currently using the lates version of data-prepper
