### ISSUE TITLE
Feature request for merge_all aggregate action

### ISSUE THREAD

**Issue by KrishnanandSingh** [opensearch-project/data-prepper#2157]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a merge aggregate action. There is no way to preserve values from different events in aggregate action  for non identification_keys fields though they may contain useful data.

**Describe the solution you'd like**
Proposing a merge_all action which needs data_types for fields which we want to merge. The data type is needed for doing object comparisons.

_Pipeline_
```yml
aggregation-pipeline:
  workers: 2
  delay: "1000"
  source:
    file:
      path: /usr/share/data-prepper/files/example.log
      format: json
      record_type: event
  processor:
    - aggregate:
        identification_keys: ["ipv4_src_addr", "l4_src_port", "ipv4_dst_addr", "l4_dst_port", "protocol", "in_bytes", "in_pkts"]
        group_duration: 4s
        action:
          merge_all:
            data_types:
              output_snmp: "integer"
              flow_seq_num: "integer"
              src_tos: "integer"
              input_snmp: "integer"
              l4_dst_port: "integer"
              tcp_flags: "integer"
              in_bytes: "integer"
              in_pkts: "integer"
              protocol: "integer"
              flowset_id: "integer"
              version: "integer"
              dst_as: "integer"
              ip_dscp: "integer"
              l4_src_port: "integer"
              ipv4_src_addr: "string"
              first_switched: "string"
              last_switched: "string"
              ipv4_dst_addr: "string"
  sink:
    - stdout:
```

_Input_
```json
{"output_snmp": 2, "flow_seq_num": 700710, "src_tos": 64, "input_snmp": 10, "l4_dst_port": 22, "tcp_flags": 16, "in_bytes": 40, "in_pkts": 1, "ipv4_src_addr": "10.35.197.104", "first_switched": "2023-01-11t08:37:22.783z", "protocol": 6, "flowset_id": 257, "last_switched": "2023-01-11t08:37:22.783z", "version": 9, "dst_as": 0, "ip_dscp": 16, "ipv4_dst_addr": "10.46.1.138", "l4_src_port": 52114}
{"output_snmp": 9, "flow_seq_num": 48159, "src_tos": 64, "input_snmp": 1, "l4_dst_port": 22, "tcp_flags": 16, "in_bytes": 40, "in_pkts": 1, "ipv4_src_addr": "10.35.197.104", "first_switched": "2023-01-11t08:37:23.057z", "protocol": 6, "flowset_id": 256, "last_switched": "2023-01-11t08:37:23.057z", "version": 9, "dst_as": 0, "ip_dscp": 16, "ipv4_dst_addr": "10.46.1.138", "l4_src_port": 52114}
```

_Output_
```json
{"output_snmp":[9,2],"ip_dscp":16,"dst_as":0,"in_pkts":1,"src_tos":64,"ipv4_dst_addr":"10.46.1.138","first_switched":["2023-01-11t08:37:23.057z","2023-01-11t08:37:22.783z"],"flowset_id":[256,257],"l4_src_port":52114,"version":9,"flow_seq_num":[48159,700710],"ipv4_src_addr":"10.35.197.104","in_bytes":40,"protocol":6,"input_snmp":[1,10],"tcp_flags":16,"last_switched":["2023-01-11t08:37:23.057z","2023-01-11t08:37:22.783z"],"l4_dst_port":22}
```

**Describe alternatives you've considered (Optional)**
The put_all aggregate action keeps values from the last event thus losing information.

**Additional context**
The use case is to stitch different netflow logs into one.
