### ISSUE TITLE
Consistent AWS Pipeline Configurations 

### ISSUE THREAD

**Issue by cmanning09** [opensearch-project/data-prepper#2184]
**Is your feature request related to a problem? Please describe.**
aws: and aws_* options in yaml are not consistent in the pipeline configuration definitions. 

```
sqs:
  queue_url: "https://sqs.us-east-1.amazonaws.com/123456789012/ApplicationLoadBalancer"
  aws:
    region: "us-east-1"
    sts_role_arn: "arn:aws:iam::123456789012:role/Example-Role"
```
vs
```
- opensearch:
    aws_sts_role_arn: "arn:aws:iam::879571289017:role/rajs-osis-policy-role"
    aws_region: "us-west-2"
    aws_sigv4: true
```

**Describe the solution you'd like**
We should align / have consistent format
