### ISSUE TITLE
[BUG] High CPU load from plugins/buffer/blockingbuffer doRead

### ISSUE THREAD

**Issue by MrSparc** [opensearch-project/data-prepper#2244]
**Describe the bug**
I made a docker image of the main Git branch of DataPrepper (2.1.0-SNAPSHOT) 
The container from this local docker image  `opensearch-data-prepper:2.1.0-SNAPSHOT` is consuming 100% CPU (laptop's fan spinning at full rpm) when compared to a container with release image `opensearchproject/data-prepper:2` 

The only change to test both versions is simply change in `docker-compose.yaml` the container image:
```
data-prepper:
    restart: unless-stopped
    container_name: data-prepper
    #image: opensearchproject/data-prepper:2
    image: opensearch-data-prepper:2.1.0-SNAPSHOT
```

I attach screenshots of the analysis with JProfiler of the Data Prepper 2.1.0 container. 

Looks like this method is generating all this CPU load:
https://github.com/opensearch-project/data-prepper/blob/497bae2b191fb96144159bfc1229bf01b7b50a5c/data-prepper-plugins/blocking-buffer/src/main/java/org/opensearch/dataprepper/plugins/buffer/blockingbuffer/BlockingBuffer.java#L148

**To Reproduce**

1. Git clone and  build docker image of Data Prepper (HEAD rev of  clone was fb060f241d0a36ecd63b4e8b153cf727ff122fe3): 
```
./gradlew clean :release:docker:docker -Prelease
```

2. Run the following docker-compose that makes use the built image :

`docker-compose.yaml`:
```yaml
version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  opensearch-node2:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]'
    networks:
      - opensearch-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    #user: root # required for reading docker container logs
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"     # OTLP gRPC receiver
      - "4318:4318"     # OTLP HTTP receiver
    networks:
      - opensearch-net
    depends_on:
      - "data-prepper"

  data-prepper:
    restart: unless-stopped
    container_name: data-prepper
    #image: opensearchproject/data-prepper:2
    image: opensearch-data-prepper:2.1.0-SNAPSHOT
    volumes:
      - ./trace_analytics_no_ssl_2x.yml:/usr/share/data-prepper/pipelines/pipelines.yaml
      - ./data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
      - ./root-ca.pem:/usr/share/data-prepper/root-ca.pem
    ports:
      - "21890:21890"
      - "21891:21891"
      - "21892:21892"
    networks:
      - opensearch-net
    depends_on:
      - "opensearch-node1"

volumes:
  opensearch-data1:
  opensearch-data2:

networks:
  opensearch-net:
```
`trace_analytics_no_ssl_2x.yml`:
```yaml
entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      port: 21890
      ssl: false
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"
raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: [ "https://opensearch-node1:9200" ]
        insecure: true
        username: "admin"
        password: "admin"
        index_type: trace-analytics-raw
service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: ["https://opensearch-node1:9200"]
        insecure: true
        username: "admin"
        password: "admin"
        index_type: trace-analytics-service-map

otel-metrics-pipeline:
  source:
    otel_metrics_source:
      port: 21891
      ssl: false
      authentication:
        unauthenticated:
  processor:
    - otel_metrics_raw_processor:
  sink:
    - opensearch:
        hosts: ["https://opensearch-node1:9200"]
        insecure: true
        username: "admin"
        password: "admin"
        bulk_size: 10
        index_type: custom
        index: otel-v1-metrics-%{YYYY.ww}
        number_of_replicas: 0
```

`otel-collector-config`:
```yaml
receivers:

  # Data sources: traces, metrics, logs
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Data sources: metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: "service"
          scrape_interval: 5s
          static_configs:
            - targets:
              - host.docker.internal:30000

processors:
  batch:
    send_batch_size: 10000
    send_batch_max_size: 11000
    timeout: 10s


exporters:
  logging:
    logLevel: DEBUG
      #verbosity: detailed
  otlp:
    endpoint: 127.0.0.1:4317
    tls:
      insecure: true

  otlp/data-prepper-traces:
    endpoint: data-prepper:21890
    tls:
      insecure: true
      insecure_skip_verify: true

  otlp/data-prepper-metrics:
    endpoint: data-prepper:21891
    tls:
      insecure: true
      insecure_skip_verify: true

  otlp/data-prepper-logs:
    endpoint: data-prepper:21892
    tls:
      insecure: true
      insecure_skip_verify: true


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/data-prepper-traces]
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [otlp/data-prepper-metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/data-prepper-logs]
```

**Expected behavior**
No significant impact on CPU load between both versions.

**Screenshots**
![CallTree_DP2 1 0](https://user-images.githubusercontent.com/2487742/216798394-09d9fc91-3e4a-4899-bb8f-b99bb26cbd03.png)
![HotSpots_DP2 1 0](https://user-images.githubusercontent.com/2487742/216798411-5599948c-4e93-4024-b11e-de7797d13757.png)
![CPULoad_DP2 1 0](https://user-images.githubusercontent.com/2487742/216798431-d7503c72-9d96-4954-bb83-84638bd27fea.png)
![Overview_DP2 1 0](https://user-images.githubusercontent.com/2487742/216798457-5e13f6b4-e4ad-4520-a9e5-9b096ab639b8.png)
![htop_DP2 1 0](https://user-images.githubusercontent.com/2487742/216798472-3e6808d6-1cb0-451c-85fb-1108dc4d9139.png)
![SystemResources_DP2 1 0](https://user-images.githubusercontent.com/2487742/216798478-1d2a9e0e-b7aa-4db7-87d1-1dc69580e80c.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS (host) - Docker 20.10.12-0ubuntu4

 - Version: 2.1.0-SNAPSHOT (Git checkout from main branch )
