### ISSUE TITLE
GeoIP plugin

### ISSUE THREAD

**Issue by ashoktelukuntla** [opensearch-project/data-prepper#2247]
**Is your feature request related to a problem? Please describe.**

Pipeline users want to add geographical location details based on IP address to enrich data for analytical purposes.    

**Describe the solution you'd like**

Create GeoIP plugin which will enrich traces with a geo location field, derived from the IP address. This will give customers a more insightful value that will allow them to visualize where traces are coming originating from. 

Plugin should be able to use Geo data from MaxMind database / Amazon location Service / User provided path of Geodata.

```
source:
    - geoip:
        source_key: "peer/ip"
        target_key: "location_info"
        database_path: "path/to/database.mmdb
        geoip_attributes: ["location", "city_name", "country_name"]

```
GeoIP attributes should have many optional attributes like ip, city_name, country_name, continent_code, country_iso_code, postal_code, region_name, region_code, timezone, location, latitude, longitude . Default should be all values included. Location attribute refers to latitude and longitude. 

Design Considerations:  Any Geo data - consumer needs to keep updating the latest data in the plugin periodically 

**Additional context**

Resources : 

- MaxMind data: https://dev.maxmind.com/geoip/geolite2-free-geolocation-data?lang=en
- Amazon Location Services: https://aws.amazon.com/location/, https://docs.aws.amazon.com/location/latest/developerguide/search-place-index-geocoding.html
- Java Implementation : https://maxmind.github.io/GeoIP2-java/
