### ISSUE TITLE
Change the path for HTTP source

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#2258]
**Is your feature request related to a problem? Please describe.**

The `http` source always uses the path `log/ingest`.

**Describe the solution you'd like**

Provide a configure to allow a pipeline author to change this path.

```
source:
  http:
    path: my/unique/path
    ssl: true
    ssl_certificate_file: "/full/path/to/certfile.crt"
    ssl_key_file: "/full/path/to/keyfile.key"
```

With that configuration, the HTTP source will be available at:

```
https://localhost:2021/my/unique/path
```

**Describe alternatives you've considered (Optional)**

This could use prefix, but I don't see a reason to require the `log/ingest`. Unlike OTel, this is not a convention.

**Additional context**

This is somewhat similar to #2257, but this is for the `http` source only. It is quite different from the OTel sources.
