### ISSUE TITLE
Collate plugin/processor

### ISSUE THREAD

**Issue by ashoktelukuntla** [opensearch-project/data-prepper#2307]
**Is your feature request related to a problem? Please describe.**

Pipeline users need to know query performance between two clusters 

**Describe the solution you'd like**

Create a processor which would receive streaming logs containing details of live query which is happening on source cluster and pipeline will execute the same query on destination cluster.

While pipeline is running on other destination cluster , I would envision  processor should be able to run user defined comparisons , generate latency , compare metrics or logs.

```
source:
    - performace:
        source_cluster_node_id: "81c694at-4561205"
        destination_cluster_node_id: "50855at-856-896545"
        query: ""

```

**Additional context**
