### ISSUE TITLE
No clear indication of single node vs. multi node data prepper cluster

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#2413]
**Is your feature request related to a problem? Please describe.**
Data Prepper can either be run as a single instance, or as two or more instances that essentially make up a cluster of data prepper instances. 

When configuring the `data-prepper-config.yaml` there are certain settings that only apply in a multi-node scenario. For example, the peer forwarder (https://github.com/opensearch-project/data-prepper/blob/main/docs/peer_forwarder.md) is only relevant in a multi-node scenario. The peer forwarder is configured with `service_discovery` settings to allow peers to communicate and forward Events. However, the configuration for service discovery is too coupled to peer forwarding, since service_discovery can be applied to other situations when data prepper nodes need to be aware of other data prepper nodes.

**Describe the solution you'd like**
I am proposing we break the service discovery configuration out from under the peer_forwarder (of course, we can do this while not making breaking changes and just deprecating the old peer forwarder service discovery config. It would be going from this

```
peer_forwarder:
    discovery_mode: static
    static_endpoints: ["dataprepper1", "dataprepper2"]
    ... other peer forwarder configurations ... 
```

to configuring service_discovery at the highest level, like this

```
some_other_feature_that_uses_service_discovery:
peer_forwarder:
   ... other peer forwarder configurations ...
service_discovery:
    discovery_mode: static
    static_endpoints: ["dataprepper1", "dataprepper2"]
```

Additionally, an additional configuration could be added to `service_discovery`, which will be useful for all plugins or features of data prepper that might behave differently if they are in a multi-node vs single-node setting (for example, source coordination with a single node does not require a distributed store #2412).

This configuration would be a  `discovery_mode` of type `single_instance` (or `single_node`), which is a way to explicitly say that this will always be just a single instance of data prepper not as a part of a cluster. There are cases to make for this to be the default `discovery_mode` if no `service_discovery` is found in the `data-prepper-config.yaml`. If `single_node` is not the default, then it is always assumed to be a multi-node scenario, which will not properly work for stateful aggregations without a peer forwarder and service discovery configuration. Defaulting to `single_node` seems like the safer option, since that is technically how data prepper works today (no peer forwarder configuration will essentially act as single node). The only other alternative is to make it required, but this is a breaking change. The final configuration would look like this, and would illustrate to anyone that could use the information that this is only a single instance of data prepper working on its own.

```
service_discovery:
     discovery_mode: single_node
```

**Describe alternatives you've considered (Optional)**

**Additional context**
