### ISSUE TITLE
[BUG] Use Json Pointer syntax on copy_values processor  "from_key"

### ISSUE THREAD

**Issue by dngferreira** [opensearch-project/data-prepper#2416]
**Describe the bug**
Trying to copy the value from a key with a "/" on the name

**To Reproduce**
Use the following processor with docker image 2.1.1:
```
processor:
  - copy_values:
      entries:
      - from_key: "/kubernetes/labels/app/kubernetes/io~1name"
        to_key: "app_name"
        overwrite_if_to_key_exists: true
```

**Expected behavior**
I would expect the "~1" to be replaced with "/" as described on the expression documentations

**Screenshots**
`java.lang.IllegalArgumentException: key /kubernetes/labels/app/kubernetes/io~1name must contain only alphanumeric chars with .-_ and must follow JsonPointer (ie. 'field/to/key')`

**Comment by chenqi0805** [comment]
@dngferreira Thanks for your interest in diving into data-prepper! Right now data-prepper expressions are only supported in `drop_when` attribute of `drop_events` processor. The mutate processor has not been integrated with data-prepper expression yet. We should probably indicate the scope of expression explicitly in our documentation.

**Comment by efloresb-tibco** [comment]
Hi @chenqi0805 ,  

I am facing the same issue with `routes`.  Are those also not supporting data-prepper expressions for now??
```
  processor:
    - date:
        from_time_received: true
        destination: "@timestamp"
  route:
    - empty_plane: '"/kubernetes/labels/platform.company~1plane-id" != null'
```
`plane-id must contain only alphanumeric chars with .-_ and must follow JsonPointer (ie. 'field/to/key')`
