### ISSUE TITLE
[BUG] Opensearch dashboards not displaying the traces at the observability traces window when the raw-pipeline is configured with  index_type: custom

### ISSUE THREAD

**Issue by talkraghu** [opensearch-project/data-prepper#2443]
**Describe the bug**
Opensearch dashboards not displaying the traces at the observability traces window when the raw-pipeline is configured with  index_type: custom

Versions of software's in use are
Dataprepper: 2.1
OpenSearch and OpenSearch-Dashboards: 2.6

Below is the configured pipelines.yml

```

entry-pipeline:
  workers: 12
  source:
    otel_trace_source:
      ssl: true
      sslKeyCertChainFile: "/opt/nsp/os/ssl/certs/nsp/nsp_internal.pem"
      sslKeyFile: "/opt/nsp/os/ssl/nsp_internal.key"
  buffer:
    bounded_blocking:
      buffer_size: 6000
      batch_size: 125
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"

raw-pipeline:
  workers: 12
  source:
    pipeline:
      name: "entry-pipeline"
  buffer:
    bounded_blocking:
      buffer_size: 6000
      batch_size: 125
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: [ "https://{{ .Values.opensearch.service.name }}:{{ .Values.opensearch.service.port }}" ]
        cert: "/opt/nsp/os/ssl/internal_ca_cert.pem"
        username: "admin"
        password: "admin"
        index: otel-v1-apm-span-%{yyyy.MM.dd}
        index_type: custom

service-map-pipeline:
  workers: 12
  source:
    pipeline:
      name: "entry-pipeline"
  buffer:
    bounded_blocking:
      buffer_size: 6000
      batch_size: 125
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: [ "https://{{ .Values.opensearch.service.name }}:{{ .Values.opensearch.service.port }}" ]
        cert: "/opt/nsp/os/ssl/internal_ca_cert.pem"
        username: "admin"
        password: "admin"
        index_type: trace-analytics-service-map
```

When we try to view/refresh/pull the traces from OpenSearch-Dashboards, I see the below errors. 

```
StatusCodeError: [illegal_argument_exception] Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [serviceName] in order to load field data by uninverting the inverted index. Note that this can use significant memory.
    at respond (/usr/share/opensearch-dashboards/node_modules/elasticsearch/src/lib/transport.js:349:15)
    at checkRespForFailure (/usr/share/opensearch-dashboards/node_modules/elasticsearch/src/lib/transport.js:306:7)
    at HttpConnector.<anonymous> (/usr/share/opensearch-dashboards/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)
    at IncomingMessage.wrapper (/usr/share/opensearch-dashboards/node_modules/lodash/lodash.js:4991:19)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  status: 400,
  displayName: 'BadRequest',
  path: '/otel-v1-apm-service-map*/_search',
  query: { size: 0 },
  body: {
    error: {
      root_cause: [Array],
      type: 'search_phase_execution_exception',
      reason: 'all shards failed',
      phase: 'query',
      grouped: true,
      failed_shards: [Array],
      caused_by: [Object]
    },
    status: 400
  },
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [name] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"otel-v1-apm-span-2023.04.03","node":"2bptfcmUTZS-fnTg1vp9jg","reason":{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [name] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}}],"caused_by":{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [name] in order to load field data by uninverting the inverted index. Note that this can use significant memory.","caused_by":{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [name] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}}},"status":400}',
  toString: [Function (anonymous)],
  toJSON: [Function (anonymous)]
}
{"type":"response","@timestamp":"2023-04-03T17:53:53Z","tags":[],"pid":1,"method":"post","statusCode":200,"req":{"url":"/api/observability/stats","method":"post","headers":{"host":"135.249.148.155","x-request-id":"617b5ef19130c595c6092c005310f8c9","x-real-ip":"10.143.82.108","x-forwarded-for":"10.143.82.108","x-forwarded-host":"135.249.148.155","x-forwarded-port":"443","x-forwarded-proto":"https","x-forwarded-scheme":"https","x-scheme":"https","content-length":"44","sec-ch-ua":"\"Google Chrome\";v=\"111\", \"Not(A:Brand\";v=\"8\", \"Chromium\";v=\"111\"","content-type":"application/json","dnt":"1","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36","osd-version":"2.6.0","sec-ch-ua-platform":"\"Windows\"","accept":"*/*","origin":"https://135.249.148.155","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://135.249.148.155/logviewer/app/observability-dashboards","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9"},"remoteAddress":"10.233.121.35","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36","referer":"https://135.249.148.155/logviewer/app/observability-dashboards"},"res":{"statusCode":200,"responseTime":24,"contentLength":9},"message":"POST /api/observability/stats 200 24ms - 9.0B"}
{"type":"response","@timestamp":"2023-04-03T17:53:53Z","tags":[],"pid":1,"method":"post","statusCode":400,"req":{"url":"/api/observability/trace_analytics/query","method":"post","headers":{"host":"135.249.148.155","x-request-id":"7df90927d894aef041d43ce2593c39c1","x-real-ip":"10.143.82.108","x-forwarded-for":"10.143.82.108","x-forwarded-host":"135.249.148.155","x-forwarded-port":"443","x-forwarded-proto":"https","x-forwarded-scheme":"https","x-scheme":"https","content-length":"640","sec-ch-ua":"\"Google Chrome\";v=\"111\", \"Not(A:Brand\";v=\"8\", \"Chromium\";v=\"111\"","content-type":"application/json","dnt":"1","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36","osd-version":"2.6.0","sec-ch-ua-platform":"\"Windows\"","accept":"*/*","origin":"https://135.249.148.155","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://135.249.148.155/logviewer/app/observability-dashboards","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9"},"remoteAddress":"10.233.121.35","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36","referer":"https://135.249.148.155/logviewer/app/observability-dashboards"},"res":{"statusCode":400,"responseTime":29,"contentLength":9},"message":"POST /api/observability/trace_analytics/query 400 29ms - 9.0B"}

```

Can you pls guide me on additional configs that could be needed at dataprepper OR opensearch/opensearch-dashboards to have the traces displayed at observability traces window?
