### ISSUE TITLE
Data-Prepper not using pipelines.yaml

### ISSUE THREAD

**Issue by rajavajra** [opensearch-project/data-prepper#2461]
**Describe the bug**
I receive the below error
```
2023-04-07T14:45:33,589 [main] INFO  org.opensearch.dataprepper.DataPrepperArgumentConfiguration - Command line args: /usr/share/data-prepper/pipelines,/usr/share/data-prepper/config/data-prepper-config.yaml                                                                                      
2023-04-07T14:45:35,496 [main] ERROR org.opensearch.dataprepper.parser.PipelineParser - Pipelines configuration file not found at /usr/share/data-prepper/pipelines
```
the docker-compse file I am using
```
  data-prepper:
    container_name: data-prepper
    image: docker.io/opensearchproject/data-prepper:latest
    volumes:
      - ./log-pipeline.yaml:/usr/share/data-prepper/pipelines.yaml:rw
      - ./data-prepper-config.yaml:/usr/share/data-prepper/data-prepper-config.yaml:rw
    environment:
      ENV_PIPELINE_FILEPATH: '["/usr/share/data-prepper-config/pipelines.yaml"]'
      ENV_CONFIG_FILEPATH: '["/usr/share/data-prepper-config/data-prepper-config.yaml"]'
    ports:
      - 4900:4900
    networks:
      - opensearch-net
```
**Note**: I added the environment section at the very end of my attempts, I get the same alert without it.

the Pipelines file I am using

```
simple-sample-pipeline:
  workers: 2
  delay: "5000"
  source:
    random:
  sink:
    - stdout:
```

if I try to change the ```pipelines.yaml``` file to just ```pipelines``` I receive a se linux error

```
Error response from daemon: runc: runc create failed: unable to start container process: error during container init: error mounting "/home/admin/docker/log-pipeline.yaml" to rootfs at "/usr/share/data-prepper/pipelines": mount /home/admin/docker/log-pipeline.yaml:/usr/share/data-prepper/pipelines (via /proc/self/fd/6), flags: 0x5006, data: context="system_u:object_r:container_file_t:s0:c560,c842": not a directory: OCI runtime error
```

**Expected behavior**
A docker container using data-prepper should be running

.

**Environment (please complete the following information):**
 - OS: RHEL 8.7
