### ISSUE TITLE
[BUG] S3 source csv codec parsing

### ISSUE THREAD

**Issue by asifsmohammed** [opensearch-project/data-prepper#2471]
**Describe the bug**
S3 source with csv codec is not paring the csv file accurately. It appends an additional space before the first key.

**To Reproduce**
1. create pipeline with S3 source and csv codec
2. ingest some csv data

Pipeline config:
```
log-pipeline:
  source:
    s3:
      notification_type: "sqs"
      compression: none
      codec:
        csv:
      sqs:
        queue_url: "https://sqs.us-east-1.amazonaws.com/<account-id>/<queue-name>"
      aws:
        region: "us-east-1"
        sts_role_arn: "arn:aws:iam::<account-id>:role/<role>"
      on_error: "retain_messages"

  processor:
    - date:
        from_time_received: true
        destination: "@timestamp"
   - delete_entries:
       with_keys: ["col1"]

  sink:
    - stdout:
```
Input:
```
col1,col2
a,101
b,102
```
Output:
```
{"﻿col1":"a","col2":"101","s3":{"bucket":"bucket-name","key":"Book1.csv"},"@timestamp":"2023-04-10T14:48:53.411-05:00"}
{"﻿col1":"b","col2":"102","s3":{"bucket":"bucket-name","key":"Book1.csv"},"@timestamp":"2023-04-10T14:48:53.580-05:00"}
```

**Expected behavior**
- There shouldn't be a space before `col1` in above output and `delete_entries` should delete the key.
