### ISSUE TITLE
Make conditional routing yaml configurations user friendly

### ISSUE THREAD

**Issue by asifsmohammed** [opensearch-project/data-prepper#2520]
**Is your feature request related to a problem? Please describe.**
Currently, users configure `route` component and `routes` in sink in the pipeline YAML. This might not look very clear for users on what actually is happening with routes since both `route` and `routes` are list and can be plural.  For example,
```
  route:
  - my-route: "/a==b"
  sink:
  - testSink:
      routes:
      - "my-route"
```

**Describe the solution you'd like**
One proposal is to have a clear and easy configuration for readability and understandability.
```
  routes:
  - my-route: "/a==b"
  sink:
  - testSink:
      routes:
      - "my-route"
```
Second proposal to to have match inside sink. This is not required and might not add much value as there are no other options inside `routes`. If needed we can rename the `matches` in sink.
```
  routes:
  - my-route: "/a==b"
  sink:
  - testSink:
      routes:
        match:
          - "my-route"
```

**Additional context**
We originally changes to `routes` to `route` from PR feedback and we are planning to go back to `routes`.

Please feel free to comment any other suggestions you might have.
