### ISSUE TITLE
[BUG] Invalid key prefix format for dlq

### ISSUE THREAD

**Issue by daixba** [opensearch-project/data-prepper#2581]
**Describe the bug**

I have added the dlq to OpenSearch sink. And when I used "error/" as the key_path_prefix, the full output file of dlq is 'error//dlq-v2-test-pipeline-opensearch-2023-...' which contains an extra unexpected `/` in between.  

Note that / still is a valid key in Amazon S3.

**To Reproduce**
1.  Add below dlq config to opensearch sink

```
  sink:
    - opensearch:
        dlq:
          s3:
            bucket: "xxx"
            key_path_prefix: "error/"
            region: "us-west-2"
```

2. Run the pipeline and try get some errors

3. Check the dlq bucket for error files.

**Expected behavior**
The current output key is `error//dlq-v2-...`, expected output key is `error/dlq-v2-...`

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: MacOS (local)
 - Version: 2.2

**Additional context**
N/A
