### ISSUE TITLE
Shared OpenSearch configurations

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#2590]
## Problem

Data Prepper pipeline configurations require configuring OpenSearch sinks in multiple locations.

For example, in the standard trace analytics pipeline, I may have the following configured twice

```
  sink:
    - opensearch:
        hosts: ["https://localhost:9200"]
        username: admin
        password: admin
        index_type: trace-analytics-raw
...
  sink:
    - opensearch:
        hosts: ["https://localhost:9200"]
        username: admin
        password: admin
        index_type: trace-analytics-service-map
```

## Proposal

I'd like to be able to optionally configure an OpenSearch connection once and re-use it.

```
pipeline_configurations:
  opensearch:
    connections:
      trace_cluster:
        hosts: ["https://localhost:9200"]
        username: admin
        password: admin
```

Then, I can re-use it with the following.

```
  sink:
    - opensearch:
        connection: trace_cluster
        index_type: trace-analytics-raw
...
  sink:
    - opensearch:
        connection: trace_cluster
        index_type: trace-analytics-service-map
```

## Related enhancements

This requires a common OpenSearch extension. It would be used along with #2589. Thus, this requires the plugin extensions capability described by #2588.
