### ISSUE TITLE
Support checking if an IP address is in a CIDR block

### ISSUE THREAD

**Issue by oeyh** [opensearch-project/data-prepper#2625]
**Is your feature request related to a problem? Please describe.**
There are use cases where the IP address associated with an event needs to be checked against some given CIDR blocks to determine the further processing actions for the event. 

**Describe the solution you'd like**
Support a `ip_in` operator in an Data Prepper expression like this:
```
/source_ip ip_in {"192.0.2.0/24.", "10.10.0.0/16"}
```
to check if an IP address from the event on the left side matches any of the network blocks on the right side.

With the conditional support proposed in #2613, we can then use this expression in many common processors to process events based on the result of the IP check.

**Describe alternatives you've considered (Optional)**
Support a `when` option in existing processors (e.g. add_entries processors) to perform CIDR check:
```
processor:
  - add_entries:
      entries:
        - key: "valid_source"
          value: true
      when:
        cidr:
          address_key: "source_ip"
          network: ["192.0.2.0/24.", "10.10.0.0/16"]
```
This will add an entry {"valid_source": true} to the event if source_ip is within the range of the network blocks.

**Additional context**
