### ISSUE TITLE
Support loading Grok patterns from S3

### ISSUE THREAD

**Issue by asifsmohammed** [opensearch-project/data-prepper#2646]
**Is your feature request related to a problem? Please describe.**
Currently, user can configure Grok Processor with `pattern_directories` to load pattern files only from local file system.
```
processor:
  - grok:
      patterns_directories: ["path/to/patterns_folder", "path/to/extra_patterns_folder"]
      match:
        message: ["%{CUSTOM_PATTERN_FROM_FILE:my_pattern}"`
```

**Describe the solution you'd like**
Allow users to load the pattern directories from S3. This would allow specifying S3 URI in `pattern_directories`.
This change would use [ListObjectsV2](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html) API and require `s3:ListBucket` permission.

**Additional context**
This is similar to loading index template and ISM policy from S3: https://github.com/opensearch-project/data-prepper/issues/2120
