### ISSUE TITLE
Add support for expressions in add_entries processor

### ISSUE THREAD

**Issue by kkondaka** [opensearch-project/data-prepper#2672]
**Is your feature request related to a problem? Please describe.**
Add Entries processor should support adding entries based on expressions, especially expressions with functions

For example,
```
    processor:
        - add_entries:                                                                                                                                       
           entries:                                                                                                                                         
            - key: "requestLength" 
            - value: "length(/request)"
```

or
```
   processor:
        - add_entries:                                                                                                                                       
           entries:                                                                                                                                         
            - key: "newKey" 
            - value: "getMetadata('newKey')"
```
or 
```
    processor:
        - add_entries:                                                                                                                                       
           entries:                                                                                                                                         
            - key: "newLength" 
            - value: "length(/request) + getMetadata('padding_length')"
```

**Describe the solution you'd like**
Need to support dataprepper expressions as values. They may be supported under existing `value:` config option  or add new config option like `value_expression:` which takes an expression, evaluates it and stores the result as value for the given key

```
 processor:
        - add_entries:                                                                                                                                       
           entries:                                                                                                                                         
            - key: "newLength" 
            - value_expression: "length(/request) + getMetadata('padding_length')"
```

**Describe alternatives you've considered (Optional)**
Alternative way is to have a special character as the first character in the value to indicate that what's following is an expression. For example
```
 processor:
        - add_entries:                                                                                                                                       
           entries:                                                                                                                                         
            - key: "newLength" 
            - value: "@(length(/request) + getMetadata('padding_length'))"
```
**Additional context**
