### ISSUE TITLE
SQS Source / Input plugin

### ISSUE THREAD

**Issue by ashoktelukuntla** [opensearch-project/data-prepper#2679]
**Is your feature request related to a problem? Please describe.**

Pipeline users want to read data from SQS Queue

**Describe the solution you'd like**

Create SQS Source plugin which will read all events from SQS queue URL’s with provided batch size. This plugin should be able to accept AWS Key’s and work with AWS Authentication Sigv4. Plugin should have 

- Back off mechanism which should kick in say when number of messages per batch request reaches batch size mentioned in the configuration. 
- Capability to spin of threads which are configurable.  
- Require sqs:DeleteMessageBatch, sqs:DeleteMessage and sqs:ReceiveMessage IAM privileges to be associated with the Instance profile or AWS Access KeyId
- Implement multi node support 
- End-end acknowledgments. 

```
log-pipeline:
  source:
    sqs:
        queues: 
           - urls: ['https://sqs.us-east-1.amazonaws.com/myQueue/dev', 'https://sqs.us-east-1.amazonaws.com/myQueue2/dev']
             polling_frequency: 5m
             batch_size: 10
             number_of_threads: 2
           - urls: ['https://sqs.us-east-1.amazonaws.com/myQueue/dev2']
             polling_frequency: 1m
             batch_size: 10
             number_of_threads: 3

      aws:
        access_key_id:
        role_arn:
        region:
        secret_access_key:
        session_token:
```

**Additional context**

https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/examples-sqs.html
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html
https://github.com/plumbee/flume-sqs-source

**Comment by tashish4u** [comment]
Please find below the updated YAML after discussion with Ashok:

```
log-pipeline:
  source:
    sqs:
        queues: 
           urls: 
              - 'https://sqs.us-east-1.amazonaws.com/myQueue/dev'
              - 'https://sqs.us-east-1.amazonaws.com/myQueue2/dev'
             polling_frequency: 5m
             batch_size: 10
             number_of_threads: 2
      aws:
        access_key_id:
        role_arn:
        region:
        secret_access_key:
        session_token: 
```

**Comment by dlvenable** [comment]
@tashish4u , Thanks! Just so you know, these two are equivalent (and interchangeable in YAML):

```
urls: ['https://sqs.us-east-1.amazonaws.com/myQueue/dev', 'https://sqs.us-east-1.amazonaws.com/myQueue2/dev']
```

and

```
urls: 
  - 'https://sqs.us-east-1.amazonaws.com/myQueue/dev'
  - 'https://sqs.us-east-1.amazonaws.com/myQueue2/dev'
```

**Comment by dlvenable** [comment]
@ashoktelukuntla , @tashish4u ,

Currently Data Prepper is not accepting `access_key_id` and `secret_access_key` parameters. There is currently no concept of secrets. And users can use their default credentials instead.

Also, there should be no need to include a `session_token`.

Thus, the possible fields for `aws:` should be:

* `role_arn`
* `region`

Finally, this should use the work being added for #2570 for AWS credentials.

**Comment by dlvenable** [comment]
@ashoktelukuntla , @tashish4u 

Almost all of this work is already complete in the `s3` source. We need to generate the [`SqsService`](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/SqsService.java) such that:

* It is decoupled from S3 event notifications.
* It can support both goals.

**Comment by tashish4u** [comment]
Thanks David for your confirmation, That means Final Yaml should be like below:

```
log-pipeline:
  source:
    sqs:
        queues: 
           urls: 
              - 'https://sqs.us-east-1.amazonaws.com/myQueue/dev'
              - 'https://sqs.us-east-1.amazonaws.com/myQueue2/dev'
             polling_frequency: 5m
             batch_size: 10
             number_of_threads: 2
      aws:
        role_arn:
        region:
```
