### ISSUE TITLE
Add support for adding metadata entries as part of add_entries processor

### ISSUE THREAD

**Issue by kkondaka** [opensearch-project/data-prepper#2687]
**Is your feature request related to a problem? Please describe.**
Currently `add_entries` processor adds new fields to an `Event`. We need the ability to add entries to event's metadata.

**Describe the solution you'd like**
Suggest the following change to `add_entries` processor

```
processor
   - add_entries:                                                                                                                                      
         entries:                                                                                                                                        
         - metadata_key: "message_len"                                                                                                                                    
            value: 10
```

or

```
processor
   - add_entries:                                                                                                                                      
         entries:                                                                                                                                        
         - metadata_key: "message_len"                                                                                                                                    
            value_expression: `length(/message)`
```

**Describe alternatives you've considered (Optional)**

**Additional context**
