### ISSUE TITLE
S3 Scan Requires start and end time

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#2735]
**Is your feature request related to a problem? Please describe.**
S3 Scan configuration requires both start and end time to be able to use the scan feature

```
s3:
      codec:
        newline:
      aws:
        region: "us-west-2"
        sts_role_arn: "arn:aws:iam::123456789012:role/s3-role"
      scan:
        start_time: 2023-01-21T18:00:00
        end_time: 2023-08-21T18:00:00
        buckets:
          - bucket: 
              name: "my-bucket"
```

**Describe the solution you'd like**
By default s3 scan should scan the entire bucket, and not require `start_time` or `end_time`

**Describe alternatives you've considered (Optional)**

**Additional context**
