### ISSUE TITLE
S3 Scan Configuration Improvement

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#2737]
**Is your feature request related to a problem? Please describe.**
S3 Scan has `start_time`, `end_time`, and `range` at the global level for s3 scan, and not for each individual bucket

**Describe the solution you'd like**
change the current configuration of this

```
s3:
      codec:
        newline:
      aws:
        region: "us-west-2"
        sts_role_arn: "arn:aws:iam::123456789012:role/s3-role"
      scan:
        start_time: 2023-01-21T18:00:00
        end_time: 2023-08-21T18:00:00
        buckets:
          - bucket: 
              name: "my-bucket"
          - bucket:
               name: "other-bucket"
```

to 

```
s3:
      codec:
        newline:
      aws:
        region: "us-west-2"
        sts_role_arn: "arn:aws:iam::123456789012:role/s3-role"
      scan:
        buckets:
          - bucket: 
              name: "my-bucket"
              start_time: 2023-01-21T18:00:00
              end_time: 2023-08-21T18:00:00
          - bucket:
               name: "other-bucket"
               start_time: 2023-02-21T18:00:00
               end_time: 2023-09-21T18:00:00
```

**Describe alternatives you've considered (Optional)**

**Additional context**
