### ISSUE TITLE
[BUG] Nested configuration annotations are not getting triggered 

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#2743]
**Describe the bug**
Any nested configurations in a pipeline configuration will not run the validations of the nested class without the `@Valid` annotation.

For example,  the `aws` parameter gets validated in the s3 source because it has the `@Valid` annotation (https://github.com/opensearch-project/data-prepper/blob/d0d7ba01d179b60d153ff54865c7924a133a7358/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3SourceConfig.java#L42)

While the sqs options do not get validated (https://github.com/opensearch-project/data-prepper/blob/d0d7ba01d179b60d153ff54865c7924a133a7358/data-prepper-plugins/s3-source/src/main/java/org/opensearch/dataprepper/plugins/source/S3SourceConfig.java#L38)

**To Reproduce**
Run a pipeline configuration like the following and you will get a NPE at runtime and not get an exception for this validation until you add the `@Valid` annotation

```
s3-scan-pipeline:
  source:
    s3:
      sqs:
        queue_url: null
      codec:
        newline:
      aws:
        region: "us-west-2"
        sts_role_arn: "arn:aws:iam::870201406020:role/s3-to-osis-role"
  sink:
    - stdout:
```

**Expected behavior**
These should all be validated

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**
