### ISSUE TITLE
Add support to tag events when parse_json fails to parse

### ISSUE THREAD

**Issue by kkondaka** [opensearch-project/data-prepper#2744]
**Is your feature request related to a problem? Please describe.**
Add support to tag events when parse_json fails to parse. This is sub-issue of issue #629.

**Describe the solution you'd like**
Solution is to add option to parse_json processor that can add tags on failure. The proposed config is 
```
processor:                                                                                                                                              
     - parse_json:                                                                                                                                        
          source: "log"                                                                                                                                     
          tags_on_failure: ["json_parse_fail", "tag2"]    
```
This config would add the specified tags to the event upon parse failure.

**Describe alternatives you've considered (Optional)**

**Additional context**
The added tags may be used to in the pipeline to do conditional routing or conditional processing.
