### ISSUE TITLE
[DOCS] How to Increase "index.mapping.total_fields.limit" for new indices

### ISSUE THREAD

**Issue by iquirino** [opensearch-project/data-prepper#2779]
Hey guys, I hope you're well!

**Describe the bug**
I need to have more than 1000 fields on my otel indices, this is a must have to my solution.
I've tried to add it to the data-prepper template_file but it's no working as expected.

I want to have the following command automatically applied to each index created by dataprepper:

```
PUT otel-v1-apm-span-*/_settings
{
  "index.mapping.total_fields.limit": 2500
}
```

*References:*

 - https://opensearch.org/docs/2.7/data-prepper/pipelines/configuration/sinks/opensearch/
 - https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/opensearch/src/main/resources/otel-v1-apm-span-index-template.json 
 - https://stackoverflow.com/questions/55372330/what-does-limit-of-total-fields-1000-in-index-has-been-exceeded-means-in

**To Reproduce**

*pipelines.yaml*
```
sink:
  - opensearch:
      hosts: [ "https://node-0.example.com:9200" ]
      #index_type: trace-analytics-raw
      index_type: custom
      template_file: "/usr/share/data-prepper/templates/index-template.json"
      cert: "/usr/share/data-prepper/root-ca.pem"
      username: "admin"
      password: "admin"
      socket_timeout: 0
      connect_timeout: 0
```

*index-template.json*
```
{
    "version": 1,
    "settings": {
      "index": { "mapping": { "total_fields": { "limit": "2500" } } }
    },
    "mappings": {
        // ...
    }
}
```

*GET otel-v1-apm-span-***/_settings*
```
{
  "otel-v1-apm-span-": {
    "settings": {
      "index": {
        "number_of_shards": "1",
        "provided_name": "otel-v1-apm-span-",
        "creation_date": "1685351383685",
        "number_of_replicas": "1",
        "uuid": "P_ss8jsCRj2kreesYZWPbw",
        "version": {
          "created": "136277827"
        }
      }
    }
  }
}
```

I am required to run the following command for each index created to have my index settings as desired:
```
PUT otel-v1-apm-span-*/_settings
{
  "index.mapping.total_fields.limit": 2500
}
```
Result:
```
{
  "otel-v1-apm-span-": {
    "settings": {
      "index": {
        "mapping": {
          "total_fields": {
            "limit": "2500"
          }
        },
        "number_of_shards": "1",
        "provided_name": "otel-v1-apm-span-",
        "creation_date": "1685351383685",
        "number_of_replicas": "1",
        "uuid": "P_ss8jsCRj2kreesYZWPbw",
        "version": {
          "created": "136277827"
        }
      }
    }
  }
}
```

**Expected behavior**
Data prepper should follow my index settings on template_file or have any other way to configure it's index settings.

**Screenshots**
My setting is not going to be used by data-prepper to create the index:
![image](https://github.com/opensearch-project/data-prepper/assets/881117/1271615f-6bd3-4c5a-a388-93778e2a04b2)

When i've applied it manually
![image](https://github.com/opensearch-project/data-prepper/assets/881117/1acc6d81-9ea5-428d-b786-5beb4d7e36ad)

**Environment (please complete the following information):**
 - OS: Manjaro Latest and Ubuntu Latest

**Additional context**
No
