### ISSUE TITLE
Support AWS secrets in configuring Data Prepper pipelines

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/data-prepper#2780]
**Is your feature request related to a problem? Please describe.**
In the current state, user credential variables such as username and password are hardcoded in pipelines.yaml. For better security, we could support AWS secret as an extension plugin, i.e.

data-prepper-config.yaml
```
aws:
  credentials:
    default:
       sts_role_arn: arn:aws:iam::99123456789:role/OsiDataPlaneRole
       region: us-east-1
     my-custom-role:
       sts_role_arn:
       region:
  secret: # secret extension
    my_es_secret_configuration:
      name: ...
      authentication: my-custom-role
```
Then our pipeline configuration can reference the key-value pairs stored in an AWS secret.
pipelines.yaml
```
...
sink:
  - opensearch:
      ...
      username: ${{ aws_secret:my_es_secret_configuration:USERNAME }}
      password: ${{ aws_secret:my_es_secret_configuration:PASSWORD }}
```

**Describe the solution you'd like**
We can reuse aws credential extensions when configuring the credentials for AWS secrets.

**Describe alternatives you've considered (Optional)**
Alternatively, we can make AWS secret extension independent of credentials plugin at the price of duplication in configuration:

```
aws:
  credentials:
    default:
      sts_role_arn: arn:aws:iam::99123456789:role/OsiDataPlaneRole
      region: us-east-1
    my-custom-role:
      sts_role_arn:
      region:

aws_secrets:
  secrets:
    my-secret1:
      sts_role_arn: arn:aws:iam::99123456789:role/OsiDataPlaneRole
      region: us-east-1
```

**Additional context**
