### ISSUE TITLE
Define null characters in convert processor

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#2822]
**Is your feature request related to a problem? Please describe.**

The `convert_entry_type` processor requires that the input match the expected type. In some pipelines, this may be provided through a special character that does not convert.

For example, in VPC Flow Logs, reading the CSV file using the `csv` codec may have some such as `srcport` (source port) come as `-` when there is no such value.

I have to delete this entry to provide conversion.

```
processor:
    - delete_entries:
        with_keys:
          - srcport
        delete_when: '/srcport == "-"'
    - convert_entry_type:
        key: srcport
        type: integer
```

**Describe the solution you'd like**

Provide a new configuration in the `convert_entry_type` processor which allows a list of strings which are explicitly defined to be `null` (that is removed).

```
processor:
    - convert_entry_type:
        key: srcport
        type: integer
        null_values: [ '-' ]
```

The `convert_entry_type` processor will know to treat any value in the `null_values` list as `null`.

**Describe alternatives you've considered (Optional)**

An alternative solution would be to update the CSV processor and codec to have a concept of `null` strings. But, these are not mutually exclusive solutions. Not all pipelines will go through CSV.
