### ISSUE TITLE
Define multiple keys for type conversion

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#2823]
**Is your feature request related to a problem? Please describe.**

The `convert_entry_type` may be used a few times with the same configuration. It might be nice to consolidate this into a single `keys` value.

For example, see this sample for VPC Flow Logs:

```
processor:
    - convert_entry_type:
        key: dstport
        type: integer
    - convert_entry_type:
        key: srcport
        type: integer
    - convert_entry_type:
        key: protocol
        type: integer
    - convert_entry_type:
        key: bytes
        type: integer
    - convert_entry_type:
        key: packets
        type: integer
```

**Describe the solution you'd like**

Allow defining multiple `keys` in the `convert_entry_type` processor.

Each of the `convert_entry_type` processors could be combined:

```
processor:
  - convert_entry_type:
       keys: [ 'dstport', 'srcport', 'protocol', 'bytes', 'packets' ]
       type: integer
```

**Additional context**

This also becomes much more helpful when combined with #2822. I have the following sample:

```
processor:
    - delete_entries:
        with_keys:
          - dstport
        delete_when: '/dstport == "-"'
    - convert_entry_type:
        key: dstport
        type: integer
    - delete_entries:
        with_keys:
          - srcport
        delete_when: '/srcport == "-"'
    - convert_entry_type:
        key: srcport
        type: integer
    - delete_entries:
        with_keys:
          - protocol
        delete_when: '/protocol == "-"'
    - convert_entry_type:
        key: protocol
        type: integer
    - delete_entries:
        with_keys:
          - bytes
        delete_when: '/bytes == "-"'
    - convert_entry_type:
        key: bytes
        type: integer
    - delete_entries:
        with_keys:
          - packets
        delete_when: '/packets == "-"'
    - convert_entry_type:
        key: packets
        type: integer
```

This could simply become:

```
processor:
  - convert_entry_type:
       keys: [ 'dstport', 'srcport', 'protocol', 'bytes', 'packets' ]
       type: integer
       null_values: [ '-' ]
```
