### ISSUE TITLE
Support for iterating over a list and manipulating each element, such as renaming a certain key in the element

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#2853]
**Is your feature request related to a problem? Please describe.**
As a user of Data Prepper who has logs containing a list of json objects, I would like to run mutate event processors on every value in the list

**Describe the solution you'd like**

Given a log with the following structure

```
root_key: [
    {
        "key_one": "value_one",
        "key_two": "value_two"
    },
     {
        "key_one": "value_three,
        "key_two": "value_four"
    }
]
```

I would like be able to manipulate the elements of this map in place by the mutate event processors iterating over the elements and running them, especially for add_entries and delete_entries.

For example, I would like the following output

```
root_key: [
    {
        "new_key": "value_one:value_two"
    },
     {
       "new_key": "value_three:value_four"
    }
]
```

If this is supported, the following configuration would work for the above case

```
- add_entries:
     entries:
       - iterate_on: "root_key" // This is my array
         key: "my_new_key"
         format: "${key_one}:${key_two}
- delete_entries:
      iterate_on: "root_key"
      with_keys: [ "key_one", "key_two" ]
```

The `iterate_on` parameter name was used for the `translate` processor, but I am fine with another naming as long as we are consistent for all mutate processors

**Describe alternatives you've considered (Optional)**

**Additional context**
Similar concept for mutate string processors #1217
