### ISSUE TITLE
Support Prometheus as a Sink (push-based model)

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#3028]
**Is your feature request related to a problem? Please describe.**

I'd like to push metrics to Prometheus.

**Describe the solution you'd like**

Provide a `prometheus` sink which can support push.

```
sink:
  - prometheus:
       model: push
       endpoint: http://localhost:2090
```

**Additional context**

This is complementary to #1744.
