### ISSUE TITLE
Support remaining bulk actions and conditional expressions to determine bulk action in the OpenSearch sink

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#3109]
**Is your feature request related to a problem? Please describe.**

The OpenSearch sink currently supports the `create` and `index` bulk actions. As a user, I would also like to utilize both the `delete` and `update` actions (as well as `upsert` action which uses the update bulk action) in the OpenSearch sink, but they are not supported at this time (https://opensearch.org/docs/latest/api-reference/document-apis/bulk/). Additionally, I would like to choose the bulk action to use (create, index, update, and delete) based on what each Event looks like through conditional expressions.

**Describe the solution you'd like**
A deprecation of the existing `action` parameter of the OpenSearch sink

```
action: "index"
```

and a rework to the following format with an `actions` parameter. The simple config above will look like this in the new parameter

```
actions:
  - type: "index"
```

and more complex cases may look like this, including conditional expressions

```
actions:
  - type: "create"
     when: "/some_key == CREATE"
  - type: "index"
     when: "/some_key == INDEX"
  - type: "upsert"
     when: "/some_key == UPSERT"
  - type: "update"
     when: "/some_key == UPDATE"
  - type: "delete"
     when: "/some_key == DELETE"
 # default case
  - type: "index"
```

This would be read like a switch statement, where the order of the list matters

```
if (/some_key == CREATE) {
   // use bulk create action
} else if (/some_key == INDEX) {
   // use bulk index action
} else if (/some_key == UPSERT) {
   // perform upsert (update action with doc_as_upsert set to true)
} else if (/some_key == UPDATE) {
   // use bulk update action
} else if (/some_key == DELETE) {
   // use bulk delete action
} else {
   // use bulk index action
}
```

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by daixba** [comment]
Do we need to support expression maybe, something like `action: "getMetadata(\"op\")"`?

**Comment by graytaylor0** [comment]
@daixba Simplifying to just supporting expression like this is a bit simpler, but I think the proposed solution is a bit more robust. You could do 

```
action: "getMetadata(\"op\")"
```

with 

```
actions:
  - type: "create"
     when: "getMetadata(\"op\") == CREATE"
  - type: "index"
     when: "getMetadata(\"op\") == INDEX"
  - type: "update"
     when: "getMetadata(\"op\") == UPDATE"
  - type: "delete"
     when: "getMetadata(\"op\") == DELETE"
 # default case
  - type: "index"
```

which is a little verbose but can apply to more than just the ddb source
