### ISSUE TITLE
Support compression on the S3 sink

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#3130]
**Is your feature request related to a problem? Please describe.**

Data Prepper's `s3` sink does not support any compression. Yet writing compressed files to S3 can reduce network and save on storage costs.

**Describe the solution you'd like**

Add a new `compression` option in the S3 sink similar to the S3 source. (However, it will not support `automatic` since this is not relevant.)

```
sink:
  - s3:
       compression: gzip
       bucket: my_bucket
```

New option: `compression`. Values:
* `gzip`
* `none` (default)
