### ISSUE TITLE
Support Snappy compression in the S3 sink

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#3154]
**Is your feature request related to a problem? Please describe.**

Writing compressed files in Snappy can help some analytics scenarios.

**Describe the solution you'd like**

Provide a new `snappy` compression option for the S3 sink.

```
sink:
  - s3:
       compression: snappy
       bucket: my_bucket
```

**Additional context**

Expands upon:  #3130
