### ISSUE TITLE
Proxy support for AWS SDKs

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#317]
**Is your feature request related to a problem? Please describe.**

Data Prepper running behind proxies is not currently supported.

**Describe the solution you'd like**

Follow the same approach as we are planning #300. Each AWS configuration can include a new proxy configuration.

For example, within peer-forwarder:
```
  prepper:
    - peer_forwarder:
        discovery_mode: aws_cloud_map
        proxy: http://my-proxy:9000

```

**Describe alternatives you've considered (Optional)**

We may wish to have a default AWS configuration available for users to configure. This could be used for any plugin which uses AWS. However, this would be a much larger change.
