### ISSUE TITLE
Support CDC from MySQL

### ISSUE THREAD

**Issue by wanghd89** [opensearch-project/data-prepper#3233]
**Is your feature request related to a problem? Please describe.**
I would like to use data-prepper to ingest CDC from MySQL database, including Aurora DB

**Describe the solution you'd like**
Support Kafka Connect with Debezium MySQL connector plugins

**Describe alternatives you've considered (Optional)**
N/A

**Additional context**

```
connect-pipeline:
  source:
    kafka_connect:
      worker_properties:
        group_id: group
        config_storage_topic: pipeline-configs
        offset_storage_topic: pipeline-offsets
        status_storage_topic: pipeline-status
      mysql:
        hostname: localhost
        credentials:
          type: plaintext
          username: username
          password: password
        tables:
          - topic_prefix: prefix1
            table_name: dbname.tableName1
          - topic_prefix: prefix2
            table_name: dbname.tableName2
```

**Comment by dlvenable** [comment]
@wanghd89,

Thanks for this proposal. I like the concept of using Debezium and Kafka Connect. This could work nicely with the Kafka buffer concept.

In Data Prepper, sources represent the source from which Data Prepper gets data. In the current proposal, this is a bit inverted. The source name `kafka_connect` is somewhat of an implementation detail, not a source.

I'd like to see sources based around the actual source rather than the way the source operates with Data Prepper.


```
connect-pipeline:
  source:
    mysql:
      hostname: localhost
      credentials:
        type: plaintext
        username: username
        password: password
      tables:
        - table_name: dbname.tableName1
        - table_name: dbname.tableName2
```

Data Prepper's new extensions concept can supply the necessary configurations for configuring Kafka Connect under the hood. In `data-prepper-config.yaml`:

```
extensions:
  kafka_connect:
    topic_prefix: myprefix1
```

See #2588 for the extensions proposal. And #2851 for the recent PR which adds support for configuring extensions in `data-prepper-config.yaml`.
