### ISSUE TITLE
Support CDC from Postgresql

### ISSUE THREAD

**Issue by wanghd89** [opensearch-project/data-prepper#3234]
**Is your feature request related to a problem? Please describe.**
I would like to use data-prepper to ingest CDC from Postgresql database, including Aurora DB

**Describe the solution you'd like**
Support Kafka Connect with Debezium Postgresql connector plugins

**Describe alternatives you've considered (Optional)**
N/A

**Additional context**

```
connect-pipeline:
  source:
    kafka_connect:
      worker_properties:
        group_id: group
        config_storage_topic: pipeline-configs
        offset_storage_topic: pipeline-offsets
        status_storage_topic: pipeline-status
      postgresql:
        hostname: localhost
        credentials:
          type: aws
          region: us-east-1
          secretId: secretId
        tables:
          - topic_prefix: prefix1
            database_name: dbname
            table_name: public.tableName1
```
