### ISSUE TITLE
support CDC from MongoDB 

### ISSUE THREAD

**Issue by wanghd89** [opensearch-project/data-prepper#3235]
Is your feature request related to a problem? Please describe.
I would like to use data-prepper to ingest CDC from MongoDB database, including AWS Document DB

Describe the solution you'd like
Support Kafka Connect with Debezium Postgresql connector plugins

Describe alternatives you've considered (Optional)
N/A

Additional context
```
connect-pipeline:
  source:
    kafka_connect:
      worker_properties:
        group_id: group
        config_storage_topic: pipeline-configs
        offset_storage_topic: pipeline-offsets
        status_storage_topic: pipeline-status
     mongodb:
          hostname: localhost
          credentials:
            type: plaintext
            username: username
            password: password
          collections:
            - topic_prefix: prefix1
              collection_name: dbname.collection1
            - topic_prefix: prefix2
              collection_name: dbname.collection2
```
