### ISSUE TITLE
[BUG] Unable to use copy_values processor with otel_metrics_source

### ISSUE THREAD

**Issue by anand3493** [opensearch-project/data-prepper#3240]
**Describe the bug**
The opentelemetry collector exports metrics data to data-prepper which uses source as otel_metrics_source to receive the data.
Here I would like to copy a value from existing field and place it to a new field. 
Hence I went with copy_values processor but the data-prepper pod errored out and failed. 

**To Reproduce**
```
otel-metrics-pipeline:
  workers: 1
  delay: 3000
  source:
    otel_metrics_source:
      health_check_service: true
      ssl: false
  buffer:
    bounded_blocking:
  processor:
    - copy_values:
        entries:
        - from_key: "Time"
          to_key: "@timestamp"
          overwrite_if_to_key_exists: true  
    - otel_metrics:
  sink:
    - opensearch:
```

**Expected behavior**
To add a new field name called "@timestamp" with the value from "time" in the output data. 

**Actual Behavior**
ExportMetricsServiceRequest cannot be cast to class event

**Environment (please complete the following information):**
 - Kubernetes

**Additional context**
Would like to introduce a custom field with value from existing field. If not via copy_values, kindly let me know other alternatives

**Comment by anand3493** [comment]
@dlvenable  Can you please help me with this request ? If there is any workaround I could use on introducing a new field for a otel metrics source

**Comment by anand3493** [comment]
Same goes with rename_keys processor as well. It's like we cannot perform any data massaging for the metrics data at the moment. 

Same error message: 
class io.opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceRequest cannot be cast to class org.opensearch.dataprepper.model.event.Event

**Comment by asifsmohammed** [comment]
Hi @anand3493, thanks for creating the issue. This should work if you configure the `copy_values` processor after `otel_metrics` processor. The issue here is all the processors work on `Event` model, so in case of OTel metrics pipeline, `Event` is created after `otel_metrics` processor. 

Please try to update the pipeline to following,
```
otel-metrics-pipeline:
  workers: 1
  delay: 3000
  source:
    otel_metrics_source:
      health_check_service: true
      ssl: false
  buffer:
    bounded_blocking:
  processor:
    - otel_metrics:
    - copy_values:
        entries:
        - from_key: "Time"
          to_key: "@timestamp"
          overwrite_if_to_key_exists: true  
  sink:
    - opensearch:
```

Let me know how it goes with the updated pipeline.
