### ISSUE TITLE
Acknowledgements support in Drop processor

### ISSUE THREAD

**Issue by hshardeesi** [opensearch-project/data-prepper#3279]
**Is your feature request related to a problem? Please describe.**
Acknowledgements are not received by sources (such as S3/Kafka) if a pipeline has drop processor to conditionally drop events and has "acknowledgements" enabled.

**Additional context**
This was tested with following pipeline config. Kafka source did not receive acknowledgements for dropped events and did not commit offsets for consumed records.

```
version: "2"
kafka-pipeline:
  source:
    kafka:
      acknowledgments: true
      topics:
        - name: "test-drop"
          group_id: "Mac-group"
          serde_format: "json"
          auto_offset_reset: "earliest"
      aws:
        msk:
          arn: "arn:aws:kafka:us-west-2:388303208821:cluster/gameday-cluster/8cae81cb-3b38-4b59-8f47-cadee5a804f0-6"
          broker_connection_type: "public"
        sts_role_arn: "arn:aws:iam::388303208821:role/pipeline-to-domain-role"
        region: "us-west-2"
      authentication:
        sasl:
          aws_msk_iam: "role"
  buffer:
    bounded_blocking:
      batch_size: 125000
      buffer_size: 1000000
  processor:
    - grok:
        match:
          message: ['%{IPORHOST:clientip} \[%{HTTPDATE:timestamp}\] %{NUMBER:response_status:int}']
    - drop_events:
        drop_when: '/response_status >= 900'
  sink:
    - stdout:
```

Sample logs in kafka topic:
```
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 400"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 300"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
{"message": "127.0.0.1 198.126.12 [10/Oct/2000:13:55:36 -0700] 200"}
```
