### ISSUE TITLE
How can we scan sub-directories in S3 source

### ISSUE THREAD

**Issue by headsha** [opensearch-project/data-prepper#3282]
I want to data-prepper to scan S3 objects that reside in sub-directories within the bucket.

this is my pipeline config:

```
s3-logs-pipeline-payment-transactions:    
      delay: 100
      workers: 4
      buffer:
        bounded_blocking: 
            buffer_size: 25600
            batch_size: 3200
      source:
        s3:
          acknowledgments: true
          compression: gzip
          codec:
            json:
          s3_select:
            expression: "select * from s3object s LIMIT 10000"
            expression_type: SQL
            input_serialization: json
            compression_type: gzip
            json:
              type: document
          aws:
            region: us-east-1
            sts_role_arn: <>
          scan:
            start_time:  2023-08-01T05:31:00
            end_time:  2023-08-01T06:31:00
            buckets:
              - bucket:
                  name: logs-dev-s3                
      sink:
        - opensearch:
            hosts: <>       
            aws:
              sts_role_arn: <>
              region: us-east-1
            index: sampled-logs-dev
            bulk_size: 4
```

How can i specify the folder path within the bucket?

This config seems to be working when log files are in the root folder in the bucket, 
but when it has sub-directories seeing the below in logs:

```2023-08-29T11:30:33,827 [s3-logs-pipeline-payment-transactions-sink-worker-2-thread-1] INFO  org.opensearch.dataprepper.plugins.sink.opensearch.ConnectionConfiguration - aws_sigv4 is set, will sign requests using AWSRequestSigningApacheInterceptor
Exception in thread "main" java.lang.IllegalStateException: Problem loading keystore to create SSLContext
	at org.opensearch.dataprepper.pipeline.server.SslUtil.createSslContext(SslUtil.java:35)
	at org.opensearch.dataprepper.pipeline.server.HttpServerProvider.get(HttpServerProvider.java:39)
	at org.opensearch.dataprepper.pipeline.server.DataPrepperServer.createServer(DataPrepperServer.java:65)
	at org.opensearch.dataprepper.pipeline.server.DataPrepperServer.start(DataPrepperServer.java:58)
	at org.opensearch.dataprepper.pipeline.server.DataPrepperServer$$FastClassBySpringCGLIB$$5d4867b0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
	at org.opensearch.dataprepper.pipeline.server.DataPrepperServer$$EnhancerBySpringCGLIB$$b82f3ac1.start(<generated>)
	at org.opensearch.dataprepper.DataPrepper.execute(DataPrepper.java:89)
	at org.opensearch.dataprepper.DataPrepperExecute.main(DataPrepperExecute.java:42)
Caused by: java.io.IOException: Is a directory
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:48)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:330)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:296)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:273)
	at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:232)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:101)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:263)
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:440)
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:487)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2012)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:221)
	at java.base/java.security.KeyStore.load(KeyStore.java:1473)
	at org.opensearch.dataprepper.pipeline.server.SslUtil.createSslContext(SslUtil.java:24)
	... 11 more
2023-08-29T11:30:34,253 [s3-logs-pipeline-payment-transactions-sink-worker-2-thread-1] INFO  org.opensearch.dataprepper.plugins.sink.opensearch.ConnectionConfiguration - Using the trust all strategy
2023-08-29T11:30:34,898 [s3-logs-pipeline-payment-transactions-sink-worker-2-thread-1] INFO  org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink - Initialized OpenSearch sink
2023-08-29T11:30:34,898 [s3-logs-pipeline-payment-transactions-sink-worker-2-thread-1] INFO  org.opensearch.dataprepper.pipeline.Pipeline - Pipeline [s3-logs-pipeline-payment-transactions] Sink is ready, starting source...
2023-08-29T11:30:34,901 [s3-logs-pipeline-payment-transactions-sink-worker-2-thread-1] INFO  org.opensearch.dataprepper.plugins.source.S3ClientBuilderFactory - Creating S3 client
2023-08-29T11:30:34,966 [s3-logs-pipeline-payment-transactions-sink-worker-2-thread-1] INFO  org.opensearch.dataprepper.plugins.source.S3ClientBuilderFactory - Creating S3 Async client
2023-08-29T11:30:35,140 [s3-logs-pipeline-payment-transactions-sink-worker-2-thread-1] WARN  org.opensearch.dataprepper.plugins.sourcecoordinator.inmemory.InMemorySourceCoordinationStore - The in_memory source coordination store is not recommended for production workloads. It is only effective in single node environments of Data Prepper, and can run into memory limitations over time if the number of partitions is too great.
2023-08-29T11:30:35,142 [s3-logs-pipeline-payment-transactions-sink-worker-2-thread-1] INFO  org.opensearch.dataprepper.pipeline.Pipeline - Pipeline [s3-logs-pipeline-payment-transactions] - Submitting request to initiate the pipeline processin```
