### ISSUE TITLE
Use environment variables in data prepper configs

### ISSUE THREAD

**Issue by ict-one-nl** [opensearch-project/data-prepper#3335]
**Is your feature request related to a problem? Please describe.**
Other logforwarders support the use of environment variables in configs. Logstash and FLuentbit both support the ${ENV_VAR} notation in their config files. This is useful in docker/kubernetes implementations where you might have several instances using the same config data. The data prepper docs don't reference this so I presume it's not supported yet.

**Describe the solution you'd like**
Use environment variables in the configs like Fluent-bit and Logstash do

**Describe alternatives you've considered (Optional)**
None

**Additional context**
None

**Comment by dlvenable** [comment]
I think we'd be supporting this with a syntax like `${{env.ENV_VAR}}`. We laid the groundwork for this in the AWS Secrets Manager work: #3382

**Comment by ict-one-nl** [comment]
Would be very useful, especially in a container environment 👍

**Comment by batpiste** [comment]
very useful indeed :)

**Comment by anand3493** [comment]
@dlvenable Would really like to use ```${{env.ENV_VAR}}``` in our EKS data prepper deployment. Do we have any plan on doing this ?

**Comment by dmossakowski** [comment]
Are there any plans to support this? It would indeed be very useful. OpenSearch components and OpenTelemetry collector support environment variables in their yaml files so it would be of great use to be able to do this in data prepper yaml config.

**Comment by arichtman-srt** [comment]
FWIW we worked around this with an init container that runs `envsubst` over the config files. We based our work off https://hub.docker.com/r/dibi/envsubst

**Comment by LHozzan** [comment]
We would like to use this feature as well. Especially to enhance security.

**Comment by LHozzan** [comment]
> As Ariel suggested earlier, I also used envsubst to work around this issue. You can see my answer with example docker compose config on OpenSearch forum: https://forum.opensearch.org/t/using-environment-variables-for-openid-connect-url-and-secret/22855/3

Thank you, I will use it as a inspiration for our use case, until solution will be delivered.

Unfortunately, this is still only workaround, from my point of view, not a full solution.

**Comment by Hursofid** [comment]
Hi, I've stuck on this too, can not make it work without storing credentials in ConfigMap :(

**Comment by LHozzan** [comment]
> Hi, I've stuck on this too, can not make it work without storing credentials in ConfigMap :(

Workaround above is working for me.
Or what exactly is problematic for you? Can you explain it more?

**Comment by Hursofid** [comment]
> Workaround above is working for me. Or what exactly is problematic for you? Can you explain it more?

Mentioned workaround is for docker and shared volume between two containers, but I'm on k8s.

I'm using the official helm chart opensearchproject/data-prepper with user-supplied values. I'm getting literal string ${OPENSEARCH_PASSWORD} in pipeline YAML config and I'm not allowed to store credentials in ConfigMap.
Using initContainers also requires shared ConfgMap between init container and actual data-prepper, correct me if I'm wrong?

**Comment by LHozzan** [comment]
> Mentioned workaround is for docker and shared volume between two containers, but I'm on k8s.

Me too.

> I'm using the official helm chart opensearchproject/data-prepper with user-supplied values. I'm getting literal string ${OPENSEARCH_PASSWORD} in pipeline YAML config and I'm not allowed to store credentials in ConfigMap.
> Using initContainers also requires shared ConfgMap between init container and actual data-prepper, correct me if I'm wrong?

OK, this is different. We using our own "logging stack", where we have control over all components. So, it will be good to open issue to helm chart project to temporary apply the workaround and not storing credentials in ConfigMap. It isnt secure.

On another hand, the workaround replacing on the fly credentials, so on the end, everybody with access to the pod can read it from the shell.

If you wish, I can share changed K8s objects, you can fork the helm chart and attempting to apply the workaround to only your copy of the helm chart. Of course, better will be discuss with maintainers in helm chart project to add the workaround there for everyone, who want to use project helm chart.

Unfortunately, I am not a maintainer from any of the OpenSearch projects, only "random passerby" ;).

**Comment by Hursofid** [comment]
@LHozzan Thanks for your valuable input Ľuboši, I appreciate that :)

Would you mind sharing objects so I can try to implement it?

Best regards

**Comment by arichtman-srt** [comment]
@Hursofid No, configMap does not need to be shared between containers - only volumeMount and that can be an emptyDir

https://github.com/arichtman/data-prepper-helm-chart/blob/0571a66a9c60fd38c593a861d18ce353288a8de2/templates/deployment.yaml#L32

**Comment by LHozzan** [comment]
> Would you mind sharing objects so I can try to implement it?

Sure, I will trying it with some explanations :).

<details>
<summary>

`chart/templates/data-prepper/data-prepper-sec.yaml`

</summary>

```yaml
# >> the secret is generated only, when DP is enabled (in some scenarios we dont using DP)
{{- if and (.Values.data_prepper) (.Values.data_prepper.enabled) }}
---
# >> i dont like "copy&paste", so we assembling the name in one place and just using it, where it is needed
{{ $secName := printf "%s-data-prepper-input-cred" .Release.Name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secName }} # >> assembled K8s secret name
  labels: {{ include "logging.labels" . | indent 4 }}
data:
  username: {{ .Values.data_prepper.username | b64enc }}
  {{- if .Values.data_prepper.password }}
  # >> if user providing his own password, we just using it as is
  password: {{ .Values.data_prepper.password | b64enc | quote }}
  {{ else }}
  # >> if the password is missing, we will be generating one (helm install), OR using existing values (helm upgrade)
    {{- $secret := lookup "v1" "Secret" .Release.Namespace $secName -}}
    {{- if or (not $secret) (not $secret.data) }}
  # >> generate password if secret does not exists (helm install)
    {{- $pswd := randAlphaNum 64 }}
  password: {{ b64enc $pswd | quote }}
    {{- else }}
  # >> reuse existing secret values (helm upgrade)
  password: {{ index $secret.data "password" }}
    {{- end }}
  {{- end }}
type: Opaque
{{- end }}
```

Here we using a little big machinery, because credentials must be provided, but many users would not providing their own passwords, or the passwords can be vague, which can lowering security. For details, see my comments.

After rendering the helm chart, in K8s will be generated something like this (for presentation it was slightly changed ;) ):

```yaml
apiVersion: v1
data:
  password: U3VwZXJTdHJvbmdBbmRTZWNyZXRQYXNzd29yZEZvckRQT25seUZvclByZXNlbnRhdGlvbgo=
  username: U2VjcmV0RFBVc2VyTmFtZU9ubHlGb3JQcmVzZW50YXRpb24K
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: REDACTED
    meta.helm.sh/release-namespace: REDACTED
    # (... and another important annotations)
  creationTimestamp: "2011-01-01T11:11:11Z"
  labels:
    app.kubernetes.io/instance: os
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: logging-stack
    app.kubernetes.io/opensearch: 2.22.2
    # (... and another important labels)
  name: os-data-prepper-input-cred
  namespace: REDACTED
  resourceVersion: "1978752375"
  uid: 58158fb3-6fa9-4d14-9b6f-59f2a51a3687
type: Opaque
```

</details>

<details>
<summary>

`chart/templates/data-prepper/data-prepper-cm.yaml`

</summary>

```yaml
{{- if and (.Values.data_prepper) (.Values.data_prepper.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-data-prepper
  labels: {{ include "logging.labels" . | indent 4 }}
data:
  data-prepper-config.yaml: |-
    ssl: false

  otel-span-ism-policy.json: |-
    {
      ( ... we would like to manage our own retention)
    }

  otel-span-index-template.json: |-
    {
      ( ... due to a using own retention settings, the template must be adapted as well)
    }

  pipelines.yaml: |-
    entry-pipeline:
      workers: 4
      delay: "100"
      source:
        otel_trace_source:
          ssl: true
          sslKeyCertChainFile: "/usr/share/data-prepper/server.crt"
          sslKeyFile: "/usr/share/data-prepper/server.key"
          port: 21890
          authentication:
            http_basic:
              username: ${dp_user} # !!!
              password: ${dp_pass} # !!!
      buffer:
        bounded_blocking:
          buffer_size: 1024
          batch_size: 256
      sink:
        - pipeline:
            name: "raw-pipeline"
        - pipeline:
            name: "service-map-pipeline"

    raw-pipeline:
      source:
        pipeline:
          name: "entry-pipeline"
      processor:
        - otel_traces:
      sink:
        - opensearch:
            # index_type: trace-analytics-raw
            index_type: custom
            index: otel-v1-apm-span
            hosts: [ {{ include "os_url" . }} ]
            cert: "/usr/share/data-prepper/root-ca.pem"
            template_file: "/usr/share/data-prepper/otel-span-index-template.json"
            ism_policy_file: "/usr/share/data-prepper/otel-span-ism-policy.json"
            username: ${os_user} # !!!
            password: ${os_pass} # !!!

    service-map-pipeline:
      delay: "100"
      source:
        pipeline:
          name: "entry-pipeline"
      processor:
        - service_map:
      sink:
        - opensearch:
            index_type: trace-analytics-service-map
            hosts: [ {{ include "os_url" . }} ]
            cert: "/usr/share/data-prepper/root-ca.pem"
            username: ${os_user} # !!!
            password: ${os_pass} # !!!

{{- end }}
```

Now, lets focusing to the part:
```yaml
              username: ${dp_user} # !!!
              password: ${dp_pass} # !!!
```

This values are placeholders for `envsubst` and will be replaced in time, when DP will be started.
Same situation is applicable is for `${os_...}` values.

On the end, credentials isnt in `ConfigMap`! In `ConfigMap` are only placeholders!

I believe, that rendered object not have sense here, so I omitting it.

</details>

<details>
<summary>

`chart/templates/data-prepper/data-prepper-deploy.yaml`

</summary>

```yaml
{{- if and (.Values.data_prepper) ( .Values.data_prepper.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-data-prepper
  labels: {{ include "logging.labels" . | indent 4 }}
    {{- with .Values.data_prepper.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.data_prepper.deployment.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.data_prepper.replicas }}
  selector:
    matchLabels: {{ include "logging.selectorLabels" . | indent 6 }}
      type: data-prepper
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/data-prepper/data-prepper-cm.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/data-prepper/data-prepper-sec.yaml") . | sha256sum }}
        {{- with .Values.data_prepper.pod.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels: {{ include "logging.selectorLabels" . | indent 8 }}
        type: data-prepper
        {{- with .Values.data_prepper.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      priorityClassName: {{ default .Values.priorityClass .Values.data_prepper.priorityClass }}
      {{- with .Values.data_prepper.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.data_prepper.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.data_prepper.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: main
        image: {{ .Values.data_prepper.image }}:{{ .Values.data_prepper.imageTag }}
        imagePullPolicy: {{ .Values.opensearch.imagePullPolicy }}
        resources: {{ toYaml .Values.data_prepper.resources | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: otlp
          initialDelaySeconds: 60
          periodSeconds: 60
        ports:
        - containerPort: 21890
          name: otlp
        {{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) ( .Values.data_prepper.monitoring.enabled ) }}
        - containerPort: 4900
          name: metrics
        {{- end }}
        volumeMounts:
        - name: data-prepper-pipelines
          # >> here is mounted the config file for DP from shared folder AFTER "envsubst" machinery (I mean, with credentials instead of placeholders)
          mountPath: /usr/share/data-prepper/pipelines/pipelines.yaml
          subPath: pipelines.yaml
        - name: data-prepper-config
          mountPath: /usr/share/data-prepper/config/data-prepper-config.yaml
          subPath: data-prepper-config.yaml
        - name: data-prepper-config
          mountPath: /usr/share/data-prepper/otel-span-ism-policy.json
          subPath: otel-span-ism-policy.json
        - name: data-prepper-config
          mountPath: /usr/share/data-prepper/otel-span-index-template.json
          subPath: otel-span-index-template.json
        - name: certificates
          mountPath: /usr/share/data-prepper/root-ca.pem
          subPath: ca.crt
        - name: certificates
          mountPath: /usr/share/data-prepper/server.key
          subPath: tls.key
        - name: certificates
          mountPath: /usr/share/data-prepper/server.crt
          subPath: tls.crt
        env:
        - name: JAVA_OPTS
          value: "-Xms{{ .Values.data_prepper.heapSize }} -Xmx{{ .Values.data_prepper.heapSize }} \
                  {{ .Values.opensearch.additionalJvmParams }}"
      initContainers:
      - name: init
        image: {{ include "init_container.image" . }}
        imagePullPolicy: {{ .Values.init_container.imagePullPolicy }}
        # >> here is the magic, where placeholders from configmap are changed to credentials and new config file is created for current DP run
        command: ["sh","-c",'/init/check_os.sh && envsubst < /tmp/pipelines.yaml.tmp > /data-prepper-share/pipelines.yaml']
        # >> we enabling DP start only, when OS is ready ("check_os.sh")
        env:
        - name: os_url
          value: {{ include "os_url" . }}
        - name: os_user
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-opensearch-dp-cred
              key: username
        - name: os_pass
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-opensearch-dp-cred
              key: password
        - name: dp_user
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-data-prepper-input-cred
              key: username # >> value for variable "dp_user" is obtained from K8s secret with name "{{ .Release.Name }}-data-prepper-input-cred" from secret's variable "username"
        - name: dp_pass
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-data-prepper-input-cred
              key: password # >> value for variable "dp_pass" is obtained from K8s secret with name "{{ .Release.Name }}-data-prepper-input-cred" from secret's variable "password"
        - name: os_cacert_file
          value: /etc/ssl/certs/open_search_ca.crt
        volumeMounts:
        - name: init
          mountPath: "/init"
        - name: certificates
          mountPath: /etc/ssl/certs/open_search_ca.crt
          subPath: ca.crt
          readOnly: true
        - name: data-prepper-config
          # >> to init container is mounted ConfigMap with placeholders
          mountPath: /tmp/pipelines.yaml.tmp
          subPath: pipelines.yaml
        - name: data-prepper-pipelines
          # >> init container (aka "envsubst") will store complete config file for DP here
          mountPath: /data-prepper-share
      volumes:
      - name: data-prepper-config
        configMap:
          name: {{ .Release.Name }}-data-prepper
      - name: data-prepper-pipelines
        # >> shared empty dir for all containers in the pod (I mean, here will be stored complete DP config file from init container run for container with DP)
        emptyDir: {}
      - name: init
        configMap:
          name: {{ .Release.Name }}-init
          defaultMode: 0755
      - name: certificates
        secret:
          secretName: {{ .Release.Name }}-opensearch-certificates
{{- end }}
```

In `Deployment` are all pieces of puzzle assembled to working pod as was described on the forum, but this K8s adaptation for same workaround. For details, please see my comments.

</details>

As I mentioned in my previous comment, this is just a workaround due to missing feature from DP side. When DP will can reading the credentials from environmental variables, the machinery in init container with `envsubst` will not be needed and DP will starting faster.

Another unpleasant thing for this workaround is, that if anybody can shell to the pod, can read the DP config file with credentials. In environmental variables it is possible to "hide" it.

If you have some questions, feel free to ask. Hope, that helps :).

> Thanks for your valuable input Ľuboši, I appreciate that :)

PS: Rad som pomohol. Pozname sa? :)
