### ISSUE TITLE
Allow KeyValue processor to write parsed entries to event root

### ISSUE THREAD

**Issue by oeyh** [opensearch-project/data-prepper#3378]
**Is your feature request related to a problem? Please describe.**
KeyValue processor currently writes parsed entries to a user specified `destination` (default to `"parsed_message"`) but doesn't support writing those entries directly to event root. 

**Describe the solution you'd like**
When `destination` is set to null, we write parsed entries to root. The config would look like this:

```yaml
...
processor:
  key_value:
    destination:
```
or
```yaml
...
processor:
  key_value:
    destination: null
```

**Describe alternatives you've considered (Optional)**
Unless user specifies a destination, writing to root as default behavior. But this is going to be a breaking change.

**Additional context**
`parse_json` has similar configuration that when `target` is null, the parsed results will be written to root.
