### ISSUE TITLE
Support KMS encryption context in the Kafka buffer's encryption

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#3484]
**Is your feature request related to a problem? Please describe.**

The Kafka buffer can now decrypt an envelope encryption key using KMS. However, sometimes, we want to decrypt with an encryption context.

**Describe the solution you'd like**

Add support for KMS encryption context in the configuration. Use this value when sending the `kms:Decrypt` request.

```
buffer:
  kafka:
    topics:
      - name: MyTopic
        encryption_key: AQIDAHhBQ4iH7RP28kWDRU1yN2K73qYEE2d8i06EBly7HoDSIwFXoO+oiW+HOlam8lfIUFwLAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM/j9Uf9cxYv/poV0FAgEQgDuVG9jfls3Ys7dR/cRKmdkcYDJw/XzR/ZEnZwcT9e+XB1T+SxC0YHLtc33lRwoD/UV0Ot+y8oUBqMvaXg==
        kms:
          key_id: alias/ExampleAlias
          encryption_context:
            mykey1: myvalue1
            mykey2: myvalue2
            mykey3: myvalue3
```

Additionally, we can move the `kms_key_id` into a new `kms` section.

**Describe alternatives you've considered (Optional)**

Add a new field: `kms_encryption_key`. But, this list of `kms_` prefix options could grow.

**Additional context**

Kafka buffer issue for encryption/decryption and KMS: #3422
