### ISSUE TITLE
[BUG] parse_json processor doesn't handle pointers with destinations

### ISSUE THREAD

**Issue by mmehrten** [opensearch-project/data-prepper#3515]
**Describe the bug**
When using a pointer and a destination together with the `parse_json` processor, the output data in the destination contains an incorrect nested key.

**To Reproduce**

pipelines.yaml:
```
parse-json-pipeline:
  source:
    http:
  sink:
    - stdout:
  processor:
    - parse_json:
        source: "message"
        destination: "target"
        pointer: "outer_key/inner_key"
```

Input:
```
JSON='[{"message": "{\"outer_key\": {\"inner_key\": \"1220\"}}"}]'
curl -k -XPOST -H "Content-Type: application/json" -d "${JSON}" http://localhost:2021/log/ingest
```

Output:
```
{"message":"{\"outer_key\": {\"inner_key\": \"1220\"}}","target":{"inner_key":"1220"}}
```

**Expected behavior**
Expected / desired output:
```
{"message":"{\"outer_key\": {\"inner_key\": \"1220\"}}","target":"1220"}
```

**Environment (please complete the following information):**
opensearchproject/data-prepper:latest 
tag:2c474f8f05fb
data-prepper 2.5

**Additional context**
When doing complex conversions (e.g. input JSON to SS4O or OTEL schema), users need the ability to perform standard JSON re-mapping from a source schema into a destination schema. This currently isn't supported by DataPrepper.

**Comment by graytaylor0** [comment]
To achieve the desired result, you can use this configuration.

```
processor:
    - parse_json:
        source: "message"
        pointer: "outer_key/inner_key"
    - rename_keys:
        entries:
          - from_key: "inner_key"
            to_key: "target"
```
