### ISSUE TITLE
Improved schema transformation utilities in DatPrepper

### ISSUE THREAD

**Issue by mmehrten** [opensearch-project/data-prepper#3526]
**Is your feature request related to a problem? Please describe.**
Having the ability to do complex schema transformations in DataPrepper is an important component of log observably and index management. For example, if an organization wants to standardize on SS4O schema without rewriting logging in all their apps, today they would need to insert a middleware between the log source and the DataPrepper processors to perform the transformation. This feels less than ideal - in a perfect world, DataPrepper could provide mechanisms to do schema transformation and enrichment.

**Describe the solution you'd like**
Configurations to support schema re-mapping. For example, a processor config could specify the explicit remapping logic:

```
remap:
  # Accessing key/value pairs in a map object by key name, moving the keys
  - source: pets/<name>
    target: $name
  # Simple move from key to key
  - source: event/context/region
    target: aws/region
  # Explode a list into many documents (maybe required as a separate pipeline)
  - source: event/messages
    operation: explode
    on_duplicate_keys: merge
 ...
```

Or possibly a UDF?

**Describe alternatives you've considered (Optional)**
I've considered using add_entries, copy_values, delete_entries, etc. but they're too simple for the types of transformations customers need. If a customer wanted to map e.g. raw CloudTrail logs to SS4O for use with OpenSearch Integrations, it would be nearly impossible to use the existing transformation logic.

**Comment by mmehrten** [comment]
I was able to accomplish most of this with existing functionality - apologies for my ignorance! I'll open a new issue for specifically the explode functionality.

Example pipeline I made to do what I was looking for (SS4O in CloudTrail):


```
ss4o-cloudtrail-pipeline:
  source:
    http:
  processor:
    - parse_json:
        source: "message"
        destination: "parsed"
    - rename_keys:
        entries:
          - from_key: "parsed"
            to_key: "aws/cloudtrail"
          - from_key: "message"
            to_key: "body"
          - from_key: "timestamp"
            to_key: "observedTimestamp"
          - from_key: "logGroup"
            to_key: "event/log_group"
          - from_key: "logStream"
            to_key: "event/log_stream"
          - from_key: "owner"
            to_key: "cloud/account/id"
    - copy_values:
        entries:
          - from_key: "aws/cloudtrail/eventTime"
            to_key: "@timestamp"
          - from_key: "aws/cloudtrail/eventId"
            to_key: "traceId"
          - from_key: "aws/cloudtrail/awsRegion"
            to_key: "cloud/region"
          - from_key: "aws/cloudtrail/cloud/account/name"
            to_key: "cloud/account/name"
          - from_key: "aws/cloudtrail/eventSource"
            to_key: "cloud/service/name"
    - add_entries:
        entries:
          - key: "attributes/data_stream/dataset"
            value: "cloudtrail_log"
          - key: "attributes/data_stream/namespace"
            value: "production"
          - key: "attributes/data_stream/type"
            value: "cloud_trail_logs"
          - key: "event/domain"
            value: "cloudtrail"
          - key: "event/source"
            value: "cloudwatch"
          - key: "event/name"
            value: "cloud_trail"
          - key: "event/result"
            value:  "ACCEPT"
          - key: "cloud/provider"
            value: "aws"
    - delete_entries:
        with_keys: ["parsed"]
  sink:
    - stdout:

```

**Comment by mmehrten** [comment]
I was able to accomplish most of this with existing functionality - apologies for my ignorance! I'll open a new issue for specifically the explode functionality.

Example pipeline I made to do what I was looking for (SS4O in CloudTrail):


```
ss4o-cloudtrail-pipeline:
  source:
    http:
  processor:
    - parse_json:
        source: "message"
        destination: "parsed"
    - rename_keys:
        entries:
          - from_key: "parsed"
            to_key: "aws/cloudtrail"
          - from_key: "message"
            to_key: "body"
          - from_key: "timestamp"
            to_key: "observedTimestamp"
          - from_key: "logGroup"
            to_key: "event/log_group"
          - from_key: "logStream"
            to_key: "event/log_stream"
          - from_key: "owner"
            to_key: "cloud/account/id"
    - copy_values:
        entries:
          - from_key: "aws/cloudtrail/eventTime"
            to_key: "@timestamp"
          - from_key: "aws/cloudtrail/eventId"
            to_key: "traceId"
          - from_key: "aws/cloudtrail/awsRegion"
            to_key: "cloud/region"
          - from_key: "aws/cloudtrail/cloud/account/name"
            to_key: "cloud/account/name"
          - from_key: "aws/cloudtrail/eventSource"
            to_key: "cloud/service/name"
    - add_entries:
        entries:
          - key: "attributes/data_stream/dataset"
            value: "cloudtrail_log"
          - key: "attributes/data_stream/namespace"
            value: "production"
          - key: "attributes/data_stream/type"
            value: "cloud_trail_logs"
          - key: "event/domain"
            value: "cloudtrail"
          - key: "event/source"
            value: "cloudwatch"
          - key: "event/name"
            value: "cloud_trail"
          - key: "event/result"
            value:  "ACCEPT"
          - key: "cloud/provider"
            value: "aws"
    - delete_entries:
        with_keys: ["parsed"]
  sink:
    - stdout:

```
