### ISSUE TITLE
[BUG] NullPointer exception in DefaultKafkaClusterConfigSupplier get API 

### ISSUE THREAD

**Issue by kkondaka** [opensearch-project/data-prepper#3528]
**Describe the bug**
NullPointer exception in DefaultKafkaClusterConfigSupplier get API 

**To Reproduce**
Start pipeline with the following YAML file, it crashes because the kafkaClusterConfig is null
```
kafka-pipeline:
  source:
    kafka:
      bootstrap_servers: ["localhost:9092"]
      acknowledgments: true
      encryption:
        type: none
      topics:
         - name: "TestTopic"
           group_id: "TestGroup"
  sink:
    - stdout:
```

**Expected behavior**
The pipeline should start successfully.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**
