### ISSUE TITLE
Support conditional script update of documents in the OpenSearch sink

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#3563]
**Is your feature request related to a problem? Please describe.**
As a user of the OpenSearch sink, I would like to conditionally update documents by comparing the existing document in OpenSearch with the updated document. 

**Describe the solution you'd like**
An option to specify a `script` parameter that will apply to update and upsert operation in the sink (https://opensearch.org/docs/latest/api-reference/document-apis/update-document/#script-example).

This requires that the incoming update documents contain the fields that are referenced in the `script`. 

**Describe alternatives you've considered (Optional)**
One alternative to having OpenSearch handle this would be to have Data Prepper handle it, which would mean an extra read of each document with an `update` or `upsert` operation, and then relying on Data Prepper expression as the condition instead of the `script`. the benefit of this approach would be that we could support comparisons on Data Prepper metadata, instead of requiring the data be in the Event.

**Additional context**

**Comment by graytaylor0** [comment]
Index configuration for new `script` parameter (https://github.com/opensearch-project/data-prepper/blob/44b62a2ffaf2aa091586825cc47373e4c372b0c1/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/index/IndexConfiguration.java#L61)

Pass script here: https://github.com/opensearch-project/data-prepper/blob/44b62a2ffaf2aa091586825cc47373e4c372b0c1/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java#L358

**Comment by dinujoh** [comment]
```
opensearch:
  hosts: ["https://localhost:9200"]
  index: "my-index"
  action: "upsert"
  document_id: "${/primary_key}"
  script:
    source: "ctx._source.putAll(params.doc); ctx._source.write_count = (ctx._source.containsKey('write_count') ? ctx._source.write_count + 1 : 1)"
    params:
      table: "${getMetadata(\"table_name\")}"
      version: "${getMetadata(\"event_timestamp\")}"

```

Configuration Fields

* script.source:  The script source code (Painless)
* script.params: Additional parameters passed to the script. Values support ${} expression syntax for dynamic resolution from event fields (${/field}) or metadata (${getMetadata("key")})


Automatic Behavior

* params.doc: The event document is always automatically passed as params.doc. No configuration needed.
* scripted_upsert: Always set to true when script is configured. The script runs on every write including the first (document creation).
* Script language: Hardcoded to painless. Can be made configurable if OpenSearch adds support for other inline script languages.
* Param resolution: Param values containing ${} are resolved per-event in doOutput() using event.formatString() — same mechanism as document_id, routing, and action. Static values pass through unchanged.

Validation Rules

* script is only valid when action is update or upsert. Configuration should fail if script is set with index, create, or delete actions.


Bulk Request Behavior

When script is configured and the action is update or upsert:

Without script (current behavior):

```
{"update": {"_index": "my-index", "_id": "doc-1"}}
{"doc": {...}, "doc_as_upsert": true}
```

With script configured:

```
{"update": {"_index": "my-index", "_id": "doc-1"}}
{"script": {"source": "...", "lang": "painless", "params": {"doc": {...}, "table": "products"}}, "upsert": {...}, "scripted_upsert": true}
```

The upsert body seeds ctx._source on first create, then the script runs. On subsequent updates, the script runs against the existing document. The script always runs because scripted_upsert is always true.


Use Cases

Non-Join (single source → single document)
```
# Conditional price update — only update if lower
script:
  source: "if (params.doc.price < ctx._source.price) { ctx._source.price = params.doc.price }"

# Version-gated full replace
script:
  source: "if (params.doc.version > ctx._source.version) { ctx._source = params.doc }"

# Merge with write tracking
script:
  source: "ctx._source.putAll(params.doc); ctx._source.write_count = (ctx._source.containsKey('write_count') ? ctx._source.write_count + 1 : 1)"
```

Join (multiple tables → denormalized document)
```
# RDS denormalization — merge fields from multiple tables, handle deletes
script:
  source: |
    String[] fields = params.fields.splitOnToken(',');
    if (params.is_delete == 'true') {
      for (String field : fields) { ctx._source.remove(field) }
    } else {
      for (String field : fields) {
        if (params.doc.containsKey(field)) { ctx._source[field] = params.doc[field] }
      }
    }
  params:
    table: "${getMetadata(\"table_name\")}"
    fields: "${getMetadata(\"table_fields\")}"
    is_delete: "${getMetadata(\"change_event_type\")}"
```

Performance Considerations

* Script updates require a read-modify-write cycle in OpenSearch vs a plain write for index action
* Painless scripts are compiled and cached after first execution — repeated runs are fast
* For simple scripts (field merge, counter increment): ~10-30% slower than plain index
* Bulk size tuning helps — larger batches amortize the fixed per-request overhead
* retry_on_conflict is not currently set on the UpdateOperation — may need to expose as config for high-throughput CDC scenarios

Versioning Considerations

* document_version with external versioning is incompatible with scripts — OpenSearch rejects the combination. Should validate and reject this config upfront.
* For denormalization, per-table version tracking in the script (via a versions map) handles out-of-order CDC events
* Multiple Data Prepper workers can cause out-of-order writes for the same document — scripts without version tracking may produce incorrect results
