### ISSUE TITLE
Add CMK support to DynamoDB source

### ISSUE THREAD

**Issue by daixba** [opensearch-project/data-prepper#3564]
**Is your feature request related to a problem? Please describe.**
DynamoDB supports customer to choose their own customer key when doing the data export, that is used for encrypt the exported data files.

Currently, there is not an option for customer to provide the CMK, will default to use S3-SSE encryption, but that may not be aligned with customers security policy.

**Describe the solution you'd like**
The ask is to add CMK support, the proposed solution is to add an extra option under export.

```
        - table_arn: "arn:aws:dynamodb:us-west-2:xxx:table/xxx-table"
          export:
            s3_bucket: "xxx-bucket"
            s3_prefix: "export/"
            s3_sse_kms_key_id: "key_id"
```

**Describe alternatives you've considered (Optional)**
n/a

**Additional context**
Additional permission will be required for the role to read and decrypt the data files via CMK.
