### ISSUE TITLE
Centralize SSL configuration and certificate provider factory

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/data-prepper#364]
**Is your feature request related to a problem? Please describe.**
The TLS/SSL config has not been unified across plugins (otel-trace-source, http, peerforwarder). It should be unifiable so that all plugins could reuse the same config and CertificateProviderFactory.

**Describe the solution you'd like**
We need to sort out all necessary TLS/SSL config parameters and document them in a separate TLS/SSL module

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by dlvenable** [comment]
This can be solved using plugins similar to what Data Prepper does for authentication (see #464).

Example for the file-based certificates:

```
http:
  ssl: true
  certificate:
    file:
      certificate_path: /usr/share/my/path/public.cert
      private_key_path: /usr/share/my/path/private.key
```

Example for the S3-based certificates:

```
http:
  ssl: true
  certificate:
    s3:
      certificate_uri: s3://mybucket/my/key/public.cert
      private_key_uri: s3://mybucket/my/key/private.key
```

Example for the ACM-based certificates:

```
http:
  ssl: true
  certificate:
    acm:
      arn: arn:...
      passphrase: secret
```
