### ISSUE TITLE
[BUG] update and upsert bulk actions do not include changes from document_root_key, exclude_keys, etc

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#3745]
**Describe the bug**
The update and upsert actions always pass the full Event to the bulk actions, instead of only passing the part of the Event that is filtered from `document_root_key`, `exclude_keys`, `include_keys`, etc. 

For update we are passing the original jsonNode here (https://github.com/opensearch-project/data-prepper/blob/979a0045b4970c7d31909a722a753adc3d2666ca/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java#L307), while for index we pass the document without the root key / exclude_keys here (https://github.com/opensearch-project/data-prepper/blob/979a0045b4970c7d31909a722a753adc3d2666ca/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java#L334). 

**To Reproduce**

Send two items with the following structure and sink config

```
{"operation": "index", "item": { "doc_id": 110, "name": "Original Name" }}
{"operation": "update", "item": { "doc_id": 110, "name": "Updated Name" }}
```

```
        document_id_field: "item/doc_id"
        index: "actions-test-index"
        document_root_key: "item"
        actions:
          - type: "update"
            when: '/operation == "update"'
          - type: "index"
```

and the final document in OpenSearch will look like

```
{
        "_index": "actions-test-index",
        "_id": "110",
        "_score": 1,
        "_source": {
          "doc_id": 110,
          "name": "Original Name",
          "item": {
            "name": "Updated Name",
            "doc_id": 110
          },
          "operation": "update"
        }
}
```

**Expected behavior**

The updated document should look like

```
{
        "_index": "actions-test-index",
        "_id": "110",
        "_score": 1,
        "_source": {
          "doc_id": 110,
          "name": "Updated Name"
        }
}
```
