### ISSUE TITLE
Create a decoder processor to decode encrypted Event keys

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#3841]
**Is your feature request related to a problem? Please describe.**
As a user of Data Prepper, my Events contain keys that are encoded in different formats, such as `gzip`, `base64`, and `protobuf` (https://protobuf.dev/programming-guides/encoding/). 

Sample Event
```
{
  "my_protobuf_key": "",
  "my_gzip_key": "H4sIAAAAAAAAA/NIzcnJVyjPL8pJAQBSntaLCwAAAA==",
  "my_base64_key": "SGVsbG8gd29ybGQ="
}
```

**Describe the solution you'd like**
A new processor called a `decoder` processor that can decode various encodings. The following configuration example would decode the three values in the example Event above

```
processor:
  - decoder: 
       key: "my_base64_key"
       # Can be one of gzip, base64, or protobuf
       base64:
   - decoder:
        key: "my_gzip_key"
        gzip:
   - decoder:
         key: "my_protobuf_key"
         protobuf:
            message_definition_file: "/path/to/proto_definition.proto"
```

**Additional context**

**Comment by dlvenable** [comment]
It may be advantageous to have a different processors for different encodings for a few reasons.

1. Each of these brings in different dependencies and long-term we may want to make some of these plugins optional to keep the overall size of the project down.
2. This could produce simpler YAML as we won't need to the nested group for custom configurations.
3. It remains consistent with other processors. We already can decode/parse JSON, CSV, and now ION. They have their own processors.

```
processor:
  - decode_protobuf:
       key: my_prototbuf_key
       message_definition_file: "/path/to/proto_definition.proto"
  - decode_base64:
       key: my_base64_key
```

Compression might be a special case. Maybe we'd have a single processor for that. Though it wouldn't help with overall dependency reduction.

```
processor:
  - decompress:
       key: my_gzip_key
       type: gzip
```
