### ISSUE TITLE
Add string truncate processor to the family of mutate string processor

### ISSUE THREAD

**Issue by kkondaka** [opensearch-project/data-prepper#3925]
**Is your feature request related to a problem? Please describe.**
The string truncate processor should truncate the string to the user configured length.

**Describe the solution you'd like**
Solution would be to support truncate string processor with the following config
```
  processor:                                                                                                                                            
    - truncate:                                                                                                                                
        entries:                                                                                                                                        
          - source: "message" 
            start_at: 2                                                                                                                      
            length: 5                                                                                                                                  
            truncate_when: <condition>  
```

**Describe alternatives you've considered (Optional)**

**Additional context**
