### ISSUE TITLE
Add GeoIP extensions in Data Prepper Config

### ISSUE THREAD

**Issue by asifsmohammed** [opensearch-project/data-prepper#3941]
Add GeoIP service configuration in `data-prepper-config.yaml` file.

This can be done by adding it in extensions and used by plugin, instead of configuring it in each plugin instance.

```
extensions:
  geoip_service:
    maxmind:
      database_paths: ["path1", "path2"]
      database_refresh_interval: "P10D"
      cache_size: 2048
```
