### ISSUE TITLE
Use a public CDN endpoint to get MaxMind GeoLite2 Data by default

### ISSUE THREAD

**Issue by asifsmohammed** [opensearch-project/data-prepper#3942]
Use a public CDN endpoint to improve the user experience and provide MaxMind GeoLite2 Database by default. 

Configuration for using geoip can be as simple as this,
```
processor:
  - geoip:
      keys:
          - key:
              source: "/peer/ip"
              target: "target1"
```
