### ISSUE TITLE
[Feature Request] Conditionally Assign New Field Logic on Record Arrays 

### ISSUE THREAD

**Issue by adplotzk** [opensearch-project/data-prepper#3961]
This is a feature request which is requested a processor to implement the following ETL functionality to handle Conditional Logic on Record Arrays - 

#REQUIRED RECORD ARRAY MANIPULATION

            "src_object_1": {
                "src_key_1": "src_val_1",
                "src_key_2": "src_val_2",
                "src_nested_array": [
                    {
                        "src_name": "src_val_3",
                        "src_value": "src_val_4"
                    },
                    {
                        "src_name": "src_val_5",
                        "src_value": "src_val_6"
                    },
                    {
                        "src_name": "src_val_7",
                        "src_value": "src_val_8"
                    }
                ]
            }
        
#TO
        
        "dest_object_1": {
            "dest_name": "src_val_4",
            "dest_nested_array": [
                    {
                        "src_name": "src_val_3",
                        "src_value": "src_val_4"
                    },
                    {
                        "src_name": "src_val_5",
                        "src_value": "src_val_6"
                    },
                    {
                        "src_name": "src_val_7",
                        "src_value": "src_val_8"
                    }
                ]
        }
        
#MAPPING

            - from_key: "/src_object_1/nested_array[]/src_value"
              add_when: '/src_object_1/nested_array[]/src_name == "src_val_3"'
              to_key: "/dest_object_1//dest_name"

            # preserve nested array
            - from_key: "/src_object_1/src_nested_array"
               to_key: "/dest_object_1/dest_nested_array"

**Comment by oeyh** [comment]
I believe this can be done with existing processors using a config like this:

```
processor:
  - list_to_map:
      source: "/src_object_1/nested_array"
      key: "src_name"
      value_key: "src_value"
      target: "my-map"
  - copy_values:
      entries:
        - from_key: "my-map/src_val_3"
          to_key: "/dest_object_1//dest_name"
        - from_key: "/src_object_1/src_nested_array"
          to_key: "/dest_object_1/dest_nested_array"
  - delete_entries:
      with_keys: ["my-map"]

```

The list_to_map processor turns:
```json
"src_nested_array": [
  {
      "src_name": "src_val_3",
      "src_value": "src_val_4"
  },
  {
      "src_name": "src_val_5",
      "src_value": "src_val_6"
  },
  {
      "src_name": "src_val_7",
      "src_value": "src_val_8"
  }
]
```
into:
```json
"my-map": {
  "src_val_3": "src_val_4",
  "src_val_5": "src_val_6",
  "src_val_7": "src_val_8"
}
```

**Comment by 01samiksha** [comment]
But this is only true for array of objects.
If the requirement is something like:
```
   "src_object_1": {
            "src_key_1": "src_val_1",
            "src_key_2": "src_val_2"
        }
``` 
If the condition has to be put on the key, if "src_key_3" exists then only add additional key, then we would require conditional mapping

```
        - add_when: '/src_object_1/src_val_3 != null'
         from_key: "/src_object_1/src_val_3"
          to_key: "/dest_object_1//dest_name"
```

**Comment by oeyh** [comment]
@01samiksha If "src_key_3" does not exists, `copy_values` processor won't copy anything, so the above config should just work. `copy_values` processor does accept conditions, so you can also do this, which should have the equivalent effect:
```yaml
...
  - copy_values:
      entries:
        - from_key: "my-map/src_val_3"
          to_key: "/dest_object_1/dest_name"
          copy_when: "my-map/src_val_3 != null"
...
```
