### ISSUE TITLE
[Feature Request] Mapping Array to string

### ISSUE THREAD

**Issue by adplotzk** [opensearch-project/data-prepper#3963]
This is a feature request which is requested a processor to implement the following ETL functionality to handle Mapping Array to string

#REQUIRED RECORD ARRAY MANIPULATION

            "some_source": [
                    {
                        "src_key_1": "val_1"
                    },
                    {
                        "src_key_1": "val_2"
                    }
                ]
            }, 
          
#TO
           
            }
            "some_dest": {
                "dest_key_1": "val_1, val_2"
            }
                
          
#MAPPING
          
        - from_key: "some_source[]/src_key_1"
          to_key: "some_dest/dest_key1"

**Comment by oeyh** [comment]
I think this can be done in steps:

1. Use a processor to access fields from a list of objects and put them under the original key. This is basically what #3867 requests, can be a new list processor or modification to existing `list_to_map` processor.
From:
```json
"some_source": [
  {
    "src_key_1": "val_1"
  },
  {
    "src_key_1": "val_2"
  }
]
```
to:
```json
"some_dest": {
  "src_key_1": ["val_1", "val_2"]
}
```

2. Rename `src_key_1` to `dest_key_1` with existing `rename_keys` processor, and we get:
```json
"some_dest": {
  "dest_key_1": ["val_1", "val_2"]
}
```

3. If necessary, join the array of strings with specified delimiter to form a new list. This requires a new `join` processor. And we get:
```json
"some_dest": {
  "dest_key_1": "val_1, val2"
}
```

**Comment by oeyh** [comment]
Regarding the new processor mentioned above to convert list to string, a proposed solution is:
A new list processor with join action
The configuration would look like this:
```
  processor:
    - list:
        join:
          source: "mylist"
          delimiter: ","
```

**Comment by dlvenable** [comment]
Maybe for the new processor, we should give it a name that correctly indicates what it does when used as a verb. So perhaps make `join` the processor. Or call it `list_to_string`.

Do we need these extra nesting? Can it just be either of these?

```
processor:
- join:
     source: mylist
     delimiter: ','
```

or

```
processor:
- list_to_string:
     source: mylist
     delimiter: ','
```

**Comment by oeyh** [comment]
That's my original thought as well. Had some discussion offline and we're thinking about putting different list operations under the hood of a `list` processor. In this issue, it's a `join` operation for lists. In #3962, there's a `copy` operation for lists.

**Comment by dlvenable** [comment]
@oeyh , @kkondaka 

What is the value of having different list operations if there is no significant common configuration shared? It seems to result in extra layering for users in the YAML.

I'd prefer to start with a cleaner pipeline YAML. Then we can work from there to a technical design. There might be some shared code, but we could handle that by sharing the same Gradle project.

**Comment by oeyh** [comment]
I think the main value is to make it easier for users to locate a processor to use. If one wants to operate on lists/arrays, go to list processor to find it. It also makes processor naming cleaner, e.g. `list_to_string`, `copy_list_items`, `append_to_list`, `delete_list_items` can be `join`, `copy`, `append`, `delete` operations under `list` processor.

Now is also a good time to do it because we lack operations on lists and will likely add a couple to it soon.

**Comment by oeyh** [comment]
Looking at some existing processor configs (eg, `aggregate`), the list processor configuration would look like this:
```yaml
processor:
    - list:
        source: "source-list"
        target: "target"  
        action:
          join:
            delimiter: ","
        process_when: ...
```
Does it make more sense? It'll have some common options like `source`, `target`, `when`, while having one of the actions like `join` (this issue), `copy` (#3962), etc., similar to `aggregate` processor.
