### ISSUE TITLE
Delete input for processors which expand the event

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#3968]
**Is your feature request related to a problem? Please describe.**

Data Prepper pipelines often expand events using processors like `grok` or `parse_json`. Processors like these output events which are larger than the input event. Each event now takes up more memory.

Data Prepper processors work in batches. Each processor is invoked with the whole batch of events. So when executing a pipeline that expands events, Data Prepper expands entire batches of events in the expansion processor. Then downstream processors which reduce some redundant data (e.g. the field which was parsed) happen after the batch.

Say you have a pipeline where you grok a field to get data from it. Then you delete that input field. With a batch size of 100,000, Data Prepper will expand all 100,000 events. Then it removes the messages for all 100,000 events. 

```
my-pipeline:
  buffer:
    bounded_blocking:
      batch_size: 100000
  processor:
    - grok:
        match:
          message: ["..."]
    - delete_entries:
        with_keys: ["message"]
```

**Describe the solution you'd like**

I'd like to be able to remove the `message` field sooner, rather than wait for all 100,000 events to be groked.

For these processors which have large expansion potential, provide an additional configuration to delete the input source. This way, the processor itself can remove the input data sooner and reduce the memory needs of Data Prepper.

```
  processor:
    - grok:
        match:
          message: ["..."]
        delete_source: true
    - parse_json:
        source: message
        delete_source: true

```

These would only delete the source key if the match or parsing succeeded.

**Describe alternatives you've considered (Optional)**

I've also considered a concept of allowing processors to declare that they can work on smaller batches. This would work well for these processors that just loop over the events, just like grok and parse_json.

This would be nice because pipeline authors won't need to think about the memory usage and Data Prepper could take care of reducing the batch sizes. However, this work could be complicated to implement. It could be as simple as running a single Event through each processor. But, we would need to have points at which we re-batch for the processors where it matters.
