### ISSUE TITLE
Support codec on the file source to help with testing

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#4018]
**Is your feature request related to a problem? Please describe.**

Sometimes creating a small pipeline that reads from a file helps test a pipeline before transitioning to S3.

**Describe the solution you'd like**

Support input codecs on the `file` source.

e.g.

```
  source:
    file:
      path: my-file.log
      codec:
        newline:
```
