### ISSUE TITLE
Append values to lists in an event

### ISSUE THREAD

**Issue by oeyh** [opensearch-project/data-prepper#4129]
**Is your feature request related to a problem? Please describe.**
Append is a common operation for lists. As a Data Prepper user, I would like to be able to append values to a list in the event. 

**Describe the solution you'd like**
`add_entries` processor can be enhanced to achieve this by adding an `append_if_key_exists` option:
```
    - add_entries:
        entries:
          - key: "fruits"
            value: "banana"
            append_if_key_exists: true
```
Example1:
Input:
```json
{"fruits": "apple"}
```
output:
```json
{"fruits": ["apple", "banana"]}
```

Example2:
Input:
```json
{"fruits": ["apple", "watermelon"]}
```
output:
```json
{"fruits": ["apple", "watermelon", "banana"]}
```

**Describe alternatives you've considered (Optional)**
A separate `list_append` processor. 

**Additional context**
#3967
