### ISSUE TITLE
Support object checksums in the S3 sink

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#4146]
**Is your feature request related to a problem? Please describe.**

S3 supports object checksums to verify the content sent to S3. With this, S3 will reject files that do not match the checksum. This can prevent invalid objects. Additionally, S3 Object Lock requires checksums. 

**Describe the solution you'd like**

Provide a configuration to specify the checksums for objects uploaded.

New configuration: `checksum`
Valid values: `crc32`, `crc32c`, `sha1`, `sha256`

```
  sink:
    - s3:
        bucket: mybucket
        checksum: crc32
        compression: gzip
        object_key:
          path_prefix: logs/%{yyyy}/%{MM}/%{dd}/%{HH}/
        codec:
          ndjson:
```

**Describe alternatives you've considered (Optional)**

Data Prepper could support MD5 as well. We'd need to determine if the MD5 should be another option entirely or an additional entry in the list. This probably depends on whether the settings are mutually exclusive. Perhaps you can have both? However, just adding the current checksum should be sufficient.

**Additional context**

Current error when writing to S3 with object lock:

```
data-prepper  | software.amazon.awssdk.services.s3.model.S3Exception: Content-MD5 OR x-amz-checksum- HTTP header is required for Put Object requests with Object Lock parameters (Service: S3, Status Code: 400, Request ID: XYZ, Extended Request ID: XYZ)
```

https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-managing.html#object-lock-put-object

https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/s3-checksums.html
