### ISSUE TITLE
Provide an OpenSearch API source

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#4180]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to point existing OpenSearch clients that perform ingestion to Data Prepper instead.

**Describe the solution you'd like**

Create a new source - `opensearch_api` which supports the [Document APIs](https://opensearch.org/docs/latest/api-reference/document-apis/index/) that perform ingestion.

Minimally, this can be:

```
source:
  opensearch_api:
```

Some more options:

```
source:
  opensearch_api:
    port: 9200
    ssl: true
    ssl_certificate_file: /path/to/certificate
    ssl_key_file: /path/to/private.key
    thread_count: 200
    authentication:
      http_basic:
        username: ingest_client
        password: ${{aws_secrets:ingest:password}}
```

**Additional context**

This can start with only the `_bulk` API and this could supersede #248. Over time we can add the other endpoints as well.

## Tasks

- [ ] #248 
- [ ] Support other ingestion APIs
