### ISSUE TITLE
[BUG] [Docs] OpenSearch sink documented permissions insufficient

### ISSUE THREAD

**Issue by arichtman-srt** [opensearch-project/data-prepper#4194]
**Describe the bug**

When configuring an OpenSearch sink with a user, the permissions documented result in failure to write data to OpenSearch

**To Reproduce**

Configure pipeline sink:

```
entry-pipeline:
  buffer:
    bounded_blocking:
      batch_size: 160
      buffer_size: 10240
  delay: "100"
  sink:
  - pipeline:
      name: raw-pipeline
raw-pipeline:
  buffer:
    bounded_blocking:
      batch_size: 160
      buffer_size: 10240
  processor:
  - otel_traces:
      trace_flush_interval: 1
  sink:
  - opensearch:
      hosts:
      - https://vpc-opensearch-dev-nevn7hqedhhppf7rw4c674cbne.eu-west-1.es.amazonaws.com
      index_type: trace-analytics-raw
      password: REDACTED
      username: observability
  - stdout: null
  source:
    pipeline:
      name: entry-pipeline
```

Configure role:

![image](https://github.com/opensearch-project/data-prepper/assets/121832558/437a840c-958c-4b90-aaa3-5273dc120980)

Map role to user:

![image](https://github.com/opensearch-project/data-prepper/assets/121832558/3ebba6ff-8f35-49f9-9416-43aa06a44fd5)

**Expected behavior**

Data prepper starts without error, listens on the appropriate port, and writes to OpenSearch

**Screenshots**

As above.

[log gist](https://gist.github.com/arichtman-srt/2ca01c38de45776e87860f4653ef1911)

**Environment (please complete the following information):**

- AWS-managed OpenSearch: v2.9.0
- Data Prepper: v2.6.2
- AWS EKS: v1.29

**Additional context**

When I map the same user to `all_access` role, Data Prepper behaves as expected, and is able to set up the pipeline, listens on the configured port, and successfully writes to OpenSearch. If I add index permissions of `indices_all` on pattern `*`, it still doesn't work. So it's maybe cluster level index permissions?
I've set `JAVA_OPTS=-Dlog4j2.debug=true` so hopefully the logs show something useful, but not the failing API call that I can see.
