### ISSUE TITLE
S3 Thresholds are not withheld  [BUG]

### ISSUE THREAD

**Issue by tmeringenti-twilio** [opensearch-project/data-prepper#4242]
**Describe the bug**
Unable to get data prepper to follow s3 sink configured thresholds. When setting the thresholds to very low values (1 or even 0) data is still written to s3. 

**To Reproduce**
Configuration to reproduce: 
```
test-pipeline:
  workers: 2
  delay: "5000"
  source:
    kafka:
      bootstrap_servers:
        - localhost:29092
      topics:
        - name: <test-topic>
          group_id: connect-<test-topic>
      encryption:
        type: none
        insecure: true
  sink:
    - s3:
        aws:
          region: us-east-1
          sts_header_overrides:
        max_retries: 0
        threshold:
          event_count: 1
          maximum_size: 1mb
          event_collect_timeout: 15s
        bucket: <bucket name>
        object_key:
          path_prefix: testing-s3-data-loss-v2/
        codec:
          ndjson:
```

**Expected behavior**
Would like the pipeline to fail when s3 thresholds are exceeded. Or if this is not the designed behavior would appreciate clarification on what should be happening in this scenario. 

**Environment (please complete the following information):**
 - Data prepper: we are building on top of the opensource version [here](https://github.com/opensearch-project/data-prepper) pulled 2/6 

**Additional Context**
Have also tried setting `event_count`/`maximum_size` to 0 and see the same behavior.

**Comment by dlvenable** [comment]
@tmeringenti-twilio,

Thank you for reaching out to us. These threshold define when Data Prepper sends data to S3. Data Prepper buffers the outgoing data and attempts to send it all when it is needed. If you set the `maximum_size` to 128mb, then Data Prepper will write files with a size of roughly 128 MB. However, other thresholds may apply first. The `event_count` will cause Data Prepper to write events when that number are ready. And then the `event_collect_timeout` defines how long they will wait before a force write to S3.

The goal of these thresholds is not to fail, but to help the user decide when to write to S3. I hope this helps.

**Comment by dlvenable** [comment]
This is your current configuration:

```
threshold:
  event_count: 1
  maximum_size: 1mb
  event_collect_timeout: 15s
```

Data Prepper will always write S3 objects with a single event.
