### ISSUE TITLE
Tag manager processor to add and remove tags manually

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#4272]
**Is your feature request related to a problem? Please describe.**
As a user of data prepper and tags within data prepper, I would like to explicitly add or remove tags from Events with conditional expressions

**Describe the solution you'd like**
A `tag_manager` processor that can explicitly add or remove tags with conditions

```
processor:
  - tag_manager:
       add_tags: [ "tag_one", "tag_two" ]
       add_when: "/key == null"
       remove_tags: [ "tag_three", "tag_four" ]
       remove_when: "/key == null"
```

**Describe alternatives you've considered (Optional)**

**Additional context**
Originally mentioned in https://github.com/opensearch-project/data-prepper/issues/629
