### ISSUE TITLE
Support dynamically grouping Events together in the S3 sink

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#4345]
**Is your feature request related to a problem? Please describe.**
S3 Sink users would like to be able to group Events together and send them to dynamic partitions of their S3 bucket. Users would like to track different groups based on what is in the Events to group them into different S3 “folders”.

**Describe the solution you'd like**
Proposal with path_prefix and object_name

```
sink:
  - s3:
      object_key:
        path_prefix: "folder-${/partition_key}/"
        object_name: "my-object-${/some_key}";
      threshold:
        // We flush and remove groups when they reach 1000 events
        event_count: 1000
        // Alternatively, flush and remove groups on time when event_count isn't reached 
        event_collect_timeout: "30s"
```

When dynamic values are used in either the path_prefix or the object_name, we will group Events together based on the expression evaluation result. 

**Describe alternatives you've considered (Optional)**

**Additional context**
