### ISSUE TITLE
Adding compression support for DLQ events  

### ISSUE THREAD

**Issue by besha100** [opensearch-project/data-prepper#4418]
**Is your feature request related to a problem? Please describe.**
[Here](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/failures-common/src/main/java/org/opensearch/dataprepper/plugins/dlq/README.md) would be great to allow users to define compression for the objects that will be stored in S3 buckets similar to the S3 sink plugin. 

**Describe the solution you'd like**
A user could define the compression like below
```
pipeline:
  ...
  sink:
    opensearch:
      dlq:
        s3:
          bucket: "my-dlq-bucket"
          key_path_prefix: "dlq-files/"
          compression: gzip
          region: "us-west-2"
          sts_role_arn: "arn:aws:iam::123456789012:role/dlq-role"

```
**Describe alternatives you've considered (Optional)**
N/A

**Additional context**
N/A
