### ISSUE TITLE
Deprecate pipeline_configurations with extension in pipeline.yaml

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/data-prepper#4427]
**Is your feature request related to a problem? Please describe.**
The naming pipeline_configurations within pipeline.yaml can cause confusion with actual pipeline definition.
```
pipeline_configurations:
    aws:
        secrets:
            qchea-test-secret:
                secret_id: "kafka-secrets"
                region: "us-west-2"
                sts_role_arn: "arn:aws:iam::xxxxxxx:role/os-os-test-role"
            schema-secret:
                secret_id: "self-managed-kafka-schema"
                region: "us-west-2"
                sts_role_arn: "arn:aws:iam::xxxxx:role/os-os-test-role"
kafka-pipeline:
  source:
    kafka:
      encryption:
        type: "none"
      topics:
      - name: "quickstart-events"
        group_id: "groupdID1"
      bootstrap_servers:
      - "10.125.24.235:9092"
      authentication:
        sasl:
          plaintext:
            username: "${{aws_secrets:qchea-test-secret:username}}"
            password: "${{aws_secrets:qchea-test-secret:password}}"
      schema:
        type: confluent
        registry_url: https://psrc-m5k9x.us-west-2.aws.confluent.cloud
        version: 1
        schema_registry_api_key: "${{aws_secrets:schema-secret:schema_registry_api_key}}"
        schema_registry_api_secret: "${{aws_secrets:schema-secret:schema_registry_api_secret}}"
        basic_auth_credentials_source: USER_INFO
```
**Describe the solution you'd like**
rename it into extension
```
extension:
    aws:
        secrets:
            qchea-test-secret:
                secret_id: "kafka-secrets"
                region: "us-west-2"
                sts_role_arn: "arn:aws:iam::xxxxxxxxx:role/os-os-test-role"
            schema-secret:
                secret_id: "self-managed-kafka-schema"
                region: "us-west-2"
                sts_role_arn: "arn:aws:iam::xxxxxxxxx:role/os-os-test-role"
kafka-pipeline:
  source:
    kafka:
      encryption:
        type: "none"
      topics:
      - name: "quickstart-events"
        group_id: "groupdID1"
      bootstrap_servers:
      - "10.125.24.235:9092"
      authentication:
        sasl:
          plaintext:
            username: "${{aws_secrets:qchea-test-secret:username}}"
            password: "${{aws_secrets:qchea-test-secret:password}}"
      schema:
        type: confluent
        registry_url: https://psrc-m5k9x.us-west-2.aws.confluent.cloud
        version: 1
        schema_registry_api_key: "${{aws_secrets:schema-secret:schema_registry_api_key}}"
        schema_registry_api_secret: "${{aws_secrets:schema-secret:schema_registry_api_secret}}"
        basic_auth_credentials_source: USER_INFO
```
**Describe alternatives you've considered (Optional)**

**Additional context**
