### ISSUE TITLE
Support default route option for Events that match no other route

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#4615]
**Is your feature request related to a problem? Please describe.**
As a user of data prepper, I would like to be able to configure a default route for when my Events do not match any of my other routes. Currently, I would have to add an expression manually to handle this case.

**Describe the solution you'd like**
An option to use a custom route value to use as the default. Routes with a value of `default` or `DEFAULT` will be this default route

```
routes:
  - ROUTE_ONE: '/my_key == null`
  - DEFAULT_ROUTE: default
sink:
 - opensearch:
      routes:
         - ROUTE_ONE
  - opensearch:
       routes:
          - DEFAULT_ROUTE
```

**Describe alternatives you've considered (Optional)**

**Additional context**

**Comment by dlvenable** [comment]
Could this make sense? Have a special pre-defined route named `_default` or just `default`

```
routes:
  - ROUTE_ONE: '/my_key == null`
sink:
 - opensearch:
      routes:
         - ROUTE_ONE
  - opensearch:
       routes:
          - _default
```


The `routes` list is a list of expressions. But, `default` isn't an expression, so it would not fit with the current definition of what these are.
