### ISSUE TITLE
Secure the HTTP input plugin with HTTP Basic Authentication

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#464]
**Is your feature request related to a problem? Please describe.**

Data Prepper's HTTP endpoint is currently unsecured. Thus, users must either add a proxy on the host, or leave them open to network access.

**Describe the solution you'd like**

Support HTTP Basic Authentication on the HTTP input endpoint. Additionally, we will turn this on by default with a preconfigured username and password. Users will be able to turn off the HTTP security.

**Additional context**

This is related to #314 and #312

**Comment by dlvenable** [comment]
My previous configuration was somewhat different from a normal plugin in Data Prepper as they are now.

I believe it would end up looking like:
```
http:
  port: 8000
  authentication:
    http_basic:
      username: admin
      password: admin
```

This would be more consistent with the existing plugins as used in sink, source, prepper.
