### ISSUE TITLE
Jira Connector - to seamlessly sync all the ticket details to OpenSearch

### ISSUE THREAD

**Issue by san81** [opensearch-project/data-prepper#4754]
**Is your feature request related to a problem? Please describe.**

As a customer, I would like to move all my Jira ticket details to OpenSearch to use advanced search capabilities like full-text and vector search on the jira ticketing content without writing any integration code. The connector brings all ticketing system data with a simple configuration in the pipeline yaml. The connector also takes care of synchronizing the data between my Jira Cloud instance and OpenSearch instance in near real-time. 

**Describe the solution you'd like**

Introducing a new source plugin for Jira that takes jira login credentials. The connector makes use of Jira APIs to fetch all the ticket details and converts them to OpenSearch event stream that gets processed with in the OpenSearch context. Rest of the OpenSearch processors and sink options should work as they are.

```
simple-jira-pipeline:
  aws:
    secrets:
        secret1:
            secret_id: "<<jira-login-credentials>>"
            region: "<<us-east-1>>"
            refresh_interval: PT1H
jira-pipeline:
  source:
    jira:
      host: https://<client-subdomain>.atlassian.net
      authentication-type: "api-key"
      user_name: "${{aws_secrets:secret:email}}" 
      api_token: "${{aws_secrets:secret:api_token}}"
      entity_types: [project, user, issues, comments]
  processor:
  sink:
    - opensearch:
   ```

For synchronizing the data changes between the Jira Cloud instance and OpenSearch, the connector also registers a webhook to get notified when there is a change and extracts the new version of those tickets and triggers the data prepper flow for those events related to ticket modifications.

**Additional context**

Webhook registring with Jira Cloud should be using a secret enabled so that the content pushed over the registered endpoint is signed and secured
