### ISSUE TITLE
Use `join` inside a format expression

### ISSUE THREAD

**Issue by miguel-vila** [opensearch-project/data-prepper#4768]
Not sure if this is a bug or something that is not supported.

I defined an `add_entries` processor in order to build a `passage_text_elements` that will later be joined, and one of the entries defines a format expression that uses `join`:

```yaml
...
- key: passage_text_elements
  append_if_key_exists: true
  add_when: >-
    /episode != null and /episode/name != null
  format: 'name: ${/episode/name}'
...
- key: passage_text_elements
  append_if_key_exists: true
  add_when: >-
    /episode != null and /episode/guests != null
  format: 'guests: ${join(/episode/guests)}'
...
- key: passage_text
  value_expression: join("\n", /passage_text_elements)
```

This is evaluating those to null and appending those:

```json

"passage_text_elements": [
            "Content type: episode-video", // this is ok
            "name: <name>", // this is ok
            "description: <description>", // this is ok
            null // this should have been "guests: <guest1,guest2>"
          ]

```

is it possible to use `join` in a format expression? My idea for a workaround is to do this in two steps (an entry with `value_expression: join(/episode/guests)` setting a `guests_joined` field and then another entry with `format: "guests: ${/guests_joined}"`).
