### ISSUE TITLE
Add sinks under extensions

### ISSUE THREAD

**Issue by kkondaka** [opensearch-project/data-prepper#4799]
**Is your feature request related to a problem? Please describe.**
Add sinks under extensions so that it can be used as a sink for pipeline DLQ, or as a sink for Live Debug Event capture or to reduce duplicate information if the same sink is used multiple times (Customers finding it unnecessary to add the same sink configuration when multiple sub-pipelines are used in the configuration).

**Describe the solution you'd like**
Allow sink configuration like the following under `extensions` section

```
extensions:
   sinks:
     opensearch-sink1:
        hosts: [ <OPENSEARCH-ENDPOINT> ]
        aws:
            region: "<region>"
            sts_role_arn: "<ARN>"
       index: <index1>

pipeline:
   source:
   processor:
   sink:
      - opensearch:
          use: opensearch-sink1
          route:
              - route1
          
      - pipeline:
           name: pipeline2
           route:
                - route2
pipeline2:
   source:
          ...
  processor:
  sink:
     - opensearch:
            use: opensearch-sink1
            index: <index2>.  # override some config as needed
```

Using dynamic sink as pipeline DLQ or live debug capture sink

```
extensions:
   sinks:
     s3-sink1:
         bucket: <bucket>
        object_key:
          path_prefix: pfx
        threshold:
          event_collect_timeout: 5s
          event_count: 10
        aws:
          region: "<region>"
          sts_role_arn: "<arn>"
  dlq:   # This is RESERVED name
      s3:
         use: s3-sink1

live_capture: # This is RESERVED name
     s3:
          use: s3-sink1

```

**Describe alternatives you've considered (Optional)**
key words used in the above proposal like "sinks" and "use" can be different or more appropriate names may be used.

**Additional context**
