### ISSUE TITLE
Personalize as Sink

### ISSUE THREAD

**Issue by ivan-tse** [opensearch-project/data-prepper#4804]
**Is your feature request related to a problem? Please describe.**
Enable users to send events to Amazon Personalize

**Describe the solution you'd like**
Create a new sink in Data Prepper which sends data to Amazon Personalize. It should support

- End-to-end acknowledgements
- Retries
- Metrics
- DLQ
- Ingestion into Personalize datasets (items, users, interactions)

Sample YAML for items dataset:
```
pipeline:
  ...
  sink:
    - personalize:
        aws:
          region: us-west-2
          sts_role_arn: arn:aws:iam::123456789012:role/Data-Prepper
        max_retries: 5
        dataset_type: items
        dataset_arn: arn:aws:personalize:us-west-2:123456789012:dataset/dataset-name
```
Sample YAML for users dataset:
```
pipeline:
  ...
  sink:
    - personalize:
        aws:
          region: us-west-2
          sts_role_arn: arn:aws:iam::123456789012:role/Data-Prepper
        max_retries: 5
        dataset_type: users
        dataset_arn: arn:aws:personalize:us-west-2:123456789012:dataset/dataset-name
```
Sample YAML for interactions dataset:
```
pipeline:
  ...
  sink:
    - personalize:
        aws:
          region: us-west-2
          sts_role_arn: arn:aws:iam::123456789012:role/Data-Prepper
        max_retries: 5
        dataset_type: interactions
        tracking_id: 1234567890
```
**Additional context**
