### ISSUE TITLE
Support s3 scan for bucket across regions

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/data-prepper#4811]
**Is your feature request related to a problem? Please describe.**
Current s3 scan does not support bucket cross regions with iam credential:

```
version: "2"
log-pipeline:
  source:
    s3:
      codec:
        newline: # Other options "json", "csv", "parquet"
      compression: "none"
      aws:
        region: "us-east-1"
        sts_role_arn: "arn:aws:iam::253613578708:role/FullAccess"
      scan:
        buckets:
          - bucket:
              name: "test-s3-gd-bucket" # bucket in us-west-2
```

**Describe the solution you'd like**
user should be allowed to configure region for each bucket in the buckets list.

**Describe alternatives you've considered (Optional)**

**Additional context**
