### ISSUE TITLE
Allow pipeline configuration files to reference and utilize environment variables

### ISSUE THREAD

**Issue by dangube4ever** [opensearch-project/data-prepper#4813]
**Is your feature request related to a problem? Please describe.**
I'd like the ability to leverage environment variable references within the pipeline configuration file. This would allow me to set values that need to be configurable during deployment or runtime.

**Describe the solution you'd like**
* Example of desired sink configuration

```
  sink:
  - s3:
      aws:
        region: ${AWS_REGION}
      bucket: ${SINK_BUCKET}
      buffer_type: in_memory
   ...
```

* Example of source configuration

```
  source:
    s3:
      aws:
        region: ${AWS_REGION}
      codec:
        ndjson: null
      compression: gzip
      default_bucket_owner: ${AWS_ACCOUNT}
      notification_type: sqs
      sqs:
        queue_url: ${QUEUE_URL}
        visibility_duplication_protection: true
        visibility_timeout: 900s
```

In the examples provided, AWS_REGION, SINK_BUCKET, AWS_ACCOUNT, and QUEUE_URL would all be represented as environment variables.
