### ISSUE TITLE
[BUG] Unable to parse date time using defined patterns in Date Processor

### ISSUE THREAD

**Issue by sb2k16** [opensearch-project/data-prepper#4815]
Date Processor in Data Prepper is unable to parse the date time given the below patterns defined in the pipeline YAML configuration. 

Consider, `testMessage.log` has a line ```{"message": "Jul 30, 2024 3:28:55 PM"}```, data prepper is unable to inject the `@timestamp` in the output event after parsing the date time from `message` key. 

It looks like if we remove the line to default parsing for hour `parseDefaulting(ChronoField.HOUR_OF_DAY, 0)` from [here](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/date-processor/src/main/java/org/opensearch/dataprepper/plugins/processor/date/DateProcessor.java#L129), it is matching the expected behavior.

```
version: "2"
test-pipeline:
  source:
    file:
      path: "./testLog.log"
      format: "json"
      record_type: "event"
  processor:
    - date:
        match:
          - key: "message"
            patterns: ["MMM dd, yyyy HH:mm:ss a", 
            "MMM dd, yyyy H:mm:ss a", "MMM dd, yyyy hh:mm:ss a", "MMM dd, yyyy h:mm:ss a", "MMM d, yyyy h:mm:ss a" ]
        destination: "@timestamp"
        destination_timezone: "UTC"
        to_origination_metadata: true
  sink:
    - stdout:
  ```
