### ISSUE TITLE
[BUG] Expression tries to evaluate something as a string when it should evaluate it as an object

### ISSUE THREAD

**Issue by miguel-vila** [opensearch-project/data-prepper#4859]
I'm describing a `adds_entries` processor. One of the entries refers to a nested field (`/channel/name`). I want to append that value to a new `passage_text_elements` array, which is initialized with some string. The relevant code looks like this:

```yaml
  processor:
    - add_entries:
        entries:
          - key: passage_text_elements
            format: 'Content type: ${/type}'
          ...
          - key: passage_text_elements
            append_if_key_exists: true
            add_when: >-
              /channel/name != null and (/type ==
              "channel-linear" or /type == "channel-xtra")
            format: 'name: ${/channel/name}'
          - key: passage_text
            value_expression: |-
              join("

              ", /passage_text_elements)
            add_when: /passage_text_elements typeof array
```

when something like this is ingested (from dynamodb):

```json
{
  "channel": {
    "M": {
      "name": {
        "S": "some name"
      },
      ...
    }
  },
  ...
  "type": {
    "S": "channel-linear"
  }
}
```

I see this warning/error in the ingestor logs:

```
WARN  org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink - Document failed to write to OpenSearch with error code 400. Configure a DLQ to save failed documents. Error: failed to parse field [channel] of type [text] in document with id '<doc-id>'. Preview of field's value: '{name = some name, ...}' caused by Can't get text on a START_OBJECT at 1:127
```

so it seems that somewhere, the path `channel` is being interpreted as a string, as opposed to an object. The only entry that uses the channel field is the one I included above.

**To Reproduce**
1. create an add_entries processor similar to the described above
2. insert a document on the source side that has a `channel` object field with a `name` string field.

**Expected behavior**
Expecting for the formatted string `"name: <channel.name>"` to be appended to the `passage_text_elements` field

**Environment (please complete the following information):**
 - Version: 2.11
