### ISSUE TITLE
`Sources` documentation should add `pipeline` subdocumentation

### ISSUE THREAD

**Issue by linghengqian** [opensearch-project/data-prepper#4922]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. It would be nice to have [...]

**Describe the solution you'd like**
- `Sources` documentation should add `pipeline` subdocumentation.
- ![image](https://github.com/user-attachments/assets/6aab050e-7dc4-43ab-a399-b73ec958c80a)
- The document content should be similar to https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sinks/pipeline/ 
.
- ![image](https://github.com/user-attachments/assets/ee701e56-cc64-4aef-8cc6-86033e7ce212)
- Adding subdocuments to `Source` makes sense because the following usages are 100% likely to exist.
```yaml
entry-pipeline:
  source:
    otel_trace_source:
      ssl: "false"
  sink:
    - pipeline:
        name: raw-pipeline
raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: [ "https://node-0.example.com:9200" ]
        cert: "/usr/share/opensearch-test/root-ca.pem"
        username: "admin"
        password: "opensearchNode1Test"
        index_type: trace-analytics-raw
```

**Describe alternatives you've considered (Optional)**

**Additional context**
- Null.
