### ISSUE TITLE
[BUG?] data-prepper sink fails to create templates when `number_of_shards` is passed

### ISSUE THREAD

**Issue by egarbi** [opensearch-project/data-prepper#4960]
**Describe the bug**
I have data-prepper creating templates and sending data with no issue
This is the config
```
          sink:
            - opensearch:
                hosts: ["$${OS_HOST}"]
                username: $${OS_USER}
                password: $${OS_PASS}
                index_type: trace-analytics-raw
                template_type: index-template
                max_retries: 10
```
My cluster sets the `number of shards=5` as the default value for new indices being rolled over.
So, I tried adding an extra line to change that settings as stated [here in the docs](https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sinks/opensearch/#configuration-options)
```
number_of_shards: 1
```
But as soon I restart the service it starts to fail with the following error
```
Request failed: [x_content_parse_exception] [1:1118] [index_template] unknown field [settings]
```
**To Reproduce**
1. Set a sink to use OpenSearch as shown above using `number_of_shards: N`
2. Restart the service

**Expected behavior**
Templates should be created using the right sharding number.

**Environment (please complete the following information):**
 - Amazon OpenSearch service
 - Version [2.11]
