### ISSUE TITLE
[BUG] rename_keys processor: json pointers with escaped syntax fail to validate

### ISSUE THREAD

**Issue by joelmarty** [opensearch-project/data-prepper#5121]
**Describe the bug**
The [escaped syntax](https://opensearch.org/docs/latest/data-prepper/pipelines/expression-syntax/#escaped-syntax) for json pointers define how to build json pointers for fields that include special characters.

However, the [`isValidKey()`](https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-api/src/main/java/org/opensearch/dataprepper/model/event/JacksonEventKey.java#L151) method in `JacksonEventKey` only checks the basic character set and key defined using the escaped syntax is rejected.

**To Reproduce**
1. Create a pipeline with a `rename_keys` processor using an escaped syntax:
```yaml
my-file-pipeline:
  source:
    file:
      path: run/data/events.jsonl
      record_type: event
      format: json
  sink:
    - file:
        path: "run/data/result.jsonl"
  processor:
    - rename_keys:
        entries:
          - from_key: host
             to_key: '"cs(host)"'
```
2. Run data-prepper
3. data-prepper cannot start with the error:
> 2024-10-28T16:35:39,367 [main] ERROR org.opensearch.dataprepper.core.validation.LoggingPluginErrorsHandler - 1. rp-pipeline-file.processor.rename_keys: caused by: Parameter "entries.null.to_key" for plugin "rename_keys" is invalid: key "cs(host)" must contain only alphanumeric chars with .-_@/ and must follow JsonPointer (ie. 'field/to/key')

**Expected behavior**
The `to_key` argument `"cs(host)"` should be accepted as it conforms to the documented syntax.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: macOs
 - Version 14.5

**Additional context**
N/A
