### ISSUE TITLE
getKeys and getValues function for map type

### ISSUE THREAD

**Issue by RashmiRam** [opensearch-project/data-prepper#5210]
**Is your feature request related to a problem? Please describe.**
I have a nested json that contains **attributes** field of type map. I want to transform that map into keys and values array.  
ex., 

```
{
   "attributes":{
        "field1":"value1",
        "field2":"value2"
    }
}

```
can be processed and below values can be extracted from it

```
   "keys":["field1","field2"]
   "values":["value1","value2"]
```

**Describe the solution you'd like**
Expose getKeys and getValues function in Expression 

**Describe alternatives you've considered (Optional)**
No alternatives found.

**Additional context**

**Comment by oeyh** [comment]
This processor combination can achieve the above transformation:
```yaml
  processor:
    - map_to_list:
        source: "attributes"
        target: "attributes-list"
        key_name: "keys"
        value_name: "values"
    - list_to_map:
        source: "attributes-list"
        use_source_key: true
        extract_value: true
```

`map_to_list` generates a list of objects separating keys and values:
```json
{
  "attributes-list": [
    {
      "keys": "field1",
      "values": "value1"
    },
    {
      "keys": "field2",
      "values": "value2"
    }
  ]
}
```
then `list_to_map` gets you keys and values in a map:
```json
{
    "keys":["field1","field2"], 
   "values":["value1","value2"]
}
```

References on these two processors:
https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/map-to-list/
https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/list-to-map/
