### ISSUE TITLE
[RFC] Basic Conditional Logic in Preppers

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#522]
Data Prepper currently does not provide any control logic within pipelines. This proposal is to add a basic conditional system for processing data in Preppers only when certain conditions are met.

This proposal is to add a new `when` field which is available for all Processors.

When a Prepper contains the `when` field, the condition expressed in the value must be true for the Prepper to process a given event. If the field is not provided, then all events are processed.

The conditional expression should support:
* Equality operators: `==`, `>`, `<`, `>=`, `<=`
* Boolean operators: `and`, `or`, and `not`
* Set operators: `in`, and `not in`
* Regex operators: `=~` and `!~` which check a pattern on the right against the string on the left
* Fields will be accessed using JsonPointer as defined in #450 
* Sets defined by `[]` and comma delimited

Thus, an example might be:

```
preppers:
  ...
  - grok:
       when: "/http/response/status_code and /http/response/status_code >= 400 and /http/response/status_code < 500"
       match: "..."
  - grok:
       when: "/http/response/status_code in [500, 501]"
       match: "..."
```

### Implementation

The `AbstractPrepper` class can support the `when` behavior so that individual Prepper implementations do not need to handle the `when` field.

This will require that `AbstractPrepper` receive `Event` types and not any type. This is ongoing work in #319. Making this change in `AbstractPrepper` is a breaking change though since it does not require the `Event` type currently.

The `AbstractPrepper` will only call `doExecute` for records which meet the conditional expression provided by `when`.

**Comment by ryn9** [comment]
The given example seems to indicate that all preppers would be iterated through and each where cause evaluated. Would there be a way to short circuit the rest of the preppers in the event a 'when' clause is met? Though would allow for a more conventual if-then-else style evaluation.

**Comment by dlvenable** [comment]
@ryn9, Thanks for the feedback. This proposal does not include conditionals any more complicated than skipping a single Prepper/Processor.

Would the current proposal be of value to you? Do you need something more like if-then-else? My thinking is that both could  exist. The proposed `when` approach may yield clear and compact pipelines when it is sufficient. But, an if-then-else could be available to use when it is needed.

**Comment by ryn9** [comment]
So long as if-then-else is coming - sounds good to me :)

**Comment by sbayer55** [comment]
Two possible alternatives that allow branching logic to be represented with nested components.

1. Data Prepper could leverage the option to chain multiple pipelines to represent branching logic. Adding a new sink named "conditional" that contains an array of `{if: "condition", sink: [sink1, sink2]}`. Each subsiquent pipeline would need to handle a branch in contorl flow.

```start-pipeline:
  source:
    ...
  sink:
    - conditional:
      - if: "/http/response/status_code and /http/response/status_code >= 400 and /http/response/status_code < 500"
        sink:
          - pipeline:
              name: "pipeline-a"
    - conditional:
      - if: false
        sink: []
      - if: /http/response/status_code in [500, 501, 502]
        sink:
          - pipeline:
              name: "pipeline-b"
      - if: true # effectivly else
        sink:
          - pipeline:
              name: "pipeline-a"
          - pipeline:
              name: "pipeline-b"
pipeline-a:
  source:
    pipeline:
      name: "start-pipeline"
  sink:
    ...

pipeline-b:
  source:
    pipeline:
      name: "start-pipeline"
  sink:
    ...```

Another option with a less verbose syntax could be to create a conditional processor. The conditional processor would need to support nested processors. Branching processor logic is cleaner but directing events to different sinks based on conditionals requires a more complex syntax.

```start-pipeline:
  source:
    ...
  processor:
    - conditional:
      - if: "/http/response/status_code and /http/response/status_code >= 400 and /http/response/status_code < 500"
        processor:
          - grok:
            ...
          - another-processor:
            ...
      - if: "/http/response/status_code in [500, 501, 502]"
        processor:
          ...
      - if: true # effectivly else
        processor:
          ...
  sink:
    - file:
      ...```

**Comment by dlvenable** [comment]
Thanks @sbayer55 for putting that together. I have a similar concept, but it uses a `conditional_routing` Processor.

Basically, this one Processor could route into other processors depending upon the condition. This wouldn't really require any changes to Data Prepper Core either.

```
my_pipeline:
  source:
    pipeline:
      name: VAR_PIPELINE_NAME
  processor:
    - mutate:
    - conditional_routing:
        - '/http/response/status_code = 500'
            - conditional_routing:
                - '/http/response_body ~= FAILURE1'
                  - mutate:
                     ....
              - '/http/response_body ~= FAILURE2'
                 - mutate:
                    ....
                - otherwise:
                  - mutate:
```

We've had some concerns about this type of approach though because it could cause problems with a distributed Data Prepper cluster.

I think we should move forward on the `when` approach to get a feature out in 1.3 and at the same time start an RFC for different approaches to the branching condtionals.
