### ISSUE TITLE
OpenSearch sink not rolling over the index after upgrading from 2.7 to 2.10

### ISSUE THREAD

**Issue by dmossakowski** [opensearch-project/data-prepper#5258]
Since migrating from 2.7.0 to 2.10.1 the index id stayed at the same number (000056) and is no longer rolling over. You can see below that previously indexes would be rolled around 500mb but this latest one is now at 108.5gb. Number of documents used to be around 300000 but now it's more than 73 million.  Did I miss some configuration?

```
  | otel-v1-apm-span-000056 | green | Yes | open | 108.5gb | 54.1gb | 73591140 | 4806948 | 1 | 1
  | otel-v1-apm-span-000055 | green | Yes | open | 471mb | 235.5mb | 231704 | 24212 | 1 | 1
  | otel-v1-apm-span-000054 | green | Yes | open | 478.3mb | 239.1mb | 299849 | 20501 | 1 | 1
  | otel-v1-apm-span-000053 | green | Yes | open | 504mb | 252mb | 310190 | 26766 |  
..
```

Data prepper config:
```
raw-pipeline:
  workers: 2
  delay: "3000"
  source:
    pipeline:
      name: "otel-trace-pipeline"
  buffer:
    bounded_blocking:
      buffer_size: 10240
      batch_size: 160
  processor:
    - delete_entries:
        with_keys: ['command_args']
    - otel_traces:
    - otel_trace_group:
        hosts: ["https://opensearch-node1:9200"]
        username: admin
        password: ------
        insecure: true
  sink:
    - opensearch:
        hosts: ["https://opensearch-node1:9200"]
        index_type: trace-analytics-raw
        username: admin
        password: --------
        insecure: true
```
