### ISSUE TITLE
Support loading encryption keys from an S3 bucket

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#5336]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to get encrypted data keys from an S3 bucket. I want to list the objects in the bucket and then have them all available for encryption. However, I'd like to use the latest one by default.

**Describe the solution you'd like**

I'd like to build off of #5335 and support this as part of an encryption engine feature.

```
encryption:
   encryption_key_directory: s3://my-bucket/path/to/
```

**Describe alternatives you've considered (Optional)**

This could be moved to be controlled under the `kafka` buffer, but I'd rather do this in the proposed extension.

```
buffer:
  kafka:
    topics:
    - name: topicname
      encryption_key_directory: s3://data-plane-bucket/accountId/pipelineName/internalPipelineId/
```

**Additional context**

N/A
