### ISSUE TITLE
Missing trace group for SpanId [BUG]

### ISSUE THREAD

**Issue by arnitolog** [opensearch-project/data-prepper#534]
**Describe the bug**
I have an application that sends traces to opentelemtry collector. Traces collected by java instrumentation library: https://github.com/open-telemetry/opentelemetry-java-instrumentation And then collector send this data to data-prepper.
It also sends the same data to Jaeger system.

And for all these traces I see below errors in data-prepper service:
```
{"timeMillis":1635957998134,"thread":"raw-pipeline-prepper-worker-5-thread-1","level":"WARN","loggerName":"com.amazon.dataprepper.plugins.prepper.oteltrace.OTelTraceRawPrepper","message":"Missing trace group for SpanId: 12c47c820fb56ca3","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":26,"threadPriority":5}
{"timeMillis":1635957998134,"thread":"raw-pipeline-prepper-worker-5-thread-1","level":"WARN","loggerName":"com.amazon.dataprepper.plugins.prepper.oteltrace.OTelTraceRawPrepper","message":"Missing trace group for SpanId: 6165987d239ae041","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":26,"threadPriority":5}
```

At the same in Jaeger these traces works as expected.

Here is my data-prepper pipeline:
```
    entry-pipeline:
      delay: "100"
      source:
        otel_trace_source:
          ssl: false
      prepper:
        - peer_forwarder:
            discovery_mode: "dns"
            domain_name: "data-prepper-headless"
            ssl: false
      buffer:
        bounded_blocking:
          buffer_size: 1024 # max number of records the buffer accepts
          batch_size: 256 # max number of records the buffer drains after each read
      sink:
        - pipeline:
            name: "raw-pipeline"
        - pipeline:
            name: "service-map-pipeline"
    raw-pipeline:
      source:
        pipeline:
          name: "entry-pipeline"
      prepper:
        - otel_trace_raw_prepper:
      sink:
        - opensearch:
            hosts: [ "https://logging-cluster-alfa-os.es.svc.cluster.local:9200" ]
            insecure: true
            username: "data-prepper"
            password: "xxxxxxxxxxxxx"
            trace_analytics_raw: true
    service-map-pipeline:
      delay: "100"
      source:
        pipeline:
          name: "entry-pipeline"
      prepper:
        - service_map_stateful:
      sink:
        - opensearch:
            hosts: ["https://logging-cluster-alfa-os.es.svc.cluster.local:9200"]
            insecure: true
            username: "data-prepper"
            password: "xxxxxxxxxxxxx"
            trace_analytics_service_map: true
```

and OTEL collector pipeline:

````
config:
  extensions:
    health_check: {}
  processors:
    batch/traces:
      send_batch_size: 50
      timeout: 1s
    memory_limiter: null
  receivers:
    otlp:
      protocols:
        grpc:
        http:
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_http:
          endpoint: 0.0.0.0:14268
    zipkin:
      endpoint: 0.0.0.0:9411
  exporters:
    otlp/data-prepper:
      endpoint: data-prepper.es.svc.cluster.local:21890
      tls:
        insecure: true

  service:
    extensions:
      - health_check
    pipelines:
      traces:
        receivers: [otlp,jaeger,zipkin]
        processors: [batch/traces]
        exporters: [otlp/data-prepper]
    telemetry:
      logs:
        level: "warn"
````

**Comment by arnitolog** [comment]
just checked another application, that uses jaeger client library, but not java auto instrumentation lib. And it works fine. It looks like there is an issue only when this lib is used. But on the other hand, it is very useful library, so it will be good to have an ability to use it along with Data-prepper and Tracing analysis plugin

**Comment by chenqi0805** [comment]
@arnitolog Thanks for your interest in data-prepper trace-analytics. Looking at your description:

> And for all these traces I see below errors in data-prepper service:

Could you check 

1. If there is raw span documents successfully ingested into opensearch backend?
2. If yes, then in the raw span docs, could you check the value for the key `serviceName`?
3. If the value turns out to be null, which I think is likely to be the case. Then could you post a sample span for our further investigation? If not, then I suggest you try chaining [`otel_trace_group_prepper`](https://github.com/opensearch-project/data-prepper/tree/main/data-prepper-plugins/otel-trace-group-prepper) after the otel_trace_raw_prepper to see if it mitigates the issue.

FYI, our otel_trace_raw_prepper did stateful processing in populating the key `traceGroup`. For particular traceId, root span reads it from the span's `serviceName` while child span reads it from the root span's traceGroup/serviceName. But if the child span waits for root span's arrival longer than `trace_flush_interval`(by default 180s), they will be flushed even without the traceGroup populated. Thus the warning message you see: https://github.com/opensearch-project/data-prepper/blob/c8982fd6ec10a5ffd564d16b38ebb99f192a9e40/data-prepper-plugins/otel-trace-raw-prepper/src/main/java/com/amazon/dataprepper/plugins/prepper/oteltrace/OTelTraceRawPrepper.java#L257

**Comment by arnitolog** [comment]
thanks a lot @chenqi0805 , I will try to go through the suggested steps and let you know.

**Comment by arnitolog** [comment]
Hello @chenqi0805 
I've checked the raw span index in I do see service name in the docs. I've also checked otel-v1-apm-service-map index, and there I can't find that serviceName. Probably this is also the reason why this serviceName is not shown on the Services page. Could you please suggest on this
I've also added `otel_trace_raw_prepper` as you suggested. But now I'm seen the following errors:

```
{"timeMillis":1636372847335,"thread":"raw-pipeline-prepper-worker-5-thread-1","level":"WARN","loggerName":"com.amazon.dataprepper.plugins.prepper.oteltracegroup.OTelTraceGroupPrepper","message":"Failed to find traceGroup for spanId: 726be7ea87243741 due to traceGroup missing for traceId: 00000000000000003b13b048c35ed293","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":27,"threadPriority":5}
{"timeMillis":1636372847336,"thread":"raw-pipeline-prepper-worker-5-thread-1","level":"WARN","loggerName":"com.amazon.dataprepper.plugins.prepper.oteltracegroup.OTelTraceGroupPrepper","message":"Failed to find traceGroup for spanId: 0d6a2527e0e83e5a due to traceGroup missing for traceId: 00000000000000003b13b048c35ed293","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":27,"threadPriority":5}
```

**Comment by arnitolog** [comment]
@chenqi0805 here what I have:
this is span in `jaeger_json` in Kafka topic format. in real-life all traces are sent in otlp format:
```
{"traceId":"K8RYddJipXn/CNOr1i30wA==","spanId":"qParQWQRO5g=","operationName":"EndpointMvcAdapter.invoke","references":[{"traceId":"K8RYddJipXn/CNOr1i30wA==","spanId":"Ro8/bkduzzk="}],"startTime":"2021-11-08T15:19:18.011249650Z","duration":"0.003748165s","tags":[{"key":"otel.library.name","vStr":"io.opentelemetry.spring-webmvc-3.1"},{"key":"otel.library.version","vStr":"1.7.1"},{"key":"thread.name","vStr":"https-jsse-nio-8080-exec-8"},{"key":"thread.id","vType":"INT64","vInt64":"71"},{"key":"span.kind","vStr":"internal"},{"key":"otel.status_code","vType":"INT64"}],"process":{"serviceName":"platform-test","tags":[{"key":"container.id","vStr":"bdeabf673ef79ceefec2d562629632211b9e54015a9bd20c792d753b14a6bf61"},{"key":"host.arch","vStr":"amd64"},{"key":"host.name","vStr":"ip-10-0-57-215.ec2.internal"},{"key":"os.description","vStr":"Linux 4.9.0-13-amd64"},{"key":"os.type","vStr":"linux"},{"key":"process.command_line","vStr":"/usr/lib/jvm/java-1.8-openjdk/jre:bin:java -javaagent:opentelemetry-javaagent.jar -Dotel.traces.exporter=otlp -Dotel.exporter.otlp.traces.endpoint=http://otlp-collector.otlp.svc.cluster.local:4317 -Dotel.exporter.otlp.metrics.endpoint=http://otlp-collector.otlp.svc.cluster.local:4317 -Dotel.resource.attributes=service.name=platform-test -Dotel.service.name=platform-test -Dotel.javaagent.debug=true -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:MetaspaceSize=160m -XX:+UseStringDeduplication -XX:+ExitOnOutOfMemoryError -Xms1024m -Xmx1024m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -XX:CICompilerCount=2"},{"key":"process.executable.path","vStr":"/usr/lib/jvm/java-1.8-openjdk/jre:bin:java"},{"key":"process.pid","vType":"INT64","vInt64":"136"},{"key":"process.runtime.description","vStr":"IcedTea OpenJDK 64-Bit Server VM 25.242-b08"},{"key":"process.runtime.name","vStr":"OpenJDK Runtime Environment"},{"key":"process.runtime.version","vStr":"1.8.0_242-b08"},{"key":"telemetry.auto.version","vStr":"1.7.1"},{"key":"telemetry.sdk.language","vStr":"java"},{"key":"telemetry.sdk.name","vStr":"opentelemetry"},{"key":"telemetry.sdk.version","vStr":"1.7.0"},{"key":"cloud.provider","vStr":"aws"},{"key":"cloud.platform","vStr":"aws_eks"},{"key":"cloud.region","vStr":"us-east-1"},{"key":"cloud.availability_zone","vStr":"us-east-1a"},{"key":"host.type","vStr":"m5.2xlarge"},{"key":"k8s.pod.ip","vStr":"100.99.194.14"},{"key":"k8s.pod.name","vStr":"platform-test-bravo-5f8fbc497d-5cwjk"},{"key":"k8s.namespace.name","vStr":"pr7"},{"key":"k8s.deployment.name","vStr":"platform-test-bravo"},{"key":"k8s.node.name","vStr":"ip-10-0-78-169.ec2.internal"}]}}
```
here is a document from the same service (but not the same traceID) in the `otel-v1-apm-span-*` index:
```
{"_index":"otel-v1-apm-span-000002","_type":"_doc","_id":"1e3bf2c399bdd06e","_version":1,"_score":null,"_source":{"traceId":"97799147cf24f8d91593b96f9ef31052","spanId":"1e3bf2c399bdd06e","traceState":"","parentSpanId":"f6ad9246119e795c","name":"EndpointMvcAdapter.invoke","kind":"SPAN_KIND_INTERNAL","startTime":"2021-11-08T16:17:48.009644775Z","endTime":"2021-11-08T16:17:48.012132857Z","durationInNanos":2488082,"serviceName":"platform-test","events":[],"links":[],"droppedAttributesCount":0,"droppedEventsCount":0,"droppedLinksCount":0,"traceGroup":"/health","traceGroupFields.endTime":"2021-11-08T16:17:48.012570043Z","traceGroupFields.statusCode":0,"traceGroupFields.durationInNanos":3570043,"resource.attributes.k8s@namespace@name":"pr7","span.attributes.thread@id":64,"resource.attributes.process@pid":136,"resource.attributes.host@arch":"amd64","resource.attributes.telemetry@sdk@version":"1.7.0","resource.attributes.service@name":"platform-test","resource.attributes.k8s@pod@name":"platform-test-bravo-5f8fbc497d-5cwjk","status.code":0,"resource.attributes.process@runtime@name":"OpenJDK Runtime Environment","resource.attributes.os@type":"linux","resource.attributes.cloud@availability_zone":"us-east-1a","resource.attributes.host@type":"m5n.2xlarge","resource.attributes.cloud@provider":"aws","span.attributes.thread@name":"https-jsse-nio-8080-exec-1","resource.attributes.k8s@deployment@name":"platform-test-bravo","resource.attributes.telemetry@sdk@language":"java","resource.attributes.host@name":"ip-10-0-32-165.ec2.internal","resource.attributes.process@runtime@description":"IcedTea OpenJDK 64-Bit Server VM 25.242-b08","resource.attributes.cloud@region":"us-east-1","resource.attributes.process@executable@path":"/usr/lib/jvm/java-1.8-openjdk/jre:bin:java","resource.attributes.k8s@pod@ip":"100.99.194.14","resource.attributes.process@command_line":"/usr/lib/jvm/java-1.8-openjdk/jre:bin:java -javaagent:opentelemetry-javaagent.jar -Dotel.traces.exporter=otlp -Dotel.exporter.otlp.traces.endpoint=http://otlp-collector.otlp.svc.cluster.local:4317 -Dotel.exporter.otlp.metrics.endpoint=http://otlp-collector.otlp.svc.cluster.local:4317 -Dotel.resource.attributes=service.name=platform-test -Dotel.service.name=platform-test -Dotel.javaagent.debug=true -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:MetaspaceSize=160m -XX:+UseStringDeduplication -XX:+ExitOnOutOfMemoryError -Xms1024m -Xmx1024m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -XX:CICompilerCount=2","resource.attributes.process@runtime@version":"1.8.0_242-b08","resource.attributes.telemetry@sdk@name":"opentelemetry","resource.attributes.cloud@platform":"aws_eks","resource.attributes.container@id":"bdeabf673ef79ceefec2d562629632211b9e54015a9bd20c792d753b14a6bf61","resource.attributes.telemetry@auto@version":"1.7.1","resource.attributes.os@description":"Linux 4.9.0-13-amd64"},"fields":{"startTime":["2021-11-08T16:17:48.009644775Z"],"endTime":["2021-11-08T16:17:48.012132857Z"],"traceGroupFields.endTime":["2021-11-08T16:17:48.012570043Z"]},"highlight":{"resource.attributes.service@name":["@opensearch-dashboards-highlighted-field@platform-test@/opensearch-dashboards-highlighted-field@"],"serviceName":["@opensearch-dashboards-highlighted-field@platform-test@/opensearch-dashboards-highlighted-field@"]},"sort":[1636388268009644800]}
```
and in the `otel-v1-service-map` I don't see any documents for this service at all.

**Comment by arnitolog** [comment]
I've performed another experiment: I modified the configuration and left only `service-map-pipeline` pipeline. 
And I see on the metrics that data is coming in `service-map-pipeline` but not coming out.

here is the pipeline:
```
    entry-pipeline:
      delay: "100"
      source:
        otel_trace_source:
          ssl: false
      prepper:
        - peer_forwarder:
            discovery_mode: "dns"
            domain_name: "data-prepper-headless"
            ssl: false
      buffer:
        bounded_blocking:
          buffer_size: 1024
          batch_size: 256
      sink:
        - pipeline:
            name: "raw-pipeline"
        - pipeline:
            name: "service-map-pipeline"
    service-map-pipeline:
      delay: "100"
      source:
        pipeline:
          name: "entry-pipeline"
      prepper:
        - service_map_stateful:
      sink:
        - opensearch:
            hosts: ["https://logging-cluster-alfa-os.es.svc.cluster.local:9200"]
            insecure: true
            username: "data-prepper"
            password: "xxxxxxxxxxxx"
            trace_analytics_service_map: true
```
here is what I see on the metrics:
![image](https://user-images.githubusercontent.com/34036079/140891581-ee73da23-5483-4d62-ae81-0095df0b9903.png)

![image](https://user-images.githubusercontent.com/34036079/140894792-cd3d1d50-020b-4705-bf0e-9fb0006173fb.png)

and buffer metrics:
![image](https://user-images.githubusercontent.com/34036079/140891798-3f3485f4-c9e9-4e5c-9b78-36246a901c1b.png)

It looks like records dropped for some reason.

I tried to enable debug: 
```
    logger.plugins.name = com.amazon.dataprepper.plugins
    logger.plugins.level = debug
```
but it showed only lines like below:

```
{"timeMillis":1636393782026,"thread":"entry-pipeline-prepper-worker-1-thread-1","level":"INFO","loggerName":"com.amazon.dataprepper.pipeline.ProcessWorker","message":" entry-pipeline Worker: Processing 1 records from buffer","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":21,"threadPriority":5}
{"timeMillis":1636393782037,"thread":"entry-pipeline-prepper-worker-1-thread-1","level":"DEBUG","loggerName":"com.amazon.dataprepper.pipeline.ProcessWorker","message":"Pipeline Worker: Submitting 1 processed records to sinks","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":21,"threadPriority":5}
{"timeMillis":1636393782138,"thread":"service-map-pipeline-prepper-worker-3-thread-1","level":"INFO","loggerName":"com.amazon.dataprepper.pipeline.ProcessWorker","message":" service-map-pipeline Worker: Processing 1 records from buffer","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":22,"threadPriority":5}
```
Is there anything else I can enable/configure to get more details on why data is dropped
