### ISSUE TITLE
[BUG] MapToList processor throws NPE when input map contains null values

### ISSUE THREAD

**Issue by oeyh** [opensearch-project/data-prepper#5341]
**Describe the bug**
MapToList processor throws NPE when input map contains null values

**To Reproduce**
For example, if the input data is:
```json
  {
    "my-map": {
      "key1": "value1",
      "key2": null
    }
  }
```
and processor config is:
```yaml
    - map_to_list:
        source: "my-map"
        target: "my-list"
``` 

or

```yaml
    - map_to_list:
        source: "my-map"
        target: "my-list"
        convert_field_to_list: true
```
It will throw NPE.

**Expected behavior**
Processor should be able to process the record without errors.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**
