### ISSUE TITLE
Allow source field to be deleted if dissect processor was successful

### ISSUE THREAD

**Issue by alamzeeshan** [opensearch-project/data-prepper#5345]
**Is your feature request related to a problem? Please describe.**
Allow source field to be deleted if `dissect` processor was successful

**Describe the solution you'd like**
Modify `dissect` processor to support this new configuration that allows the source to be deleted when `dissect` processor was successful. Something in lines of `delete_source` option of `parse_json` processor. 

Example:
```yaml
  processor:
    - dissect:
        map:
          message: "%{Date} %{Time} %{Log_Type}: %{Message}"
        delete_source: true
```

**Describe alternatives you've considered (Optional)**

**Additional context**
