### ISSUE TITLE
Support multiple entries of source + list_to_map_when condition in list-to-map processor

### ISSUE THREAD

**Issue by niketan16** [opensearch-project/data-prepper#5368]
**Is your feature request related to a problem? Please describe.**
Allow the `list-to-map` processor to convert multiple sources (a list of objects from an event) to maps of keys to objects under different conditions.

**Describe the solution you'd like**
Modify `list-to-map` processor to support this new configuration that allows multiple entries of `source` and `list_to_map_when` conditions like shown below. The existing configuration is still supported. This is new config under entries needs to be added.

```
processor:
    - list_to_map:
        entries:
           - source: "mylist"
             key: "name"
             value_key: "value"
             flatten: true
             list_to_map_when: "some-key == 'test'"
           - source: "mylist2"
             key: "name2"
             value_key: "value2"
             flatten: true
             list_to_map_when: "some-key2 == 'test2'"
```

**Describe alternatives you've considered (Optional)**

**Additional context**
