### ISSUE TITLE
Support multiple entries of source + target + map_to_list_when condition in map_to_list processor

### ISSUE THREAD

**Issue by niketan16** [opensearch-project/data-prepper#5380]
**Is your feature request related to a problem? Please describe.**
Allow the `map_to_list` processor to convert multiple sources (map of key-value pairs) to lists of objects under different `map_to_list_when` conditions.

**Describe the solution you'd like**
Modify `map_to_list` processor to support this new configuration that allows multiple entries of `source`, `target` and `map_to_list_when`(optional) like shown below. The existing configuration is still supported. This is new config under entries needs to be added.

```
processor:
    - map_to_list:
        entries:
           - source: "my-map"
             target: "my-list"
             map_to_list_when: "some-key == 'test'"
           - source: "my-map2"
             target: "my-list2"
             map_to_list_when: "some-key2 == 'test2'"
```

**Describe alternatives you've considered (Optional)**

**Additional context**
