### ISSUE TITLE
Support proxy in OpenSearch source

### ISSUE THREAD

**Issue by pablosnt** [opensearch-project/data-prepper#5422]
**Is your feature request related to a problem? Please describe.**
I have a pipeline that reads from an OpenSearch index and writes in another one. That OpenSearch server is behind a proxy, so I need to configure it in the source and the sink

**Describe the solution you'd like**
I think the best solution is adding a `proxy` to the `opensearch` source:
```yaml
source:
  opensearch:
    ...
    proxy: https://myproxy:8080
```

Or within the `connection` field:

```yaml
source:
  opensearch:
    ...
    connection:
      proxy: https://myproxy:8080
```

**Describe alternatives you've considered (Optional)**
- `proxy` field in the `opensearch` source, or in the `connection` subfield
- `proxy` field in the `data-prepper-config.yaml`
- Environment variable

**Additional context**
The proxy configuration is already supported for the `opensearch` sink. It was reported in #300 and implemented in #479

Thank you very much in advance!
I know how hard is maintaining an open source project, so if you need help, I can try to implement this
