### ISSUE TITLE
Support options in OpenSearch sink to prevent duplicates by querying OpenSearch

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#5442]
**Is your feature request related to a problem? Please describe.**
As a user of the OpenSearch sink without for OpenSearch Serverless vector and time series collections that do not support custom document id, I would like to prevent duplicate data from entering OpenSearch. 

**Describe the solution you'd like**
Configuration options in the OpenSearch sink that will enable querying OpenSearch for a documents that may already exist in OpenSearch to prevent duplicate documents.

```
- opensearch:
        ....
        query_for_existing_document:
          query_when: 'getMetadata("potential_duplicate") == true'
          query_term: 'id'
          action_on_found: drop // only option currently
          query_duration: PT3M
```

**Additional context**
