### ISSUE TITLE
Support for Kafka authentication using SSL/TLS

### ISSUE THREAD

**Issue by gderemetz** [opensearch-project/data-prepper#5505]
I am trying to use OpenSearch Ingestion to consume data from Kafka, but my Kafka cluster is configured to use SSL/TLS with mutual authentication (mTLS). This means I only have a client certificate and key for authentication, without a username/password.

Could you confirm whether SSL/TLS authentication with a client certificate (without username/password) is not supported? 

Thanks in advance for your help

**Comment by kkondaka** [comment]
@gderemetz we only support SASL/SSL with the following config where certificate is used for encryption and SASL/PLAIN is used for authentication.

```
encryption:
        type: "ssl"
        certificate_content: >
          -----BEGIN CERTIFICATE-----

          -----END CERTIFICATE-----
      
        
      authentication:
        sasl:
          plain:
            username: <username>
            password: <password>

```
It looks like you are asking for `mTLS` option under authentication. We currently do not support that.
