### ISSUE TITLE
[BUG] Key-value processor has incorrect behavior with spaces or quotes

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#5584]
**Describe the bug**
Key-value processor does not work as intended for this sample input

```
{
  "log_message": "level=info key=test-key msg=\"upload test\" other_field=12345"
}
```

The msg is cut off with this config

```
- key_value:
        source: "log_message"
        field_split_characters: null
        field_delimiter_regex: "(\\s)"
        value_split_characters: "="
        destination: null
        include_keys: ["level", "msg", "key", "other_field"]
```

and it creates this output

```
{
    "log_message": "level=info key=test-key msg=\"upload test\" other_field=12345",
    "msg": "\"upload"
    "level": "info"
}
```

**Expected behavior**
Output should be 

```
{
    "log_message": "level=info key=test-key msg=\"upload test\" other_field=12345",
    "msg": "\"upload test\"",
    "level": "info",
    "other_field": 12345
}
```

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]

**Additional context**
Also tried using value grouping but it cuts off after the group
