### ISSUE TITLE
[RFC] OTel telemetry unified source

### ISSUE THREAD

**Issue by ps48** [opensearch-project/data-prepper#5596]
## Overview 

Today, Data prepper have three different sources for logs, traces and metrics. These three different sources need individual pipelines (source, buffer, processor [optional] and sink). In Data prepper we can have three different pipelines with individual sources. For ease of initial setup and use, we propose a OTel Telemetry source in data prepper to add logs, traces and metrics in a single OTLP source separated by path suffixes as per OTel standards.

### OTel logs source

Supports OTel logs to be ingested via exposed OTLP (gRPC) or HTTP endpoints. This source decodes the OTel logs format into flattend structure that can be ingested in OpenSearch and other compatible sinks. Defaults to `/v1/logs` http path

### Otel traces source

Supports OTel traces to be ingested via exposed OTLP (gRPC) or HTTP endpoints. This source consumes OTel trace data and converts it into a format compatible with OpenSearch and other analysis platforms. The source decodes spans, span events, and other trace data for later enrichment and analysis. Defaults to /v1/traces http path.

### Otel metrics source

Supports OTel metrics to be ingested via exposed OTLP (gRPC) or HTTP endpoints. This source accepts metrics data including counters, gauges, histograms, and summary statistics. It transforms the metrics into formats suitable for aggregation, visualization, and long-term storage in OpenSearch and other time-series databases. Defaults to /v1/metrics http path.

### Existing Otel source signals setup

Below is the current setup that users use to send Otel based logs, traces and metrics to OpenSearch indexes. The three signals land onto separate sources. The sources are differentiated by ports on the same endpoint with different path suffixes based on OTel exporter SDK as mentioned [here](https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/). Each source ends up in separate sinks 

```
otel-logs-pipeline:
  source:
    otel_logs_source:
      ssl: false
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        insecure: false
        index_type: custom
        index: ss4o_logs-%{yyyy.MM.dd}
        bulk_size: 4

otel-traces-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
  sink:
    - pipeline:
        name: "traces-raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"

traces-raw-pipeline:
  source:
    pipeline:
      name: "otel-traces-pipeline"
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        insecure: false
        index_type: trace-analytics-raw

service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "otel-traces-pipeline"
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: ["https://opensearch:9200"]
        insecure: false
        index_type: trace-analytics-service-map

otel-metrics-pipeline:
  source:
    otel_metrics_source:
  processor:
    - otel_metrics:
        calculate_histogram_buckets: true
        calculate_exponential_histogram_buckets: true
        exponential_histogram_max_allowed_scale: 10
        flatten_attributes: false
  sink:
    - opensearch:
        hosts: ["https://opensearch:9200"]
        insecure: false
        index_type: custom
        index: ss4o_metrics-otel-%{yyyy.MM.dd}
        bulk_size: 4
```

## Proposal unified source for Logs, Traces and Metrics

We want to propose a single unified source for all OTel telemetry signals starting with logs, traces and metrics maintaining OTel sdk standards. The three three signals would be separated based on endpoints path suffixes and would have same host and port for data prepper. The routing to downstream pipelines would be based on meta-data routing.

This source would also have support for gRPC and http endpoints. The source would have similar auth model, config options as exisiting soruces. 

```
# Main telemetry pipeline with unified source
otel-telemetry-pipeline:
  source:
    otel_telemetry_source:
      ssl: false
  route:
    - logs: "getMetadata(\"eventType\") == \"LOG\""
    - traces: "getMetadata(\"eventType\") == \"TRACE\""
    - metrics: "getMetadata(\"eventType\") == \"METRIC\""
  sink:
    - pipeline:
        name: "logs-pipeline"
        routes:
          - "logs"
    - pipeline:
        name: "traces-pipeline"
        routes:
          - "traces"
    - pipeline:
        name: "metrics-pipeline"
        routes:
          - "metrics"

# Logs pipeline
logs-pipeline:
  source:
    pipeline:
      name: "otel-telemetry-pipeline"
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        insecure: false
        index_type: custom
        index: ss4o_logs-%{yyyy.MM.dd}
        bulk_size: 4

# Traces pipeline
traces-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "otel-telemetry-pipeline"
  sink:
    - pipeline:
        name: "traces-raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"

# Traces raw processing pipeline
traces-raw-pipeline:
  source:
    pipeline:
      name: "traces-pipeline"
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        insecure: false
        index_type: trace-analytics-raw

# Service map processing pipeline
service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "traces-pipeline"
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: ["https://opensearch:9200"]
        insecure: false
        index_type: trace-analytics-service-map

# Metrics pipeline
metrics-pipeline:
  source:
    pipeline:
      name: "otel-telemetry-pipeline"
  processor:
    - otel_metrics:
        calculate_histogram_buckets: true
        calculate_exponential_histogram_buckets: true
        exponential_histogram_max_allowed_scale: 10
        flatten_attributes: false
  sink:
    - opensearch:
        hosts: ["https://opensearch:9200"]
        insecure: false
        index_type: custom
        index: ss4o_metrics-otel-%{yyyy.MM.dd}
        bulk_size: 4
```

### Benefits of this new approach

1. **Simplified Configuration -** Data Prepper uses a single endpoint with standard OTel paths, making the config file simpler and easier to manage.
2. **Easier Setup -** Users can get started with fewer pipelines and a smoother setup process.
3. **Consistent with Industry Standards -** It follows the OTel spec, making Data Prepper plug-and-play with other OpenTelemetry tools.
4. **Reduced Resource Usage -** One server handles all signals, saving memory and simplifying deployment.
5. **Better Integration -** All telemetry types work together in one flexible pipeline model.
6. **Future Extensibility -** The design makes it easy to add new telemetry types down the line.

### Current PoC for Otel telemetry source

* https://github.com/ps48/data-prepper/tree/otel-telemetry-source
