### ISSUE TITLE
[BUG] Otel Trace Source - Field Mapping Conflict for OTel Attributes with Dotted Keys

### ISSUE THREAD

**Issue by ps48** [opensearch-project/data-prepper#5616]
## Describe the bug
When ingesting OTel traces using Data Prepper into OpenSearch, we’re seeing document ingestion failures with the following error messages:
```
Document failed to write to OpenSearch with error code 400. Configure a DLQ to save failed documents. Error: can't merge a non object mapping [attributes.upstream_cluster] with an object mapping

Document failed to write to OpenSearch with error code 400. Configure a DLQ to save failed documents. Error: object mapping for [attributes.user_agent] tried to parse field [user_agent] as object, but found a concrete value
```

These errors originate from OpenSearch's field mapping behavior when dynamic keys in attributes contain dots (.), such as:
```
{
  "key": "upstream_cluster",
  "value": "frontend"
},
{
  "key": "upstream_cluster.name",
  "value": "frontend"
}
```
OpenSearch interprets dotted keys like upstream_cluster.name as nested fields, which causes a mapping conflict when the base key upstream_cluster is already defined as a concrete value.

## Root Cause
The current mapping template in Data Prepper sets attributes.* as dynamic fields of type keyword, long, or double using match_mapping_type without protecting against field path collisions caused by dot notation.

The issue arises because OpenSearch:
* Treats attributes.upstream_cluster as a concrete value (string, long, etc.)
* Then encounters attributes.upstream_cluster.name, which is interpreted as a nested object, resulting in: `can't merge a non object mapping with an object mapping`
* Similar issues happen when a field like attributes.user_agent appears as both a string and an object.

## Current Mapping Snippet
link to mappings: https://github.com/opensearch-project/data-prepper/blob/bc7bfecf1444b4c82d49423680d1d550b068f804/data-prepper-plugins/opensearch/src/main/resources/otel-v1-apm-span-index-standard-template.json#L8-L93

This setup assumes flat string (or other relevant data type) fields under attributes, but does not prevent dotted keys from being treated as object paths.

## Suggested fix

As the goal is to store attributes as a map but support dotted keys, using the [flat_object field](https://docs.opensearch.org/docs/latest/field-types/supported-field-types/flat-object/) type would help:

```
    "dynamic_templates": [
      {
        "resource_attributes_map": {
          "mapping": {
            "type": "flat_object"
          },
          "path_match": "resource.attributes.*"
        }
      },
      {
        "attributes_map": {
          "mapping": {
            "type": "flat_object"
          },
          "path_match": "attributes.*"
        }
      }
    ],
```

### Data prepper pipeline config
version: 2.11-snapshot from latest main  
```
entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      output_format: otel
      ssl: false
  processor:
    - trace_peer_forwarder:
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"

raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - otel_traces:
  sink:
  - opensearch:
      hosts: OPENSEARCH_HOSTS
      username: OPENSEARCH_USER
      password: OPENSEARCH_PASSWORD
      insecure: true
      index_type: trace-analytics-plain-raw
      
service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: OPENSEARCH_HOSTS
        username: OPENSEARCH_USER
        password: OPENSEARCH_PASSWORD
        insecure: true
        index_type: trace-analytics-service-map 
```

**Comment by ps48** [comment]
Hi @dlvenable @kkondaka @KarstenSchnitter, Let me know if this is something we don't want to handle it in our source implementations and request the users to handle such exceptions.

**Comment by KarstenSchnitter** [comment]
Hi,

thanks for creating this issue with its elaborate description. We have already discussed these kinds of collisions and agreed, that users should handle this with some custom processors. 

The proposed mapping type `flat_object` looks like a good idea, but has several limitations. Especially its inability of aggregations on subfields is a huge drawback. OpenTelemetry attributes are used as tags for the underlying events. Data analysis relies heavily on filters and aggregations on the attributes. Not having this ability is a severe limitation.

There is one thing, that helps avoiding collisions: the [OpenTelemetry semantic conventions](https://github.com/open-telemetry/semantic-conventions/tree/main/docs). Using only attribute names from these conventions ensures conflict-free ingestion. There might be issues between different versions of the semantic conventions. In that case a custom processor is required. Another problem might be open-ended conventions like [k8s.pod.label.\<key\>](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/attributes-registry/k8s.md#k8s-pod-label). In my experience the labels are notorious for creating field conflicts if not handled with care. Here a solution with `flat_object` might be a good idea. Fortunately, the dynamic mappings allow overriding with specific mappings rather easily. This becomes even better when using component templates. I am going to show this at OpenSearch Con 2025 Europe.

One final thing is about compatibility with older OpenSearch versions. `flat_object` was only introduced with OpenSearch 2.7. Until the final release of OpenSearch 3.0 is published, OpenSearch 1.x. is still officially maintained. So there might be an argument of Data Prepper keeping backwards compatibility with older versions. The dynamic mappings go all the way back and would work even with Elastic in OpenDistro.

Having gone through all of the above I can see one field, that can clearly benefit from `flat_object`: The `body` of an OTel log. This can be any object (as specified in the `schemaUrl`). If the default mapping does not match your data, this would be a good change to the mapping.

Cheers,
Karsten

**Comment by ps48** [comment]
@KarstenSchnitter My current setup is testing this on OpenSearch OTel demo, I also see these errors as shown below, do you happen to know the root-cause for the below is it the same mapping issue?  

```
2025-04-24T22:25:26,124 [raw-pipeline-sink-worker-6-thread-1] WARN  org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink - Document failed to write to OpenSearch with error code 400. Configure a DLQ to save failed documents. Error: failed to parse caused by class org.opensearch.index.mapper.KeywordFieldMapper cannot be cast to class org.opensearch.index.mapper.ObjectMapper (org.opensearch.index.mapper.KeywordFieldMapper and org.opensearch.index.mapper.ObjectMapper are in unnamed module of loader 'app')
```

**Comment by ps48** [comment]
For now, I made it work by deleting the keys that are not compatible with the OTel output format. For now, it doesn't look like a good end-user experience. I had to skim through DP error logs to understand which fields were failing. 

```
raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    # workaround for https://github.com/opensearch-project/data-prepper/issues/5616
    - delete_entries:
        with_keys: ["attributes/upstream_cluster", "attributes/user_agent", "app/ads/contextKeys"]
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: OPENSEARCH_HOSTS
        username: OPENSEARCH_USER
        password: OPENSEARCH_PASSWORD
        insecure: true
        index_type: trace-analytics-plain-raw
        
service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: OPENSEARCH_HOSTS
        username: OPENSEARCH_USER
        password: OPENSEARCH_PASSWORD
        insecure: true
        index_type: trace-analytics-service-map
```

**Comment by jongminchung** [comment]
Hi, @KarstenSchnitter @ps48 

I understood that the situation [provided as an example](https://github.com/opensearch-project/data-prepper/issues/5616#:~:text=attributes%EC%9D%98%20%EB%8F%99%EC%A0%81%20key%EC%97%90%20%EB%A7%88%EC%B9%A8%ED%91%9C(.)%EA%B0%80%20%ED%8F%AC%ED%95%A8%EB%90%98%EC%96%B4%20%EC%9E%88%EC%9D%84%20%EB%95%8C(%EC%98%88%3A%20)%20%EB%B0%9C%EC%83%9D%ED%95%98%EB%8A%94%20OpenSearch%EC%9D%98%20%ED%95%84%EB%93%9C%20%EB%A7%A4%ED%95%91%20%EB%8F%99%EC%9E%91%EC%97%90%EC%84%9C%20%EB%B9%84%EB%A1%AF%EB%90%A9%EB%8B%88%EB%8B%A4) is because the developer had a conflict with the relevant [opentelemetry semconvnaming recommendation](https://opentelemetry.io/docs/specs/semconv/general/naming/#recommendations-for-application-developers:~:text=It%20is%20not,with%20your%20own.) in the demo project, is it correct?

---

There was an error in as well, so I analyzed DLQ as a file. (in `traces-raw-pipeline`)

```text
# WARN LOG
2026-03-09T08:44:24,264 [traces-raw-pipeline-sink-worker-10-thread-1] WARN  org.opensearch.dataprepper.plugins.sink.opensearch.BulkRetryStrategy - index = otel-v1-apm-span-000001, operation = Index, status = 400, error = Could not dynamically add mapping for field [rpc.system.name]. Existing mapping for [attributes.rpc.system] must be of type object but found [keyword].
```

```text
# DLQ LOG
{"Document": [index {[otel-v1-apm-span][8a9bff870550dd429f5c890622856561/0f87d0daca336936], source[{"traceId":"8a9bff870550dd429f5c890622856561","droppedLinksCount":0,"instrumentationScope":{"name":"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc","droppedAttributesCount":0,"version":"0.65.0"},"resource":{"attributes":{"service.name":"product-catalog","process.command_args":["./product-catalog"],"process.runtime.version":"go1.24.13","os.type":"linux","process.pid":1,"process.executable.name":"product-catalog","service.namespace":"opentelemetry-demo","telemetry.sdk.name":"opentelemetry","process.owner":"nonroot","telemetry.sdk.language":"go","process.runtime.name":"go","service.version":"2.2.0","os.description":"Debian GNU/Linux Debian GNU/Linux 12 (bookworm) (Linux c39a4f84dcc4 6.17.8-orbstack-00308-g8f9c941121b1 #1 SMP PREEMPT Thu Nov 20 09:34:02 UTC 2025 aarch64)","process.executable.path":"/usr/src/app/product-catalog","host.name":"orbstack","telemetry.sdk.version":"1.40.0","process.runtime.description":"go version go1.24.13 linux/arm64"},"schemaUrl":"https://opentelemetry.io/schemas/1.39.0","droppedAttributesCount":0},"kind":"SPAN_KIND_SERVER","droppedEventsCount":0,"flags":769,"parentSpanId":"30207a647f6939d3","schemaUrl":"","spanId":"0f87d0daca336936","traceState":"","name":"oteldemo.ProductCatalogService/GetProduct","startTime":"2026-03-09T08:42:46.521693323Z","attributes":{"server.address":"192.168.97.29","rpc.method":"oteldemo.ProductCatalogService/GetProduct","server.port":55216,"app.product.name":"Roof Binoculars","rpc.response.status_code":"OK","rpc.system.name":"grpc","app.product.id":"2ZYFJ3GM2N"},"links":[],"endTime":"2026-03-09T08:42:46.535717740Z","droppedAttributesCount":0,"durationInNanos":14024417,"events":[{"name":"Product Found","time":"2026-03-09T08:42:46.534710693Z","attributes":{},"droppedAttributesCount":0}],"status":{"code":0,"message":""},"serviceName":"product-catalog","traceGroup":"user_browse_product","traceGroupFields":{"endTime":"2026-03-09T08:42:46.539802973Z","durationInNanos":62163122,"statusCode":0}}]}], "failure": Could not dynamically add mapping for field [rpc.system.name]. Existing mapping for [attributes.rpc.system] must be of type object but found [keyword].}
```

<img width="1610" height="1278" alt="Image" src="https://github.com/user-attachments/assets/c6f95779-b8a0-4531-9651-4dfa2ed08051" />

**Comment by KarstenSchnitter** [comment]
The [OpenTelemetry semantic conventions for rpc](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/rpc/rpc-spans.md) specifies the attribute `rpc.system.name` to be used. It is likely, that this attribute is used in other spans already present in your index. Therefore, `rpc.system` has type `object` which causes the indexing error you are experiencing. This processor configuration might be helpful to resolve this particular collision:

```yaml
pipeline:
  source:
    # ... your source config

  processor:
    - rename_keys:
        entries:
          - from_key: "attributes/rpc/system"
            to_key: "attributes/rpc/system_tmp"
            condition: '/attributes/rpc/system != null and not /attributes/rpc/system instanceof java.util.Map'

    - add_entries:
        entries:
          - key: "attributes/rpc/system/name"
            value_expression: '/attributes/rpc/system_tmp'
            condition: '/attributes/rpc/system_tmp != null'

    - delete_entries:
        with_keys:
          - "attributes/rpc/system_tmp"
        condition: '/attributes/rpc/system_tmp != null'

  sink:
    # ... your sink config
```
