### ISSUE TITLE
Support health_check_service and unauthenticatedHealthCheck options in otel-logs-source

### ISSUE THREAD

**Issue by Davidding4718** [opensearch-project/data-prepper#5651]
**Is your feature request related to a problem? Please describe.**
It was found during testing that the `otel-logs-source` plugin does not support the `health_check_service` with  http authentication, `curl` command in terminal specifically.  Additionally, `otel-logs-source` plugin also does not support `unauthenticated_health_check` options. 
In contrast, both `otel-metrics-source` and `otel-trace-source` sources support these features.

**Describe the solution you'd like**
Enhance the `otel-logs-source` plugin to support:

- The `health_check_service` option with HTTP authentication, so that users can check health via `curl` requests.

- The `unauthenticated_health_check` option, following the same implementation as in `otel-metrics-source` and `otel-trace-source` do.

**Describe alternatives you've considered (Optional)**
N/A

**Additional context**
1. `health_check_service` in `otel_logs_source`,
**Example** of pipeline.yaml:

```
test-pipeline:
  source:
    otel_logs_source:
      ssl: false
      port: 2021
      unframed_requests: true
      health_check_service: true
      proto_reflection_service: true

  sink:
    - stdout:
```

Using grpcurl works:

```
grpcurl -plaintext localhost:2021 grpc.health.v1.Health/Check 
{
  "status": "SERVING"
}

```

Using HTTP health check `curl` fail:

```
curl -X GET http://localhost:2021/health                      
Status: 404
Description: Not Found
```

2. `unauthenticated_health_check` in `otel_logs_source`,
**Example** of pipeline.yaml:
 
```
test-pipeline:
  source:
    otel_logs_source:
      ssl: false
      port: 2021
      unframed_requests: true
      health_check_service: true
      unauthenticated_health_check: true


  sink:
    - stdout:
```

this is the error detail:
`[main] ERROR org.opensearch.dataprepper.core.validation.LoggingPluginErrorsHandler - 1. test-pipeline.source.otel_logs_source: caused by: Parameter "unauthenticated_health_check" for plugin "otel_logs_source" does not exist.`
