### ISSUE TITLE
[BUG] Escape sequences aren't removed from regex

### ISSUE THREAD

**Issue by thomascft** [opensearch-project/data-prepper#5652]
**Describe the bug**

Escape characters aren't trimmed from `regexPattern` in the antlr grammar. Data prepper requires that the pattern `^\w*$` is escaped. It produces the following error message when the pattern is left unescaped.

```
/data-prepper/tree/main/data-prepper-plugins/http-source#authentication-configurations
line 1:9 token recognition error at: '^'
line 1:10 token recognition error at: '\'
line 1:11 token recognition error at: 'w*'
line 1:13 token recognition error at: '$"'
line 1:8 mismatched input '"' expecting {JsonPointer, EscapedJsonPointer, String}
```

When escaping `\` and `$`, the parser no longer errors out, but the expression produced contains the escape sequences (`^\\w*\$`). 

**To Reproduce**
Run data-prepper 2.11.0 with the following pipeline.yml

```yaml
# pipeline.yml
main:
  source:
    http:
  processor:
    - add_entries:
        entries:
          - add_when: /msg =~ "^\\w*\$" # Here's the problematic expression
            key: "matched"
            value: "true"
  sink:
    - stdout:

```
Send it JSON with a `msg` field.

**Expected behavior**

The following `msg` value should satisfy the `add_when` expression using the regex operator: 
```json
{"msg":"word"}
```
**Environment (please complete the following information):**
 - OS: [Debian Bookworm]
 - Version [2.11]

**Additional context**

This value satisfies the regex used in the pipeline above. 

```json
{"msg":"\\wwww$"}
```

Adding a print statement to this lambda outputs the RegEx pattern with escape characters included.
https://github.com/opensearch-project/data-prepper/blob/52a1e6d912a8e1265b3ae212507e6edf6992a15f/data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/OperatorConfiguration.java#L23

I'm not super familiar with antrl, but from my understanding you'd want to remove escape characters within the [listener](https://github.com/opensearch-project/data-prepper/blob/52a1e6d912a8e1265b3ae212507e6edf6992a15f/data-prepper-expression/src/main/java/org/opensearch/dataprepper/expression/ParseTreeEvaluatorListener.java). I'll spend a bit more time hacking away at the source, and submit a PR with whatever fix I find.
