### ISSUE TITLE
[BUG] The sink's include_keys feature won't work unless inputs are alphabetically ordered

### ISSUE THREAD

**Issue by Apple-Of-Eden** [opensearch-project/data-prepper#5695]
**Describe the bug**
Say we have a sink A defined like:
```
  sink:
  - opensearch:
      document_root_key: info # My testing involved a document root key
      include_keys: ["foo", "name"]
```
And sink B defined like:
```
  sink:
  - opensearch:
      document_root_key: info # My testing involved a document root key
      include_keys: ["name", "foo"]
```
The two have different outputs. Sink A results in documents retaining both `foo` and `name`, but Sink B results in documents only retaining `name`.  Based on larger inputs, I can confirm that alphabetical order is required.

**To Reproduce**
It's easy to see if you modify the unit test [testJsonStringBuilderWithIncludeKeys](https://github.com/opensearch-project/data-prepper/blob/a08cd7b82f63d4d107bd9469620099fa45af0297/data-prepper-api/src/test/java/org/opensearch/dataprepper/model/event/JacksonEventTest.java#L971) by appending the following lines:
```
// Test order independence
List<String> includeKeys8a = List.of("foo", "name");
List<String> includeKeys8b = List.of("name", "foo");
final String expectedJsonString8 = "{\"name\":\"hello\",\"foo\":\"bar\"}";

// Succeeds
assertThat(event.jsonBuilder().rootKey("info").includeKeys(includeKeys8a).toJsonString(), equalTo(expectedJsonString8));
        
// Fails
assertThat(event.jsonBuilder().rootKey("info").includeKeys(includeKeys8b).toJsonString(), equalTo(expectedJsonString8));
```

**Of note**
So when the `include_keys` functionality was first added (MR: https://github.com/opensearch-project/data-prepper/pull/2989), the `SinkModel` had a method `preprocessingKeys` that sorted the keys. At some point that code went away but the `searchAndFilter` function within `JacksonEvent` still expects a sorted input. 

Whether the fix should be in `JacksonEvent` or `SinkModel` is beyond my knowledge of this repo.

**Expected behavior**
The sink's `include_keys` feature should not depend on the order of its inputs.

**Environment (please complete the following information):**
1st environment:
 - OS: unknown. 
 - Using AWS's OpenSearch serverless pipeline on May 14th, 2025.

2nd environment in which I ran the above unit test changes:
 - OS: OSX Sequoia 15.5
 - Using main (commit a08cd7b)
