### ISSUE TITLE
[BUG] parse_json not being able to parse JSON arrays

### ISSUE THREAD

**Issue by architkshk** [opensearch-project/data-prepper#5705]
Here's the ticket summary in the requested format:

**Describe the bug**
The parse_json processor in Data Prepper fails to parse valid JSON arrays. When attempting to parse a JSON string that contains an array of objects, it throws an error: `jorg.opensearch.dataprepper.plugins.processor.parse.json.ParseJsonProcessor - An exception occurred due to invalid JSON while parsing [******] due to ******`.

**To Reproduce**
1. Set up a Data Prepper pipeline with DynamoDB as source
2. Configure parse_json processor to parse a field containing a JSON array string
3. Example input:
```json
{
    "tags": "[{\"type\":\"foo1\",\"value\":\"bar1\"},{\"type\":\"foo2\",\"value\":\"bar2\"}]"
}
```
4. Run the pipeline
5. Observe the error

**Expected behavior**
The parse_json processor should successfully parse valid JSON strings, including arrays, into their corresponding JSON objects/arrays. In this case, it should parse the string into an array of objects.

**Screenshots**
N/A

**Environment**
- Source: DynamoDB
- Sink: OpenSearch Serverless Collection
- Component: Data Prepper parse_json processor
- Amazon OpenSearch Ingestion Pipeline

**Additional context**
- Current workaround involves using substitute_string processor to remove array brackets or wrapping the array in an object using add_entries
- The JSON strings are valid and can be parsed using standard JSON.parse() in JavaScript
- This appears to be a limitation in the JSON codec implementation

**Example Workaround**
```
processor:
  - add_entries:
      entries:
        - key: "tagsJSON"
          format: '{"tags":${tags}}'
  - parse_json:
      source: "tagsJSON"
      destination: "parsedTags"
      overwrite_if_destination_exists: true
  - add_entries:
      entries:
        - key: "tags"
          value_expression: "/parsedTags/tags"
          overwrite_if_key_exists: true
```
