### ISSUE TITLE
[BUG] AWS Lambda processor skips processing records under high load in OSIS

### ISSUE THREAD

**Issue by benkajaja** [opensearch-project/data-prepper#5719]
**Describe the bug**

The AWS Lambda processor in Data Prepper is intermittently skipping record processing when running in AWS OSIS. This occurs in a pipeline configuration where:

* Source: DynamoDB (containing base objects with S3 paths to vector data)
* Processor: AWS Lambda (meant to read S3 files and append vector data)
* Sink: OpenSearch

The processor appears to be bypassed sometimes, with records going directly to the sink without Lambda processing, particularly under high traffic and memory pressure conditions.

Sample pipeline configuration:
```yaml
version: "2"
ddb-integ-pipeline:
  source:
    dynamodb:
      acknowledgments: true
      tables:
        - table_arn: xxx
          stream:
            start_position: LATEST
      aws: xxx
  sink:
    - opensearch:
        hosts: xxx
        index: xxx
        index_type: custom
        action: index
        document_version: ${document_version}
        document_version_type: external
        document_id: ${my_id}
        flush_timeout: -1
        aws: xxx
        dlq: xxx
  processor:
    - aws_lambda:
        function_name: VectorIngestProcessor
        batch:
          key_name: events
          threshold:
            event_count: 10
            maximum_size: 5mb
        circuit_breaker_retries: 30
        circuit_breaker_wait_interval: 1000
        client:
            max_concurrency: 600
        aws:
          xxx
```

Sample dlq message:
```json
{
    "dlqObjects": [
        {
            "pluginId": "opensearch",
            "pluginName": "opensearch",
            "pipelineName": "ddb-integ-pipeline",
            "failedData": {
                "index": "xxx",
                "indexId": null,
                "status": 0,
                "message": "There was an exception when evaluating the document_version '${document_version}': The key document_version could not be found in the Event when formatting",
                "document": "{\"my_id\":\"xxx\",\"vectors\":\"s3://xxx.json\"}"
            },
            "timestamp": "2025-05-15T11:38:51.127Z"
        }
    ]
}
```

Sample lambda logic:
```python
def handle_requests(self, event: Dict[str, List[Dict]], context: Any) -> List[Dict]:
        ...
        # read s3 file path from field:vectors, and replace this field with actual vector data
        ...
        output = []
        while not result_queue.empty():
            item = result_queue.get()
            item["document_version"] = int(time.time() * 1000)
            output.append(item)
        return output
```

Observed Metrics during the issue:
* DynamoDB bytes processed: 220 MB/min (avg)
* JVM memory used: 12.23 GB (max)
* Lambda processor metrics:
  * Request payload size: 81 KB (avg)
  * Response payload size: 1.6 MB (avg)

Relevant Error Logs:
```
ERROR org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink - There was an exception when evaluating the document_version '${document_version}': The key document_version could not be found in the Event when formatting Check the dlq if configured to see more details about the affected Event
```
```
ERROR org.opensearch.dataprepper.plugins.lambda.processor.LambdaProcessor - software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
```

**To Reproduce**
Issue occurs frequently under the following conditions:
* High ingestion traffic
* High memory pressure (near JVM memory limits)

**Expected behavior**
All records should be processed by the Lambda function before being sent to OpenSearch, with each record containing:
* Vector data from S3 (10 vectors × 768 dimensions)
* Document version (timestamp)

**Screenshots**
No

**Environment (please complete the following information):**
Platform: AWS OSIS
Not deployed locally

**Additional context**
1. The vector data structure in processed records should contain 10 vectors, each with 768 dimensions, suggesting significant memory requirements for processing.
2. No Lambda errors were detected during this issue, suggesting the processor is being bypassed rather than failing
3. When DynamoDB write speed is low, all records are successfully processed by Lambda and ingested into OpenSearch, with complete vector data and document_version included in the records

**Comment by daniloarcidiacono** [comment]
Hello, I'm currently having the same issue in a production environment. My pipeline sources data from Opensearch, applies a transformation with a Lambda function and then writes the transformed data to a new index in the same OpenSearch cluster. No errors on Lambda nor objects in the S3 DLQ bucket. Also, the pipeline logs says that it has received acknowledgement of completion. 

Can you please give advice about what parameters can be tuned to mitigate the issue?

**Comment by srikanthjg** [comment]
Regarding these errors: 
```
ERROR org.opensearch.dataprepper.plugins.lambda.processor.LambdaProcessor - software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.

Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
```

You can solve them by increasing the default timeout from 60sec to 5M or more as shown:
```
aws_lambda:
      ...
      client:
          connection_timeout: PT5M
          api_call_timeout: PT5M
```


**Behaviour of lambda processor on Failure**: 

Each ProcessWorkers picks up a certain batch size from pipeline buffer, lets say X. Each processor in the processor chain will receive the same batch size X. Lets say we have lambda processor as one of the processors, we will get X records in total (assuming the processors before that have not deleted or added additional records but only modified). The X records are split up into smaller batches (lets say lambda batch size = Y) that user can configure for which lambda receives as a request. 

Behaviour when we have a failure with respect to lambda processor is that we will tag those smaller batches sent to lambda as failed and forward them to the next processor in the processor chain without processing - so you will see the unprocessed records for the set of records which had errors. If there is an error even with one record in batch Y, the entire batch Y is considered failed.
