### ISSUE TITLE
[BUG] readinessProbe and livenessProbe fails when enable the

### ISSUE THREAD

**Issue by latituder** [opensearch-project/data-prepper#5723]
**Describe the bug**

when enabling the authentication in data-prepper-config.yaml, the  readinessProbe and livenessProbe fails with 401 error

```
config:
  data-prepper-config.yaml: |
    ssl: false
    serverPort: 4900
      authentication:
        http_basic:
          username: "data-prepper"
          password: "mys3cr3t"
```

**To Reproduce**
see above

**Expected behavior**
In HELM, the data-prepper container's   readinessProbe and livenessProbe shall consider when http_basic authentication is enabled in configuration.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 LTS]
 - Version [e.g. 22]. HELM VERSION version: 0.3.1

**Additional context**
