### ISSUE TITLE
[BUG] HELM template service.yaml missing open 4900 port

### ISSUE THREAD

**Issue by latituder** [opensearch-project/data-prepper#5724]
**Describe the bug**

in the HELM chart, deployment.yaml template, it opens 4900 port by default. this is OK.
```
            - name: server
              containerPort: {{ (.Values.config).serverPort | default 4900 }}
              protocol: TCP
```

however, the HELM's service.yaml template doesn't have 4900 port open.
so, if not changing the devault values.yaml file, then the 4900 port is missing from the clusterIP service.
If adding the 4900 port in the `.Values.ports` manually, then the deployment will repot 4900 being open 2 times.
`W0528 11:33:20.601128   17742 warnings.go:70] spec.template.spec.containers[0].ports[5]: duplicate port definition with spec.template.spec.containers[0].ports[4]`
see the deployment.yaml template:
```
          ports:
          {{- range .Values.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: TCP
          {{- end }}
            - name: server
              containerPort: {{ (.Values.config).serverPort | default 4900 }}
              protocol: TCP
``` 

**To Reproduce**
see above

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
HELM version: 0.3.1

**Additional context**
