### ISSUE TITLE
Add content format detector processor

### ISSUE THREAD

**Issue by kkondaka** [opensearch-project/data-prepper#5731]
**Is your feature request related to a problem? Please describe.**
The event data received may have fields which can be of different format. For example, OTEL logs data contains "Body" field which is a string. The value of this field may contain JSON data or plain text or XML or CSV or Key-Value etc. Need a way to detect the format of the data in a given field
**Describe the solution you'd like**
Add a new processor `format_detector` which looks at the content of a given `source` field and detects the format and stores the format as a string in the event data or metadata

```
processor:
   - format_detector:
         source:
         # one of the following 2 is a must
         target_key:  (optional)
         target_metadata_key: (optional)
         (other config options as needed)
```

**Describe alternatives you've considered (Optional)**

**Additional context**
