### ISSUE TITLE
support flattening in ParseJson processor

### ISSUE THREAD

**Issue by kkondaka** [opensearch-project/data-prepper#5732]
**Is your feature request related to a problem? Please describe.**
ParseJson processor should provide an option to generate the json without nesting. The nested fields should be flattened with a configurable separator like "."

**Describe the solution you'd like**
Provide a config option under `parse_json` processor to flatten.

```
processor:
  - parse_json:
        source:
        destination:
        flatten_with: "."   # new config option indicating flatten and the character/string to use when flattening

```
The above config will parse a string like
`{"k1":"v1", "k2" : { "k3": "v3", "k4" : { "k5": "v5"}, "k6": "v6"}, "k7" : "v7"}`

to 
```
{
   "k1": "v1",
   "k2.k3": "v3",
   "k2.k4.k5": "v5",
   "k2.k6": "v6",
   "k7":"v7"
}
```

**Describe alternatives you've considered (Optional)**

**Additional context**
