### ISSUE TITLE
Inconsistencies regarding ss4o in docs, code, index-templates

### ISSUE THREAD

**Issue by rpasche** [opensearch-project/data-prepper#5791]
Hi @kkondaka , @KarstenSchnitter , @dlvenable , @rafael-gumiero 

I would like to raise this issue to provide some information (issues) I observed trying to ingest OTLP data into opensearch using SS4O.

I have quite some experience with the `elastic-stack`, but have never worked before with `opensearch` and `data-prepper`.

As mentioned, my goal was (is) to ingest OTLP data into opensearch and keeping the structure as close as possible to OTLP (which is what I think also SS4O is trying. Correct me if I'm wrong).

And, finally, this is not meant tell, how to do it better. I simply hope, that my information might be useful to improve the stack and get new users (like myself) started quicker.

### otel_logs_source, otel_metrics_source, otel_traces_source

I tried to follow example pipelines mentioned at https://docs.opensearch.org/docs/latest/data-prepper/common-use-cases/trace-analytics/#example-trace-analytics-pipeline or https://docs.opensearch.org/docs/latest/data-prepper/common-use-cases/log-analytics/#pipeline-configuration and was later also wondering, where those `log.attributes` field came from, that is also mentioned at

https://github.com/opensearch-project/data-prepper/issues/3098 and
https://github.com/opensearch-project/data-prepper/issues/5455

I tried *rename_keys*, *add_entries* + *delete_entries* within `data-prepper`, but nothing worked. In the end, I always had those `log.attributes` object, and was wondering, where this came from.

So this comes from https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/otel-proto-common/src/main/java/org/opensearch/dataprepper/plugins/otel/codec/OTelProtoOpensearchCodec.java

The *additional problem* is, that this *transformation* seems to be done *AFTER* all `processors` have been run. So there "seemed" to be no way of getting rid of those.

But then I found the - until now undocumented? - option `output_format` within those 3 `sources`. Once I have set this to `output_format: otel`,  the payload is - basically - kept as it is. Great!

So I'm running something similar to...
```
source:
  otel_logs_source:
    ssl: false
    output_format: otel
...
sink:
  - opensearch
    ...
    index_type: management_disabled
    index: ss4o_logs-demo-poc
    action: create
```
Of course, I needed to prepare the `data_stream` before. 

### ss4o index templates
I first found the index-templates in the [notebook.json](https://github.com/opensearch-project/opensearch-catalog/blob/main/integrations/observability/otel-schema-setup/info/notebook.json) and used those to create my templates.
Note: Each `PUT` statement is missing the leading `_`. The API is `PUT _index_template/` and not `PUT index_template/`

But using those *templates*, I pretty quickly got a lot of ingestion errors caused by `mapping_conflicts`. Mostly referring to `resource.attributes`. As `output_format: otel` is not *flattening* (nor renaming `.` with `@` in key names), the often resulting `objects` within `resource.attributes` failed with the `dynamic_template` to type all the fields as `keyword`.

Then, I finally found the *different* `index-templates` at https://github.com/opensearch-project/opensearch-catalog/tree/main/schema/observability and noticed that those templates *differ* from the templates mentioned within the `notebook.json`. Especially, PR https://github.com/opensearch-project/opensearch-catalog/pull/132 removed those `keyword` dynamic template for `resource.*`.

I then started to use the `data_stream` versions: So [logs](https://github.com/opensearch-project/opensearch-catalog/blob/main/schema/observability/logs/logs-datastream-1.0.0.mapping), [metrics](https://github.com/opensearch-project/opensearch-catalog/blob/main/schema/observability/metrics/metrics-datastream-1.0.0.mapping) and [traces](https://github.com/opensearch-project/opensearch-catalog/blob/main/schema/observability/traces/traces-datastream-1.0.0.mapping)

#### traces
The current [traces](https://github.com/opensearch-project/opensearch-catalog/blob/main/schema/observability/traces/traces-datastream-1.0.0.mapping) template is not a valid JSON! This is caused by a missing `properties: {` line at https://github.com/opensearch-project/opensearch-catalog/blob/main/schema/observability/traces/traces-datastream-1.0.0.mapping#L111

Once I fixed that, the *raw* `logs` and `traces` seem to get ingested just fine (without any special `trace analytics` or similar).

#### metrics

Because of issues observed in `data-prepper` (I also have an otel-demo running), I changed the field `value` to be only of type `double`, as all data that I saw were of type `double`. I found https://github.com/opensearch-project/opensearch-catalog/blob/main/docs/schema/observability/metrics/metrics.md, where `value.int` and `value.double` are defined....but for my current testing, I changed that.

```
"value@int": {
  "type": "integer"
},
"value@double": {
  "type": "double"
} 
```
into
```
"value": {
  "type": "double"
}
```

### bucketCount(s)?

I found https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-api/src/main/java/org/opensearch/dataprepper/model/metric/JacksonHistogram.java#L32 writing `bucketCounts`, but https://github.com/opensearch-project/opensearch-catalog/blob/main/schema/observability/metrics/metrics-datastream-1.0.0.mapping#L131 and https://github.com/opensearch-project/opensearch-catalog/blob/main/docs/schema/observability/metrics/metrics.md are using `bucketCount` (without `s`)

Not sure, which way is easier to fix.

### exemplar(s)
https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-api/src/main/java/org/opensearch/dataprepper/model/metric/JacksonMetric.java#L38 and https://opentelemetry.io/docs/specs/otel/metrics/data-model/#exemplars use the plural `exemplars`, while the template is using singular `exemplar` (https://github.com/opensearch-project/opensearch-catalog/blob/main/schema/observability/metrics/metrics-datastream-1.0.0.mapping#L35 , https://github.com/opensearch-project/opensearch-catalog/blob/main/schema/observability/metrics/metrics-datastream-1.0.0.mapping#L208 and https://github.com/opensearch-project/opensearch-catalog/blob/main/docs/schema/observability/metrics/metrics.md)

With all those changes, at least, data can be ingested into my 3 signal indices.

Again...I hope, that this information is useful for you.

Some screenshots:

![Image](https://github.com/user-attachments/assets/b7ebbb5d-d739-4c0c-8a17-143b8199e87e)

![Image](https://github.com/user-attachments/assets/aa5b1207-2622-46b6-bd63-84989ab5d7bd)

![Image](https://github.com/user-attachments/assets/f1997661-b546-4ac6-aba0-06630976a17a)

**Comment by rpasche** [comment]
Hehe...now I also found: https://github.com/opensearch-project/data-prepper/pull/5524. I think, having the `output_format` documented in traces, logs and metrics source would greatly help users struggling to keep the OTLP format as much as possible.

Thanks.

**Comment by kkondaka** [comment]
@rpasche Yes, we will update the documentation about `output_format`. There is also new index templates that you should be using when using `output_format: otel`,
For logs, use `index_type: "log-analytics-standard"` in opensearch sink config.
For metrics, use `index_type: "metric-analytics-standard"` in opensearch sink config.
For traces, use `index_type: "trace-analytics-standard"` in opensearch sink config.
With this config change, you should see ss4o compliant data in opensearch

**Comment by ps48** [comment]
@rpasche Can you please try our OTel demo fork. It is using the latest data prepper OTel schemas now: https://github.com/opensearch-project/opentelemetry-demo

**Comment by Blarc** [comment]
Hey @rpasche,

would you mind sharing your data-prepper pipeline configuration?. I am trying to do the same thing as you, but I can't get it to work.

Thanks 🙏 .

**Comment by rpasche** [comment]
@Blarc Please note. I am also very new to data-prepper and opensearch at all. See below my config, that I currently use. And I still saw some issue that were causing *mapping conflicts*....and I was not yet fully able to solve them. Some events seem to have provided fields like `status` and some pushed that field as an `object`. So I tried my best.....but as said....still have some issues.

But *most* of the events seem to be flowing in....

So take this *as-is*. This is still my *playground* configuration.....

Sometimes, I temporarily enabled the `stdout` sink to have a look at the JSON structure....

```
pipelineConfig:
  enabled: true
  config:
    main:
      source:
        otlp:
          ssl: false
      route:
        - logs: 'getEventType() == "LOG"'
        - traces: 'getEventType() == "TRACE"'
        - metrics: 'getEventType() == "METRIC"'
      sink:
        - pipeline:
            name: "otel-logs-pipeline"
            routes:
              - "logs"
        - pipeline:
            name: "otel-traces-pipeline"
            routes:
              - "traces"
        - pipeline:
            name: "otel-metrics-pipeline"
            routes:
              - "metrics"
    otel-logs-pipeline:
      workers: 2
      #delay: 10
      source:
        pipeline:
          name: "main"
      buffer:
        bounded_blocking:
          # buffer_size is the number of ExportTraceRequest from otel-collector the data prepper should hold in memeory.
          # We recommend to keep the same buffer_size for all pipelines.
          # Make sure you configure sufficient heap
          # default value is 512
          buffer_size: 4096
          # This is the maximum number of request each worker thread will process within the delay.
          # Default is 8.
          # Make sure buffer_size >= workers * batch_size
          batch_size: 2048
      processor:
        - add_entries:
            entries:
              - key: "@timestamp"
                value_expression: /time
                add_when: /@timestamp == null and /time != null
              - key: "@timestamp"
                value_expression: /timestamp
                add_when: /@timestamp == null and /timestamp != null
              - key: "@timestamp"
                value_expression: /observedTimestamp
                add_when: /@timestamp == null and /observedTimestamp != null
        - rename_keys:
            entries:
              - from_key: "severityText"
                to_key: "severity/text"
              - from_key: "severityNumber"
                to_key: "severity/number"
              - from_key: "upstream_cluster"
                to_key: "attributes/upstream/cluster"
              - from_key: "user_agent"
                to_key: "attributes/user_agent/original"

      sink:
        # - stdout:
        - opensearch:
            hosts: ["<opensearch-endpoint>"]
            cert: "<path_to_ca_cert>"
            username: "<user>"
            password: "<password>"
            insecure: true
            # # data_stream config
            # # you need to pre-create the index (in this case, the data_stream via API!)
            index_type: management_disabled
            index: ss4o_logs-demo-poc
            action: create
            # # new ss4o index type for logs
            # # legacy index-template
            # index_type: "log-analytics-plain"
            bulk_size: 4

    otel-metrics-pipeline:
      workers: 2
      #delay: 3000
      source:
        pipeline:
          name: "main"
      buffer:
        bounded_blocking:
          # buffer_size is the number of ExportTraceRequest from otel-collector the data prepper should hold in memeory.
          # We recommend to keep the same buffer_size for all pipelines.
          # Make sure you configure sufficient heap
          # default value is 512
          buffer_size: 4096
          # This is the maximum number of request each worker thread will process within the delay.
          # Default is 8.
          # Make sure buffer_size >= workers * batch_size
          batch_size: 2048
      processor:
        - add_entries:
            entries:
              - key: "@timestamp"
                value_expression: /startTime
                add_when: /@timestamp == null and /startTime != null
        - otel_metrics:
            calculate_histogram_buckets: true
            calculate_exponential_histogram_buckets: true
            exponential_histogram_max_allowed_scale: 10
            flatten_attributes: false
        - rename_keys:
            entries:
              - from_key: "/attributes/status"
                to_key: "/attributes/status_tmp"
                rename_when: '/attributes/status != null and /attributes/status/code == null'
              - from_key: "/attributes/user_agent"
                to_key: "/attributes/user_agent_tmp"
                rename_when: '/attributes/user_agent != null and /attributes/user_agent/original == null'
        - copy_values:
            entries:
              - from_key: "/attributes/status_tmp"
                to_key: "/attributes/status/code"
                copy_when: '/attributes/status_tmp != null'
              - from_key: "/attributes/user_agent_tmp"
                to_key: "/attributes/user_agent/original"
                copy_when: '/attributes/user_agent_tmp != null'
        - delete_entries:
            with_keys: ["/attributes/status_tmp", "/attributes/user_agent_tmp"]
      sink:
        # - stdout:
        - opensearch:
            hosts: ["<opensearch-endpoint>"]
            cert: "<path_to_ca_cert>"
            username: "<user>"
            password: "<password>"
            insecure: true
            # # data_stream config
            # # you need to pre-create the index (in this case, the data_stream via API!)
            index_type: management_disabled
            index: ss4o_metrics-demo-poc
            action: create
            # # new ss4o index type for logs
            # # legacy index template
            # index_type: "metric-analytics-plain"
            bulk_size: 4

    otel-traces-pipeline:
      workers: 2
      delay: "100"
      source:
        pipeline:
          name: "main"
      buffer:
        bounded_blocking:
          # buffer_size is the number of ExportTraceRequest from otel-collector the data prepper should hold in memeory.
          # We recommend to keep the same buffer_size for all pipelines.
          # Make sure you configure sufficient heap
          # default value is 512
          buffer_size: 2048
          # This is the maximum number of request each worker thread will process within the delay.
          # Default is 8.
          # Make sure buffer_size >= workers * batch_size
          batch_size: 512
      processor:
        - add_entries:
            entries:
              - key: "@timestamp"
                value_expression: /startTime
                add_when: /@timestamp == null and /startTime != null
      sink:
        # - stdout:
        - opensearch:
            hosts: ["<opensearch-endpoint>"]
            cert: "<path_to_ca_cert>"
            username: "<user>"
            password: "<password>"
            insecure: true
            index: ss4o_traces-demo-poc
            index_type: management_disabled
            action: create
        - pipeline:
            name: "raw-trace-pipeline"
        - pipeline:
            name: "service-map-pipeline"

    raw-trace-pipeline:
      workers: 2
      source:
        pipeline:
          name: "otel-traces-pipeline"
      processor:
        - otel_trace_raw: {}
        - otel_trace_group:
            hosts: ["<opensearch-endpoint>"]
            cert: "<path_to_ca_cert>"
            username: "<user>"
            password: "<password>"
            insecure: true
      buffer:
        bounded_blocking:
          # buffer_size is the number of ExportTraceRequest from otel-collector the data prepper should hold in memeory.
          # We recommend to keep the same buffer_size for all pipelines.
          # Make sure you configure sufficient heap
          # default value is 512
          buffer_size: 2048
          # This is the maximum number of request each worker thread will process within the delay.
          # Default is 8.
          # Make sure buffer_size >= workers * batch_size
          batch_size: 512
      sink:
        # - stdout:
        - opensearch:
            hosts: ["<opensearch-endpoint>"]
            cert: "<path_to_ca_cert>"
            username: "<user>"
            password: "<password>"
            insecure: true
            index_type: "trace-analytics-plain-raw"

    service-map-pipeline:
      workers: 2
      delay: "100"
      source:
        pipeline:
          name: "otel-traces-pipeline"
      processor:
        - service_map: {}
      buffer:
        bounded_blocking:
          # buffer_size is the number of ExportTraceRequest from otel-collector the data prepper should hold in memeory.
          # We recommend to keep the same buffer_size for all pipelines.
          # Make sure you configure sufficient heap
          # default value is 512
          buffer_size: 1024
          # This is the maximum number of request each worker thread will process within the delay.
          # Default is 8.
          # Make sure buffer_size >= workers * batch_size
          batch_size: 512
      sink:
        # - stdout:
        - opensearch:
            hosts: ["<opensearch-endpoint>"]
            cert: "<path_to_ca_cert>"
            username: "<user>"
            password: "<password>"
            insecure: true
            index_type: trace-analytics-service-map
```
