### ISSUE TITLE
DataPrepper validator should validating the expressions and functions inside the expressions

### ISSUE THREAD

**Issue by san81** [opensearch-project/data-prepper#5840]
**Is your feature request related to a problem? Please describe.**
DataPrepper validations are not validating or catching unknown functions inside an expression. For example

```
processor:
   - drop_events:
     drop_when: "not exists(/index)"
     handle_failed_events: drop
```
DataPrepper validation pass above configuration. But it could possibly validate the function given in the expression as well.

**Describe the solution you'd like**
Expressions are validate at the pipeline configuration validation step itself.
