### ISSUE TITLE
OpenSearch Client Certificate Authentication

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#633]
**Is your feature request related to a problem? Please describe.**

Data Prepper supports HTTP Basic authentication to OpenSearch clusters. However, it does not support [client certificate authentication](https://opensearch.org/docs/latest/security-plugin/configuration/client-auth/). As a client, Data Prepper can authenticate using a client certificate. This can replace HTTP Basic authentication or be combined with HTTP Basic authentication.

**Describe the solution you'd like**

Provide a mechanism for client client certificate authentication to OpenSearch clusters. Data Prepper pipeline authors would need to supply as input paths to both a certificate file and a private key file. Additionally, Data Prepper should allow this in conjunction with HTTP Basic authentication, for any cluster which requires both.

```
sink:
  - opensearch:
      authentication:
        mutual_tls:
          private_key: -----BEGIN PRIVATE KEY----- ...
```

**Additional context**

This was originally requested in a discussion as part of #310.

**Comment by faxm0dem** [comment]
We'd also very much like this functionality.
I feel that data-prepper should support most if not all supported authentication methods supported by OpenSearch.

**Comment by sheariley** [comment]
I've got mTLS working on all other components of my OTel stack. Now, if I want to use Data Prepper -> OpenSearch, I have to go back and disable mTLS for all existing components that communicate with OpenSearch.

**Comment by srikanthpadakanti** [comment]
@dlvenable Please assign this to me. Thanks

**Comment by srikanthpadakanti** [comment]
@dlvenable  I am leaning toward keeping `client_cert` and `client_key` at the top level rather than nesting them under `authentication.mutual_tls`, mainly for consistency since trust_cert is already a top level field.

lmk your thoughts. Thanks

**Comment by dlvenable** [comment]
We currently have

```
sink:
  - opensearch:
      authentication:
        username: myuser
        password: secret
        api_token: abc123
```

I think we should try to keep the authentication aspects together, which is also aligns with other sinks using authentication.

```
sink:
  - opensearch:
      authentication:
        client_certificate: -----BEGIN CERTIFICATE----- ...
        client_key: -----BEGIN PRIVATE KEY----- ...
```

We are also trying to avoid the term `cert` in favor of the full word `certificate` going forward.
