### ISSUE TITLE
Support encoding JSON

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/data-prepper#832]
**Is your feature request related to a problem? Please describe.**

In some scenarios, pipelines should be able to encode objects as a JSON string. Data Prepper should provide a feature for this.

**Describe the solution you'd like**

Provide a processor for encoding JSON - `encode_json`. It should be the inverse of the JSON parsing processor from #831.

**Example**

Given the following configuration:
```
processor:
  encode_json:
    source: my_object
    target: json_string
```

Given this input event:

```
"my_object" : {
  "key1" : "value1",
  "key2" : "value2",
}
```

The event is changed to:

```
"my_object" : {
  "key1" : "value1",
  "key2" : "value2",
}
"json_string" : "{\"key1\" : \"value1\", \"key2\" : \"value2\"}"
```

**Comment by dlvenable** [comment]
Per the request in #852, it would be good to keep these different encoders similar.

Two possible options to consider:
1. Create an abstract base class for encoding and a standard encoding configuration model. Extend this for both the `encode_json` and `encode_message_pack` plugins.

This might look like:

```
public abstract class AbstractEncoder implements Processor {
   ...
   abstract String encode(Map<String, Object> target);
}

class EncoderConfig {
   private String source;
   private String target;
   ...
}

@DataPrepperPlugin(name = "encode_json", pluginConfigurationType = EncoderConfig.class)
public class JsonEncoder extends AbstractEncoder{
...
}

@DataPrepperPlugin(name = "encode_message_pack", pluginConfigurationType = EncoderConfig.class)
public class MessagePackEncoder extends AbstractEncoder{
...
}

```

2. Create a single `encoder` processor which supports various encodings via a plugin.

This could be configured by authors like:

```
processor:
  encoder:
    encoding: json
    source: my_object
    target: json_string
  encoder:
    encoding: message_pack
    source: my_object
    target: message_pack_string
```

**Comment by sharraj** [comment]
We should not have processor names with actions in it. Ideally processor name should be "json" with action as "encode json". There can be cases where we need same json processor with say action "decode json".

**Comment by kkondaka** [comment]
@dlvenable @sharraj How about this?
```
processor:
   - write_json:
        serialization_type: "string" (or XMLstring or something else in future)
        source: my_object
        target: target_name
```
