### ISSUE TITLE
Robust CombineAggregateAction

### ISSUE THREAD

**Issue by graytaylor0** [opensearch-project/data-prepper#855]
**Is your feature request related to a problem? Please describe.**
The [RFC for Stateful Aggregation]() provides an example of a basic `CombineAggregateAction` that creates an aggregated Event by simply using `putAll`, which will overwrite any existing keys of the combined Event. 

**Describe the solution you'd like**
We should discuss a solution for providing a more robust `CombineAggregateAction`. Instead of simply overwriting keys that have merge conflicts, we can make the merging logic configurable for the user. For example, an additional configuration option for merging could look like this if the desire was to overwrite the keys:

```
processor:
  - aggregate:
      identification_keys:
        - 'sourceIp'
        - 'destinationIp'
        - 'port'
      window_duration: 180
      data_path: data/aggregate
      action:
        combine:
          merge_function: overwrite
```

And then if a user wanted to instead append to a list of values instead of overwrite, they could change the merge function to something like `append`, which would push the new conflicting key value to the end of a list

```
processor:
  - aggregate:
      identification_keys:
        - 'sourceIp'
        - 'destinationIp'
        - 'port'
      window_duration: 180
      data_path: data/aggregate
      action:
        combine:
          merge_function: append
```
Ideally, we can cover as many common merge functions as possible out of the box. However, we should also try to make it as easy as possible for the user to create their own custom merge functions.

**Alternative Solution**
The alternative to this solution is to simply make a completely new `AggregateAction `when a user does not wish to simply overwrite keys.

**Comment by dlvenable** [comment]
I think this idea. Perhaps instead we can replace `combine` with both `merge` and `append` actions. The current `combine` is so simple that it might just be easier for pipeline authors to have two different actions instead of customizing one action. And there is no need to worry about what the default behavior is.

**Comment by graytaylor0** [comment]
That is the alternative. Are there other algorithms users will want to combine Events into a larger one? Because if there are more than a couple then it might make more sense to have the single `combine` and make it configurable.

**Comment by graytaylor0** [comment]
After further consideration, I believe that each special operation should get its own `AggregateAction`. For example, in the case of the action that simply uses `putAll`, this action should be called something like `put_all` or `merge_all`. A separate action could be named `append`, and it could simply append all values to a list when a key collision occurs.

**Comment by graytaylor0** [comment]
Following this model, here are some additional ideas for other `AggregateAction`...

`sum` : Sum all numeric values that have key collisions together

`concatenate`: Concatenate all strings that have key collision together
```yaml
action:
    concatenate:
        delimiter: '\n'
```
