### ISSUE TITLE
Support default timestamp for events

### ISSUE THREAD

**Issue by asifsmohammed** [opensearch-project/data-prepper#930]
**Is your feature request related to a problem? Please describe.**
Data Prepper events doesn't have a default timestamp field for any event type. 

**Describe the solution you'd like**
We can implement this by updating the JSON node in the constructor of `JacksonEvent`

**Additional context**
- To implement Data processor(#509) we need a default timestamp field 
-  This will also help customers visualize events over time

**Comment by cmanning09** [comment]
Thanks @asifsmohammed, I have a couple questions:

- What will the default timestamp field be called?
- What will the format of the timestamp be? (Are we going to use ISO 8601?)
- Can customers configure this field? (i.e. possibly set the timezone?)

**Comment by asifsmohammed** [comment]
- Default timestamp will be called `event_timestamp`. Please let me know if there are any other suggestions. 
- Timestamp will be generated using `ZonedDateTime` of Java Date Time and it follows ISO 8601 format. 
- Default timestamp is not configurable by customer. If needed they can create a new field for timestamp with desired format using `destination` configuration option in date processor.

**Comment by asifsmohammed** [comment]
There are few other things we might need to address,

- Do we need to specify the default time zone like `UTC` for default timestamp or just leave it to JVM default time zone?
- Is there any specific use case to name the field starting with @?

**Comment by dlvenable** [comment]
@asifsmohammed ,

Regarding the time zone, I believe the default should be to use the time zone of the Data Prepper instance. This can be converted into UTC by the OpenSearch of other clients. But, we can't later go back from UTC to the instance time zone without additional information. 

If users desire, we could make a configuration to support UTC by default in the future.

Regarding the `@` in timestamp, I believe Data Prepper should include it, only if it has special meaning to OpenSearch or OpenSearch Dashboards. Otherwise, I don't see any reason to choose to include the `@` prefix.

**Comment by dlvenable** [comment]
@asifsmohammed , It does appear that some features of OpenSearch Dashboards are enhanced with the use of `@timestamp`.

https://opensearch.org/docs/latest/opensearch/data-streams/#step-1-create-an-index-template

**Comment by dlvenable** [comment]
Another consideration could be using a a Data Prepper-specific field. Let's say it were `event_timestamp`. Then the OpenSearch sink would be responsible for moving this from `event_timestamp` to `@timestamp`. There may be future sinks which use different naming conventions.

**Comment by asifsmohammed** [comment]
> @asifsmohammed ,
> 
> Regarding the time zone, I believe the default should be to use the time zone of the Data Prepper instance. This can be converted into UTC by the OpenSearch of other clients. But, we can't later go back from UTC to the instance time zone without additional information.
> 
> If users desire, we could make a configuration to support UTC by default in the future.

In future if there are multiple sources running in different regions with same sink then there might be a conflict in the timestamp. Although, the default timestamp represents when the event is created by Data Prepper and not the true representation of when the event actually happened.

**Comment by dlvenable** [comment]
> In future if there are multiple sources running in different regions with same sink then there might be a conflict in the timestamp.

By default ISO-8601 serializes the time zone offset. So even if Data Prepper instances are running in different time zones, that information is still present.

**Comment by asifsmohammed** [comment]
> @asifsmohammed , It does appear that some features of OpenSearch Dashboards are enhanced with the use of `@timestamp`.
> 
> https://opensearch.org/docs/latest/opensearch/data-streams/#step-1-create-an-index-template

After doing some research about this, I think we should name it `@timestamp` instead of `event_timestamp` whcih requires a custom index template.

**Comment by dlvenable** [comment]
One consideration is whether users want to have the `@timestamp` field in their events or not. This field will eventually be stored in the sinks.

This issue proposes that Data Prepper set the `@timestamp` automatically. Users could still remove it with the upcoming #508 plugin.

e.g.

```
log-pipeline:
  source:
    http:
  prepper:
    - mutate:
        delete_key: '@timestamp'
    - grok:
        match:
          log: [ "%{COMMONAPACHELOG}" ]
  sink:
    - opensearch:
        hosts: [ "https://opensearch:9200" ]
        index: apache_logs
```

But, should users get the timestamp implicitly or explicitly?

An explicit approach is to require users to specifically state that they want to use the time received as the timestamp. Data Prepper already records the time received and makes it available in [EventMetadata::getTimeReceived](https://github.com/opensearch-project/data-prepper/blob/675bc96331367f657c24d4dcf23ac89258c76b07/data-prepper-api/src/main/java/com/amazon/dataprepper/model/event/EventMetadata.java#L29). A processor could support reading the time received and setting that as the timestamp.


In the following example, the `timestamp_from_time_received` processor reads the time received and sets the `@timestamp`. It could allow a configuration for the destination as well.

```
log-pipeline:
  source:
    http:
  prepper:
    - timestamp_from_time_received:
    - grok:
        match:
          log: [ "%{COMMONAPACHELOG}" ]
  sink:
    - opensearch:
        hosts: [ "https://opensearch:9200" ]
        index: apache_logs
```

There is an issue for parsing dates from other fields in #509 . Perhaps this processor could support a configuration which reads the timestamp from the EventMetadata. This would avoid the need for another processor.

For example:

```
log-pipeline:
  source:
    http:
  prepper:
    - date:
         timestamp_from_time_received: true
    - grok:
        match:
          log: [ "%{COMMONAPACHELOG}" ]
  sink:
    - opensearch:
        hosts: [ "https://opensearch:9200" ]
        index: apache_logs
```

**Comment by asifsmohammed** [comment]
I like the suggestions for making it either implicit or explicit. With implicit approach it comes down to how we overwrite the `@timestamp` if user already provides it.

I think with explicit approach we should use date processor #509 instead of creating a new processor. The default value for `timestamp_from_time_received` would be `false`.

1. If user wants `@timestamp` field and it's not part of the input, they can set the`timestamp_from_time_received` flag to true in date processor.

2. If an user wants to extract date from other field to `@timestamp` they can just configure match and leave the `timestamp_from_time_received` and `destination` to default values. Default value for destination is `@timestamp`.
For example:
```
log-pipeline:
  source:
    http:
  prepper:
    - date:
         match:
             timestamp_field:
                 - pattern1
                 - pattern2
  sink:
    - opensearch:
        hosts: [ "https://opensearch:9200" ]
```


3. If user wants to overwrite `@timestamp` with [EventMetadata::getTimeReceived](https://github.com/opensearch-project/data-prepper/blob/675bc96331367f657c24d4dcf23ac89258c76b07/data-prepper-api/src/main/java/com/amazon/dataprepper/model/event/EventMetadata.java#L29) and extract date from any field to a new field the configuration would look like this
```
log-pipeline:
  source:
    http:
  prepper:
    - date:
         timestamp_from_time_received: true
         match:
             timestamp_field:
                 - pattern1
                 - pattern2
         destination: new_timestamp_field
  sink:
     - opensearch:
         hosts: [ "https://opensearch:9200" ]
 ```

**Comment by dlvenable** [comment]
I also like the idea of using the processor from #509.

But, I think it would be more natural for either `timestamp_from_time_received` or `match` to set the same field - the `destination`. Maybe the name `from_time_received` rather than `timestamp_from_time_received` would be clearer.

In this example, the Event doesn't get an `@timestamp` at all. It sets `new_timestamp_field` to the time received.

```
log-pipeline:
  source:
    http:
  prepper:
    - date:
         from_time_received: true
         destination: new_timestamp_field
  sink:
     - opensearch:
         hosts: [ "https://opensearch:9200" ]
```

This would mean that `from_time_received ` and `match` are mutually exclusive and should not be used together.
